<?php
$event = $event ?? (object) [];
$category = $category ?? (object) [];
$match = $match ?? (object) [];
$section = $section ?? "resumo";
$matchUrl = get_uri("grupo_donato/operacional/evento/" . (int) $event->id . "/categoria/" . (int) $category->id . "/partida/" . (int) $match->id);
$categoryUrl = get_uri("grupo_donato/operacional/evento/" . (int) $event->id . "/categoria/" . (int) $category->id);
$lineupLabels = ["called" => "Convocado", "starter" => "Titular", "substitute" => "Reserva", "absent" => "Ausente", "cut" => "Cortado"];
$breadcrumbs = [["label" => "GD Academy", "url" => get_uri("grupo_donato/operacional?gd_tab=alunos")], ["label" => "Eventos", "url" => get_uri("grupo_donato/operacional?gd_tab=eventos")], ["label" => (string) ($event->name ?? "Evento"), "url" => get_uri("grupo_donato/operacional/evento/" . (int) $event->id)], ["label" => (string) ($category->name ?? "Categoria"), "url" => $categoryUrl], ["label" => (string) ($match->name ?? "Partida")]];
?>
<?php echo view('grupo_donato_gestao\Operacional\Views\_academy_styles'); ?>
<div id="page-content" class="page-wrapper clearfix gd-academy-page">
    <?php echo view('grupo_donato_gestao\Operacional\Views\_academy_breadcrumbs', ["breadcrumbs" => $breadcrumbs]); ?>
    <?php echo view('grupo_donato_gestao\Operacional\Views\_academy_match_nav', ["event" => $event, "category" => $category, "match" => $match, "section" => $section]); ?>

    <?php if ($section === "resumo"): ?>
        <div class="row"><div class="col-md-7 mb15"><div class="gd-academy-card"><h3>Informações da partida</h3><div class="row"><div class="col-sm-6 mb10"><span class="gd-academy-muted">Campeonato</span><br><strong><?php echo esc($event->name); ?></strong></div><div class="col-sm-6 mb10"><span class="gd-academy-muted">Categoria</span><br><a href="<?php echo esc($categoryUrl); ?>"><?php echo esc($category->name); ?></a></div><div class="col-sm-6 mb10"><span class="gd-academy-muted">Data e horário</span><br><strong><?php echo !empty($match->match_date) ? esc(date("d/m/Y", strtotime((string) $match->match_date))) : "Não informado"; ?><?php if (!empty($match->match_time)): ?> às <?php echo esc(substr((string) $match->match_time, 0, 5)); ?><?php endif; ?></strong></div><div class="col-sm-6 mb10"><span class="gd-academy-muted">Local / campo</span><br><strong><?php echo esc($match->location ?: ($match->field_name ?: "Não informado")); ?></strong></div><div class="col-sm-6"><span class="gd-academy-muted">Fase</span><br><strong><?php echo esc($match->phase ?: "Não informada"); ?></strong></div><div class="col-sm-6"><span class="gd-academy-muted">Status</span><br><strong><?php echo esc(ucfirst((string) $match->status)); ?></strong></div></div></div></div><div class="col-md-5 mb15"><div class="gd-academy-card text-center"><span class="gd-academy-muted">Placar</span><div class="display-4 font-weight-bold mt10"><?php echo $match->gd_score !== null && $match->opponent_score !== null ? (int) $match->gd_score . " × " . (int) $match->opponent_score : "—"; ?></div><div class="mt5"><?php echo esc("GD Academy x " . ($match->opponent ?: "Adversário")); ?></div><?php if ($can_manage ?? false): ?><?php echo form_open(get_uri("grupo_donato/operacional/save_event_match_score"), ["class" => "gd-academy-form-card gd-academy-ajax-form mt15 text-left"]); ?><input type="hidden" name="match_id" value="<?php echo (int) $match->id; ?>"><div class="row"><div class="col-5"><label>GD</label><input class="form-control" type="number" min="0" name="gd_score" value="<?php echo esc($match->gd_score ?? ""); ?>"></div><div class="col-2 text-center pt25">×</div><div class="col-5"><label>Adversário</label><input class="form-control" type="number" min="0" name="opponent_score" value="<?php echo esc($match->opponent_score ?? ""); ?>"></div></div><input type="hidden" name="status" value="completed"><button class="btn btn-primary btn-sm mt10" type="submit">Salvar placar</button><?php echo form_close(); ?><?php endif; ?></div></div></div>
        <div class="row"><div class="col-md-4 mb10"><a class="gd-academy-card d-block" href="<?php echo esc($matchUrl . "/escalacao"); ?>"><h3>Ver escalação</h3><span class="gd-academy-muted">Organize titulares e reservas.</span></a></div><div class="col-md-4 mb10"><a class="gd-academy-card d-block" href="<?php echo esc($matchUrl . "/estatisticas"); ?>"><h3>Ver estatísticas</h3><span class="gd-academy-muted">Registre o desempenho individual.</span></a></div></div>

    <?php elseif ($section === "escalacao"): ?>
        <div class="gd-academy-section-title"><div><h2>Escalação</h2><p class="gd-academy-muted mb0">Titulares e reservas da partida <?php echo esc($match->name); ?>.</p></div></div>
        <?php if (empty($participants)): ?><div class="gd-academy-empty"><i data-feather="users" class="icon-28"></i><h3>Nenhum atleta disponível</h3><p>Convocados ativos da categoria aparecerão nesta partida.</p></div><?php else: ?><div class="row"><div class="col-md-6 mb15"><div class="gd-academy-card"><h3>Titulares</h3><?php $starters = array_values(array_filter($participants, static fn($row): bool => ($row->lineup_status ?? "") === "starter")); ?><?php if (!$starters): ?><p class="gd-academy-muted">Nenhum titular definido.</p><?php else: ?><div class="gd-academy-list"><?php foreach ($starters as $player): ?><div class="gd-academy-list-item"><div class="gd-academy-list-item-main"><strong><?php echo esc($player->athlete_name); ?></strong><small><?php echo esc($player->position ?: "Posição não definida"); ?></small></div></div><?php endforeach; ?></div><?php endif; ?></div></div><div class="col-md-6 mb15"><div class="gd-academy-card"><h3>Reservas e convocados</h3><?php $reserves = array_values(array_filter($participants, static fn($row): bool => ($row->lineup_status ?? "") !== "starter")); ?><?php if (!$reserves): ?><p class="gd-academy-muted">Todos os atletas estão entre os titulares.</p><?php else: ?><div class="gd-academy-list"><?php foreach ($reserves as $player): ?><div class="gd-academy-list-item"><div class="gd-academy-list-item-main"><strong><?php echo esc($player->athlete_name); ?></strong><small><?php echo esc($lineupLabels[$player->lineup_status] ?? $player->lineup_status); ?></small></div></div><?php endforeach; ?></div><?php endif; ?></div></div></div><?php if ($can_lineup ?? false): ?><div class="gd-academy-form-card"><h3>Atualizar situação</h3><div class="gd-academy-list"><?php foreach ($participants as $player): ?><?php echo form_open(get_uri("grupo_donato/operacional/update_event_participant"), ["class" => "gd-academy-list-item gd-academy-ajax-form"]); ?><input type="hidden" name="participant_id" value="<?php echo (int) $player->participant_id; ?>"><div class="gd-academy-list-item-main"><strong><?php echo esc($player->athlete_name); ?></strong><small><?php echo esc($player->position ?: "Posição não definida"); ?></small></div><select class="form-control" name="lineup_status" style="max-width:170px"><?php foreach ($lineupLabels as $key => $label): ?><option value="<?php echo esc($key); ?>" <?php echo $player->lineup_status === $key ? "selected" : ""; ?>><?php echo esc($label); ?></option><?php endforeach; ?></select><input class="form-control" name="position" value="<?php echo esc($player->position ?? ""); ?>" placeholder="Posição" style="max-width:150px"><button class="btn btn-default btn-sm" type="submit">Salvar</button><?php echo form_close(); ?><?php endforeach; ?></div></div><?php endif; ?><?php endif; ?>

    <?php elseif ($section === "estatisticas"): ?>
        <div class="gd-academy-section-title"><div><h2>Estatísticas da partida</h2><p class="gd-academy-muted mb0">Registre somente atletas desta partida.</p></div></div>
        <?php if (empty($participants)): ?><div class="gd-academy-empty"><i data-feather="bar-chart-2" class="icon-28"></i><h3>Nenhum atleta disponível</h3><p>Convocados ativos aparecerão nesta tela.</p></div><?php else: ?><div class="gd-academy-list"><?php foreach ($participants as $player): ?><div class="gd-academy-form-card"><div class="d-flex align-items-center justify-content-between mb10"><div><strong><?php echo esc($player->athlete_name); ?></strong><div class="gd-academy-muted"><?php echo esc($player->lineup_status ?: "Convocado"); ?></div></div><span class="gd-academy-status gd-academy-status-muted">Estatística individual</span></div><?php if ($can_evaluate ?? false): ?><?php echo form_open(get_uri("grupo_donato/operacional/save_event_stat"), ["class" => "gd-academy-ajax-form"]); ?><input type="hidden" name="participant_id" value="<?php echo (int) $player->participant_id; ?>"><input type="hidden" name="match_id" value="<?php echo (int) $match->id; ?>"><div class="row"><div class="col-6 col-md-2 form-group"><label>Gols</label><input class="form-control" type="number" min="0" name="goals" value="<?php echo (int) ($player->goals ?? 0); ?>"></div><div class="col-6 col-md-2 form-group"><label>Assistências</label><input class="form-control" type="number" min="0" name="assists" value="<?php echo (int) ($player->assists ?? 0); ?>"></div><div class="col-6 col-md-2 form-group"><label>Defesas</label><input class="form-control" type="number" min="0" name="saves" value="<?php echo (int) ($player->saves ?? 0); ?>"></div><div class="col-6 col-md-2 form-group"><label>Minutos</label><input class="form-control" type="number" min="0" name="minutes_played" value="<?php echo esc($player->minutes_played ?? ""); ?>"></div><div class="col-6 col-md-2 form-group"><label>Amarelos</label><input class="form-control" type="number" min="0" name="yellow_cards" value="<?php echo (int) ($player->yellow_cards ?? 0); ?>"></div><div class="col-6 col-md-2 form-group"><label>Vermelhos</label><input class="form-control" type="number" min="0" name="red_cards" value="<?php echo (int) ($player->red_cards ?? 0); ?>"></div></div><div class="row"><div class="col-md-10 form-group"><label>Observação</label><input class="form-control" name="notes" value="<?php echo esc($player->stat_notes ?? ""); ?>"></div><div class="col-md-2 form-group d-flex align-items-end"><button class="btn btn-primary w-100" type="submit">Salvar</button></div></div><?php echo form_close(); ?><?php else: ?><p class="gd-academy-muted mb0">Você não possui permissão para registrar estatísticas.</p><?php endif; ?></div><?php endforeach; ?></div><?php endif; ?>
    <?php endif; ?>
</div>
<?php echo view('grupo_donato_gestao\Operacional\Views\_academy_actions'); ?>
