<?php
$types = ["championship" => "Campeonato", "cup" => "Copa", "tournament" => "Torneio", "friendly" => "Amistoso", "festival" => "Festival", "single_game" => "Jogo isolado", "official" => "Competição oficial", "unofficial" => "Competição não oficial", "other" => "Outro"];
$breadcrumbs = [["label" => "GD Academy", "url" => get_uri("grupo_donato/operacional?gd_tab=alunos")], ["label" => "Eventos", "url" => get_uri("grupo_donato/operacional?gd_tab=eventos")], ["label" => "Novo evento"]];
?>
<?php echo view('grupo_donato_gestao\Operacional\Views\_academy_styles'); ?>
<div id="page-content" class="page-wrapper clearfix gd-academy-page">
    <?php echo view('grupo_donato_gestao\Operacional\Views\_academy_breadcrumbs', ["breadcrumbs" => $breadcrumbs]); ?>
    <div class="gd-academy-header"><div><div class="gd-academy-kicker">GD Academy · Eventos</div><h1>Novo evento</h1><div class="gd-academy-subtitle">Crie o contexto básico primeiro. Categorias, atletas e partidas são configurados depois.</div></div><div class="gd-academy-header-actions"><a class="btn btn-default" href="<?php echo esc(get_uri("grupo_donato/operacional?gd_tab=eventos")); ?>">← Eventos</a></div></div>
    <?php echo form_open(get_uri("grupo_donato/operacional/save_event"), ["id" => "gd-academy-new-event-form", "class" => "gd-academy-form-card mt20"]); ?><input type="hidden" name="status" value="draft"><div class="gd-academy-card mb15"><h3>Informações básicas</h3><div class="form-group"><label>Nome do evento</label><input class="form-control" name="name" placeholder="Ex.: Copa MU 2026" required autofocus></div><div class="row"><div class="col-md-6 form-group"><label>Tipo</label><select class="form-control" name="event_type"><?php foreach ($types as $key => $label): ?><option value="<?php echo esc($key); ?>"><?php echo esc($label); ?></option><?php endforeach; ?></select></div><div class="col-md-6 form-group"><label>Local</label><input class="form-control" name="location" placeholder="Ex.: Arena X"></div><div class="col-md-6 form-group"><label>Data inicial</label><input class="form-control" type="date" name="starts_on" value="<?php echo esc(date("Y-m-d")); ?>" required></div><div class="col-md-6 form-group"><label>Data final</label><input class="form-control" type="date" name="ends_on"></div><div class="col-md-6 form-group"><label>Horário</label><input class="form-control" type="time" name="event_time"></div><div class="col-md-6 form-group"><label>Organização / promotor</label><input class="form-control" name="organizer"></div></div></div><div class="gd-academy-card mb15"><h3>Financeiro e observações <span class="gd-academy-muted">(opcional)</span></h3><div class="row"><div class="col-md-6 form-group"><label>Valor padrão por atleta (R$)</label><input class="form-control" name="default_participation_amount" inputmode="decimal" placeholder="0,00"></div><div class="col-md-6 form-group"><label>Endereço</label><input class="form-control" name="address"></div></div><div class="form-group"><label>Descrição curta</label><textarea class="form-control" name="description" rows="3" placeholder="Contexto do evento para a equipe."></textarea></div></div><div class="gd-academy-sticky-actions"><button class="btn btn-primary" type="submit">Criar evento</button><a class="btn btn-link" href="<?php echo esc(get_uri("grupo_donato/operacional?gd_tab=eventos")); ?>">Cancelar</a></div><?php echo form_close(); ?>
</div>
<?php echo view('grupo_donato_gestao\Operacional\Views\_academy_actions'); ?>
<script>
$(function(){
    $("#gd-academy-new-event-form").off("submit.gdAcademyNew").on("submit.gdAcademyNew",function(e){e.preventDefault();var form=this,button=$(form).find("button[type='submit']");button.prop("disabled",true).text("Criando...");appAjaxRequest({url:form.action,type:"POST",data:$(form).serialize(),dataType:"json",success:function(result){if(result&&result.success&&result.data&&result.data.id){window.location.href="<?php echo get_uri("grupo_donato/operacional/evento"); ?>/"+result.data.id;return;}appAlert.error((result&&result.message)||"Não foi possível criar o evento.");button.prop("disabled",false).text("Criar evento");},error:function(){appAlert.error("Não foi possível criar o evento.");button.prop("disabled",false).text("Criar evento");}});});
});
</script>
