<?php
$e = static fn($value) => htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8");
$id = (int) ($model_info->id ?? 0);
?>
<?php echo form_open(get_uri("grupo_donato/account-people/save"), ["id" => "gd-relation-form", "class" => "general-form", "role" => "form"]); ?>
<div class="modal-body clearfix"><div class="container-fluid">
    <input type="hidden" name="id" value="<?php echo $id; ?>">
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_customer_account"); ?></label><div class="col-md-9"><select name="account_id" class="form-control" data-rule-required="true"><option value=""></option><?php foreach ($accounts as $account) { ?><option value="<?php echo (int) $account->id; ?>"<?php echo (int) $account_id === (int) $account->id ? " selected" : ""; ?>><?php echo $e($account->display_name); ?></option><?php } ?></select></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_person"); ?></label><div class="col-md-9"><select name="person_id" class="form-control" data-rule-required="true"><option value=""></option><?php foreach ($people as $person) { ?><option value="<?php echo (int) $person->id; ?>"<?php echo (int) $person_id === (int) $person->id ? " selected" : ""; ?>><?php echo $e($person->full_name); ?></option><?php } ?></select></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_role"); ?></label><div class="col-md-9"><select name="role" class="form-control"><?php foreach ($roles as $option) { ?><option value="<?php echo $e($option["id"]); ?>"<?php echo ($model_info->role ?? "other") === $option["id"] ? " selected" : ""; ?>><?php echo $e($option["text"]); ?></option><?php } ?></select></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_start_date"); ?></label><div class="col-md-3"><?php echo form_input(["type" => "date", "name" => "start_date", "value" => $model_info->start_date ?? "", "class" => "form-control"]); ?></div><label class="col-md-3"><?php echo app_lang("gd_end_date"); ?></label><div class="col-md-3"><?php echo form_input(["type" => "date", "name" => "end_date", "value" => $model_info->end_date ?? "", "class" => "form-control"]); ?></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_flags"); ?></label><div class="col-md-9"><?php echo form_checkbox("is_primary", "1", !empty($model_info->is_primary)); ?> <?php echo app_lang("gd_primary"); ?>&nbsp;&nbsp; <?php echo form_checkbox("is_financial_responsible", "1", !empty($model_info->is_financial_responsible)); ?> <?php echo app_lang("gd_financial_responsible"); ?>&nbsp;&nbsp; <?php echo form_checkbox("receives_notifications", "1", !empty($model_info->receives_notifications)); ?> <?php echo app_lang("gd_receives_notifications"); ?></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_status"); ?></label><div class="col-md-9"><select name="status" class="form-control"><?php foreach (["active", "inactive", "ended"] as $status) { ?><option value="<?php echo $status; ?>"<?php echo ($model_info->status ?? "active") === $status ? " selected" : ""; ?>><?php echo app_lang("gd_status_" . $status); ?></option><?php } ?></select></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("note"); ?></label><div class="col-md-9"><?php echo form_textarea(["name" => "notes", "value" => $model_info->notes ?? "", "class" => "form-control", "rows" => 3]); ?></div></div></div>
    <?php if ($id) { ?><div class="form-group"><div class="row"><label class="col-md-3 text-danger"><?php echo app_lang("gd_end_reason"); ?></label><div class="col-md-9"><?php echo form_input(["name" => "reason", "class" => "form-control", "maxlength" => 500]); ?></div></div></div><?php } ?>
</div></div>
<div class="modal-footer"><?php if ($id) { ?><button type="button" id="gd-end-relation" class="btn btn-danger me-auto"><?php echo app_lang("gd_end_relation"); ?></button><?php } ?><button type="button" class="btn btn-default" data-bs-dismiss="modal"><?php echo app_lang("close"); ?></button><button type="submit" class="btn btn-primary"><?php echo app_lang("save"); ?></button></div>
<?php echo form_close(); ?>
<script type="text/javascript">
$(document).ready(function () { var form = $("#gd-relation-form"); form.appForm({onSuccess: function () { location.reload(); }}); $("#gd-end-relation").click(function () { if (!form.find("[name=reason]").val()) { appAlert.error('<?php echo addslashes(app_lang("gd_delete_reason_required")); ?>', {container: ".modal-body", animate: false}); return; } $.post('<?php echo_uri("grupo_donato/account-people/delete"); ?>', form.serialize(), function (result) { if (result.success) location.reload(); else appAlert.error(result.message, {container: ".modal-body", animate: false}); }, "json"); }); });
</script>
