<?php
echo "# Fase 5 — financeiro básico integrado\n";
$financeTables=['gd_financial_accounts','gd_receivables','gd_receivable_items','gd_payments','gd_payment_allocations','gd_expenses','gd_cash_movements'];
gd_assert('schema 039–045 aplicado',array_reduce($financeTables,fn($ok,$t)=>$ok&&$db->tableExists($prefix.$t),true));
(new \grupo_donato_gestao\Database\Seeds\FinanceSeeder(0))->run();
$account=$db->table($prefix.'gd_financial_accounts')->where('unit_id',$unit_id)->where('code','MAIN-CASH')->where('deleted',0)->get(1)->getRow();
gd_assert('seed cria Caixa Principal idempotente',$account&&$db->table($prefix.'gd_financial_accounts')->where('unit_id',$unit_id)->where('code','MAIN-CASH')->where('deleted',0)->countAllResults()===1);
$fin=new \grupo_donato_gestao\Services\FinanceService($unit_id);
$bank=$fin->saveAccount(['code'=>'BANK-TEST','name'=>'Banco teste','account_type'=>'bank','status'=>'active']);gd_assert('cadastra conta financeira tipada',$bank['id']>0);
$token=substr(hash('sha256',uniqid('fin',true)),0,8);
$today=gmdate('Y-m-d');
$enrollmentId=(int)$enrollment['id'];
$r1=$fin->createReceivable(['source_type'=>'enrollment','source_id'=>$enrollmentId,'reference_month'=>'2098-02','description'=>'Mensalidade '.$token,'issue_date'=>'2098-02-01','due_date'=>'2098-02-10','original_amount'=>'100.00','unit_amount'=>'100.00','quantity'=>'1']);
gd_assert('gera cobrança de matrícula integrada',!empty($r1['created'])&&$r1['id']>0);
$monthlyId=(int)$monthly['id'];
$r2=$fin->createReceivable(['source_type'=>'court_rental','source_id'=>$monthlyId,'reference_month'=>'2098-02','description'=>'Mensalista '.$token,'issue_date'=>'2098-02-01','due_date'=>'2098-02-10','original_amount'=>'150.00','unit_amount'=>'150.00','quantity'=>'1']);
gd_assert('gera cobrança de mensalista integrada',!empty($r2['created']));
$singleCharge=(new \grupo_donato_gestao\Services\ReceivableGenerationService($unit_id))->generateCourtRental((int)$single['id'],['amount'=>'80.00','due_date'=>'2098-02-05']);
gd_assert('gera cobrança avulsa integrada',!empty($singleCharge['created']));
$duplicate=$fin->createReceivable(['source_type'=>'enrollment','source_id'=>$enrollmentId,'reference_month'=>'2098-02','description'=>'Duplicada','issue_date'=>'2098-02-01','due_date'=>'2098-02-10','original_amount'=>'100.00','unit_amount'=>'100.00','quantity'=>'1']);
gd_assert('impede cobrança mensal duplicada',empty($duplicate['created'])&&!empty($duplicate['duplicate']));
$pay1=$fin->registerPayment(['amount'=>'100.00','payment_date'=>$today,'payment_method'=>'pix','financial_account_id'=>$account->id,'allocations'=>[$r1['id']=>'100.00']]);
gd_assert('pagamento total quita cobrança',$pay1['id']>0&&$fin->getReceivable($r1['id'])->status==='paid');
$pay2=$fin->registerPayment(['amount'=>'50.00','payment_date'=>$today,'payment_method'=>'cash','financial_account_id'=>$account->id,'allocations'=>[$r2['id']=>'50.00']]);
$r2partial=$fin->getReceivable($r2['id']);
gd_assert('pagamento parcial atualiza saldo',$r2partial->status==='partial'&&$r2partial->paid_amount==='50.00'&&$r2partial->balance_amount==='100.00');
$manual=$fin->createReceivable(['source_type'=>'manual','customer_account_id'=>$r2partial->customer_account_id,'description'=>'Manual '.$token,'issue_date'=>'2098-02-01','due_date'=>'2098-02-20','original_amount'=>'40.00','unit_amount'=>'40.00','quantity'=>'1']);
$multi=$fin->registerPayment(['amount'=>'70.00','payment_date'=>$today,'payment_method'=>'bank_transfer','financial_account_id'=>$account->id,'allocations'=>[$r2['id']=>'30.00',$manual['id']=>'40.00']]);
gd_assert('um pagamento aloca em várias cobranças',$multi['id']>0&&count($fin->getPayment($multi['id'])->allocations)===2);
gd_assert('alocação acima do saldo é bloqueada',gd_throws(fn()=>$fin->registerPayment(['amount'=>'999.00','payment_date'=>$today,'payment_method'=>'pix','financial_account_id'=>$account->id,'allocations'=>[$r2['id']=>'999.00']]),'gd_finance_overallocation'));
$fin->reversePayment($pay2['id'],'Teste de estorno');
gd_assert('estorno restaura saldo sem excluir pagamento',$fin->getPayment($pay2['id'])->status==='reversed'&&$fin->getReceivable($r2['id'])->paid_amount==='30.00');
$expense=$fin->saveExpense(['description'=>'Despesa teste '.$token,'payee'=>'Fornecedor','expense_date'=>$today,'paid_date'=>$today,'amount'=>'25.00','status'=>'paid','financial_account_id'=>$account->id,'payment_method'=>'pix']);
gd_assert('despesa paga gera saída',$expense['id']>0&&$db->table($prefix.'gd_cash_movements')->where('source_type','expense')->where('source_id',$expense['id'])->where('movement_type','out')->countAllResults()===1);
$movements=$fin->cashPage(['date_from'=>$today,'date_to'=>$today,'financial_account_id'=>$account->id]);
gd_assert('caixa contém entradas, saída e estorno',(bool)array_filter($movements,fn($m)=>$m->movement_type==='in')&&(bool)array_filter($movements,fn($m)=>$m->movement_type==='out'));
gd_assert('saldo acumulado é calculado exatamente',end($movements)->running_balance==='145.00');
$overdue=$fin->createReceivable(['source_type'=>'manual','customer_account_id'=>$r2partial->customer_account_id,'description'=>'Vencida '.$token,'issue_date'=>'2020-01-01','due_date'=>'2020-01-10','original_amount'=>'12.00','unit_amount'=>'12.00','quantity'=>'1']);
gd_assert('cobrança vencida recebe estado overdue',$fin->getReceivable($overdue['id'])->status==='overdue');
$summary=$fin->summary(['customer_account_id'=>$r2partial->customer_account_id]);$dashboard=$fin->dashboard($today,$today);
gd_assert('resumo contextual retorna aberto, vencido e último pagamento',isset($summary['open'],$summary['overdue'],$summary['last_payment'])&&$summary['last_payment']);
gd_assert('dashboard financeiro consolida indicadores sem float',isset($dashboard['open'],$dashboard['overdue'],$dashboard['received'],$dashboard['expenses'],$dashboard['balance'],$dashboard['debtors']));
gd_assert('movimentos de caixa bloqueiam update e delete',gd_throws(fn()=>model('grupo_donato_gestao\\Models\\Gd_cash_movements_model')->delete(1),'gd_append_only'));
$otherUnit=$db->table($prefix.'gd_units')->where('id !=',$unit_id)->where('deleted',0)->get(1)->getRow();if($otherUnit){$foreign=$db->table($prefix.'gd_receivables')->where('unit_id',(int)$otherUnit->id)->get(1)->getRow();gd_assert('IDOR financeiro respeita unidade',!$foreign||$fin->getReceivable((int)$foreign->id)===null);}else gd_assert('IDOR financeiro respeita unidade',true);
$financeAccess=new \grupo_donato_gestao\Services\AccessService($pm('gd_payments_manage'));
gd_assert('permissão de pagamento implica visão financeira',$financeAccess->can('gd_finance_view')&&!$financeAccess->can('gd_expenses_manage'));
$getFinance=$routes->getRoutes('GET');$postFinance=$routes->getRoutes('POST');
gd_assert('rotas financeiras separam leitura e escrita',isset($getFinance['grupo_donato/finance'],$getFinance['grupo_donato/finance/receivables'])&&isset($postFinance['grupo_donato/finance/payments/save'],$postFinance['grupo_donato/finance/expenses/save']));
gd_assert('CSRF protege escrita financeira',in_array('csrf',(array)get_array_value($routes->getRoutesOptions('grupo_donato/finance/payments/save','POST'),'filter'),true));
gd_assert('nenhum schema financeiro usa exclusão física',array_reduce(['gd_receivables','gd_payments','gd_expenses'],fn($ok,$t)=>$ok&&in_array('deleted',$db->getFieldNames($prefix.$t),true),true));
gd_assert('não existem campos de integração bancária',!array_filter($financeTables,fn($t)=>array_intersect(['gateway_id','bank_reconciliation_id','pix_transaction_id'],$db->getFieldNames($prefix.$t))));
