<?php $e = static fn($value) => htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8"); $id = (int) ($model_info->id ?? 0); ?>
<?php echo form_open(get_uri("grupo_donato/contacts/save"), ["id" => "gd-contact-form", "class" => "general-form", "role" => "form"]); ?>
<div class="modal-body clearfix"><div class="container-fluid">
    <input type="hidden" name="id" value="<?php echo $id; ?>"><input type="hidden" name="person_id" value="<?php echo (int) $person_id; ?>">
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_contact_type"); ?></label><div class="col-md-9"><select name="contact_type" class="form-control"><?php foreach ($types as $option) { ?><option value="<?php echo $e($option["id"]); ?>"<?php echo ($model_info->contact_type ?? "phone") === $option["id"] ? " selected" : ""; ?>><?php echo $e($option["text"]); ?></option><?php } ?></select></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_label"); ?></label><div class="col-md-9"><?php echo form_input(["name" => "label", "value" => $model_info->label ?? "", "class" => "form-control", "maxlength" => 80]); ?></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_contact_value"); ?></label><div class="col-md-9"><?php echo form_input(["name" => "value", "value" => $model_info->value ?? "", "class" => "form-control", "maxlength" => 190, "data-rule-required" => true, "data-msg-required" => app_lang("field_required")]); ?></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_flags"); ?></label><div class="col-md-9"><?php echo form_checkbox("is_primary", "1", !empty($model_info->is_primary)); ?> <?php echo app_lang("gd_primary"); ?>&nbsp;&nbsp; <?php echo form_checkbox("receives_notifications", "1", !empty($model_info->receives_notifications)); ?> <?php echo app_lang("gd_receives_notifications"); ?></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_status"); ?></label><div class="col-md-9"><select name="status" class="form-control"><option value="active"<?php echo ($model_info->status ?? "active") === "active" ? " selected" : ""; ?>><?php echo app_lang("gd_status_active"); ?></option><option value="inactive"<?php echo ($model_info->status ?? "") === "inactive" ? " selected" : ""; ?>><?php echo app_lang("gd_status_inactive"); ?></option></select></div></div></div>
    <?php if ($id) { ?><div class="form-group"><div class="row"><label class="col-md-3 text-danger"><?php echo app_lang("gd_delete_reason"); ?></label><div class="col-md-9"><?php echo form_input(["name" => "reason", "class" => "form-control", "maxlength" => 500]); ?></div></div></div><?php } ?>
</div></div>
<div class="modal-footer"><?php if ($id) { ?><button type="button" id="gd-delete-contact" class="btn btn-danger me-auto"><?php echo app_lang("delete"); ?></button><?php } ?><button type="button" class="btn btn-default" data-bs-dismiss="modal"><?php echo app_lang("close"); ?></button><button type="submit" class="btn btn-primary"><?php echo app_lang("save"); ?></button></div><?php echo form_close(); ?>
<script type="text/javascript">
$(document).ready(function () { var form = $("#gd-contact-form"); form.appForm({onSuccess: function () { location.reload(); }}); $("#gd-delete-contact").click(function () { if (!form.find("[name=reason]").val()) { appAlert.error('<?php echo addslashes(app_lang("gd_delete_reason_required")); ?>', {container: ".modal-body", animate: false}); return; } $.post('<?php echo_uri("grupo_donato/contacts/delete"); ?>', form.serialize(), function (result) { if (result.success) location.reload(); else appAlert.error(result.message, {container: ".modal-body", animate: false}); }, "json"); }); });
</script>
