<?php

declare(strict_types=1);

namespace grupo_donato_gestao\Services;

use grupo_donato_gestao\Config\Constants;

class AccountPersonService extends CustomerDataService
{
    private $model;private $accounts;private $people;
    public function __construct(int $unit_id,int $actor_id=0,?object $login_user=null){parent::__construct($unit_id,$actor_id,$login_user);$this->model=model('grupo_donato_gestao\\Models\\Gd_account_people_model');$this->accounts=model('grupo_donato_gestao\\Models\\Gd_customer_accounts_model');$this->people=model('grupo_donato_gestao\\Models\\Gd_people_model');}
    public function save(array $input,int $id=0):int
    { $old=$id?$this->model->get_scoped($id,$this->unit_id):null;if($id&&!$old)throw new \DomainException('gd_record_not_found');$account=(int)($input['account_id']??0);$person=(int)($input['person_id']??0);if(!$this->accounts->get_scoped($account,$this->unit_id)||!$this->people->get_scoped($person,$this->unit_id))throw new \DomainException('gd_invalid_relation');$role=(string)($input['role']??'');$status=(string)($input['status']??'active');if(!in_array($role,Constants::ACCOUNT_PERSON_ROLES,true)||!in_array($status,Constants::RELATION_STATUSES,true))throw new \DomainException('gd_invalid_value');$start=$this->valid_date($input['start_date']??'');$end=$this->valid_date($input['end_date']??'');if($start&&$end&&$end<$start)throw new \DomainException('gd_invalid_date_range');$dup=$this->db->table($this->db->prefixTable('gd_account_people'))->where('unit_id',$this->unit_id)->where('account_id',$account)->where('person_id',$person)->where('role',$role)->where('deleted',0)->where('status','active');if($id)$dup->where('id !=',$id);if($status==='active'&&$dup->countAllResults()>0)throw new \DomainException('gd_duplicate_relation');$primary=!empty($input['is_primary'])?1:0;$financial=$role==='financial_responsible'?1:(!empty($input['is_financial_responsible'])?1:0);$data=$this->stamp(['unit_id'=>$this->unit_id,'account_id'=>$account,'person_id'=>$person,'role'=>$role,'is_primary'=>$primary,'is_financial_responsible'=>$financial,'receives_notifications'=>!empty($input['receives_notifications'])?1:0,'status'=>$status,'start_date'=>$start,'end_date'=>$status==='ended'?($end?:gmdate('Y-m-d')):$end,'notes'=>DataNormalizationService::text($input['notes']??'')?:null],$id===0);$table=$this->db->prefixTable('gd_account_people');$previousPrimary=$primary&&$status==='active'?$this->db->table($table)->where('account_id',$account)->where('unit_id',$this->unit_id)->where('deleted',0)->where('status','active')->where('is_primary',1)->where('id !=',$id?:0)->get(1)->getRow():null;$now=function_exists('get_current_utc_time')?get_current_utc_time():gmdate('Y-m-d H:i:s');$this->db->transStart();if($primary&&$status==='active'){$this->db->table($table)->where('account_id',$account)->where('unit_id',$this->unit_id)->where('deleted',0)->where('id !=',$id?:0)->update(['is_primary'=>0,'updated_at'=>$now,'updated_by'=>$this->actor_id?:null]);}$save=(int)$this->model->ci_save($data,$id);$this->db->transComplete();if(!$save||$this->db->transStatus()===false)throw new \RuntimeException('save_failed');$after=$this->model->get_scoped($save,$this->unit_id);$this->audit_change($id?'update':'create','account_person',$save,$old?(array)$old:null,$after?(array)$after:null);if($previousPrimary){$this->audit_change('primary_change','account_person',$save,null,null,['previous_relation_id'=>(int)$previousPrimary->id]);}return $save; }
    public function end(int $id,string $reason):void{$row=$this->model->get_scoped($id,$this->unit_id);if(!$row)throw new \DomainException('gd_record_not_found');$reason=DataNormalizationService::text($reason);if($reason==='')throw new \DomainException('gd_delete_reason_required');$data=$this->stamp(['status'=>'ended','end_date'=>gmdate('Y-m-d'),'is_primary'=>0],false);$this->model->ci_save($data,$id);$this->audit_change('end','account_person',$id,(array)$row,(array)$this->model->get_scoped($id,$this->unit_id),['reason'=>$reason]);}
}
