<?php

declare(strict_types=1);

namespace grupo_donato_gestao\Services;

use grupo_donato_gestao\Config\Constants;

class BookingService extends CustomerDataService
{
    private $bookings;private $booking_resources;private $booking_events;private TemporalService $time;private BookingConflictService $conflicts;private BookingEventService $events;private ?array $trusted_series_context=null;
    public function __construct(int $unit_id,int $actor_id=0,?object $login_user=null)
    {parent::__construct($unit_id,$actor_id,$login_user);$this->bookings=model("grupo_donato_gestao\\Models\\Gd_bookings_model");$this->booking_resources=model("grupo_donato_gestao\\Models\\Gd_booking_resources_model");$this->booking_events=model("grupo_donato_gestao\\Models\\Gd_booking_events_model");$this->time=new TemporalService($unit_id);$this->conflicts=new BookingConflictService($unit_id,$actor_id,$login_user);$this->events=new BookingEventService($unit_id,$actor_id,$login_user);}

    public function get(int $id):?object
    {
        $row=$this->bookings->get_scoped($id,$this->unit_id);if(!$row){return null;}$row->resources=$this->booking_resources->for_booking($id,$this->unit_id);$row->events=$this->booking_events->for_booking($id,$this->unit_id);
        $row->customer_name=null;$row->contact_name=null;if($row->customer_account_id){$a=$this->db->table($this->db->prefixTable("gd_customer_accounts"))->select("display_name")->where("id",$row->customer_account_id)->where("unit_id",$this->unit_id)->where("deleted",0)->get(1)->getRow();$row->customer_name=$a->display_name??null;}if($row->contact_person_id){$p=$this->db->table($this->db->prefixTable("gd_people"))->select("full_name")->where("id",$row->contact_person_id)->where("unit_id",$this->unit_id)->where("deleted",0)->get(1)->getRow();$row->contact_name=$p->full_name??null;}return $row;
    }
    public function listPage(array $options):array{$options["unit_id"]=$this->unit_id;$from=trim((string)($options["date_from"]??""));$to=trim((string)($options["date_to"]??""));if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)){$options["date_from_utc"]=$this->time->localToUtc($from,"00:00");}if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$to)){$next=(new \DateTimeImmutable($to))->modify("+1 day")->format("Y-m-d");$options["date_to_utc"]=$this->time->localToUtc($next,"00:00");}return $this->bookings->get_details($options);}
    public function resourcesFor(int $booking_id):array{return $this->booking_resources->for_booking($booking_id,$this->unit_id);}
    public function bookableResources():array{return $this->db->table($this->db->prefixTable("gd_resources"))->select("id,code,name")->where("unit_id",$this->unit_id)->where("deleted",0)->where("is_active",1)->where("is_bookable",1)->orderBy("sort_order")->orderBy("name")->get()->getResultArray();}
    public function customerOptions(string $term="",int $limit=30):array{$q=$this->db->table($this->db->prefixTable("gd_customer_accounts"))->select("id,display_name,account_type")->where("unit_id",$this->unit_id)->where("deleted",0)->where("status","active");if(trim($term)!==""){$q->like("display_name",trim($term));}return $q->orderBy("display_name")->limit(max(1,min(50,$limit)))->get()->getResultArray();}
    public function contactOptions(int $account_id,string $term="",int $limit=50):array{$l=$this->db->prefixTable("gd_account_people");$p=$this->db->prefixTable("gd_people");$q=$this->db->table($l)->select("DISTINCT $p.id,$p.full_name",false)->join($p,"$p.id=$l.person_id AND $p.unit_id=$l.unit_id AND $p.deleted=0","inner",false)->where("$l.unit_id",$this->unit_id)->where("$l.account_id",$account_id)->where("$l.status","active")->where("$l.deleted",0);if(trim($term)!==""){$q->like("$p.full_name",trim($term));}return $q->orderBy("$p.full_name")->limit(max(1,min(100,$limit)))->get()->getResultArray();}

    public function createSeriesOccurrence(array $input,int $series_id,string $occurrence_key,string $local_date,bool $external_transaction=false,bool $locks_already_held=false):array
    {
        if($series_id<=0||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$occurrence_key)||$occurrence_key!==$local_date){throw new \DomainException("gd_invalid_booking_series_occurrence");}
        $series=$this->db->table($this->db->prefixTable("gd_booking_series"))->select("id")->where("id",$series_id)->where("unit_id",$this->unit_id)->where("deleted",0)->get(1)->getRow();if(!$series){throw new \DomainException("gd_booking_series_not_found");}
        $existing=$this->db->table($this->db->prefixTable("gd_bookings"))->select("id,booking_number,lock_version")->where("series_id",$series_id)->where("series_occurrence_key",$occurrence_key)->where("deleted",0)->get(1)->getRow();if($existing){return ["id"=>(int)$existing->id,"booking_number"=>(string)$existing->booking_number,"lock_version"=>(int)$existing->lock_version,"idempotent"=>true];}
        $this->trusted_series_context=["series_id"=>$series_id,"series_occurrence_key"=>$occurrence_key,"series_local_date"=>$local_date];
        try{$result=$this->save($input,0,true,$external_transaction,$locks_already_held);$result["idempotent"]=false;return $result;}finally{$this->trusted_series_context=null;}
    }

    public function save(array $input,int $id=0,bool $allow_confirmed=false,bool $external_transaction=false,bool $locks_already_held=false):array
    {
        $existing=$id?$this->bookings->get_scoped($id,$this->unit_id):null;if($id&&!$existing){throw new \DomainException("gd_booking_not_found");}
        if($existing&&(!in_array((string)$existing->status,Constants::BOOKING_EDITABLE_STATUSES,true)||(string)$existing->starts_at_utc<=gmdate("Y-m-d H:i:s"))){throw new \DomainException("gd_booking_not_editable");}
        $prepared=$this->prepare($input,$existing,$allow_confirmed);$old_resources=$existing?$this->booking_resources->for_booking($id,$this->unit_id):[];$lock_ids=array_merge(array_column($prepared["resources"],"resource_id"),array_map(static fn($r)=>(int)$r->resource_id,$old_resources));$locks=new BookingResourceLockService();$number=$existing?(string)$existing->booking_number:"";$in_tx=false;
        try{if(!$locks_already_held){$locks->acquire($this->unit_id,$lock_ids);}if(!$existing){$seq=new SequenceService();$seq->ensure($this->unit_id,"booking","RES-".gmdate("Y")."-",6,true);$number=$seq->next($this->unit_id,"booking");}
            if(!$external_transaction){if($this->db->transBegin()===false){throw new \RuntimeException("booking transaction");}$in_tx=true;}if($existing){$fresh=$this->bookings->get_scoped($id,$this->unit_id);if(!$fresh||(int)$fresh->lock_version!==(int)$prepared["lock_version"]){throw new \DomainException("gd_booking_edit_conflict");}$existing=$fresh;}
            $this->assertResourcesCurrent($prepared["resources"]);$this->assertAvailable($prepared["resources"]);$this->assertNoDuplicate($prepared,$id);$conflict=$this->conflicts->findConflicts($this->unit_id,$prepared["resources"],$id?:null);if($conflict["has_conflict"]){throw new \DomainException("gd_booking_conflict");}
            $booking_data=$prepared["booking"];$booking_data["booking_number"]=$number;$booking_data["unit_id"]=$this->unit_id;if(!$existing&&$this->trusted_series_context!==null){$booking_data["source_type"]="booking_series";$booking_data["source_id"]=$this->trusted_series_context["series_id"];$booking_data+=$this->trusted_series_context+["is_series_exception"=>0,"detached_from_series"=>0];}$booking_data=$this->stamp($booking_data,!$existing);
            if($existing){unset($booking_data["unit_id"],$booking_data["booking_number"]);if(!$this->bookings->optimistic_update($id,$this->unit_id,(int)$prepared["lock_version"],$booking_data)){throw new \DomainException("gd_booking_edit_conflict");}$this->db->table($this->db->prefixTable("gd_booking_resources"))->where("booking_id",$id)->where("unit_id",$this->unit_id)->where("deleted",0)->update(["deleted"=>1,"updated_at"=>gmdate("Y-m-d H:i:s"),"updated_by"=>$this->actor_id?:null]);}
            else{$id=(int)$this->bookings->ci_save($booking_data);if($id<=0){throw new \RuntimeException("booking insert");}}
            foreach($prepared["resources"] as $resource){$data=$this->stamp(["unit_id"=>$this->unit_id,"booking_id"=>$id,"resource_id"=>$resource["resource_id"],"buffer_before_minutes"=>$resource["buffer_before_minutes"],"buffer_after_minutes"=>$resource["buffer_after_minutes"],"occupancy_starts_at_utc"=>$resource["occupancy_starts_at_utc"],"occupancy_ends_at_utc"=>$resource["occupancy_ends_at_utc"],"deleted"=>0],true);$this->booking_resources->ci_save($data);}
            $event=$existing?"updated":($prepared["booking"]["status"]==="hold"?"hold_created":"created");$this->events->append($id,$event,$existing?(string)$existing->status:null,(string)$prepared["booking"]["status"],null,["booking_number"=>$number,"schedule"=>[$prepared["booking"]["starts_at_utc"],$prepared["booking"]["ends_at_utc"]],"resources"=>array_column($prepared["resources"],"resource_id")]);
            if($existing){$this->appendChangeEvents($id,$existing,$old_resources,$prepared);}
            $this->audit_change($existing?"booking_updated":"booking_created","booking",$id,$existing?(array)$existing:null,["booking_number"=>$number]+$prepared["booking"],["resources"=>$prepared["resources"],"timezone"=>$this->time->timezoneName()]);
            if(!$external_transaction){if($this->db->transCommit()===false){throw new \RuntimeException("booking commit");}$in_tx=false;}return ["id"=>$id,"booking_number"=>$number,"lock_version"=>$existing?(int)$prepared["lock_version"]+1:1];
        }catch(\Throwable $e){if($in_tx){$this->db->transRollback();}if(in_array($e->getMessage(),["gd_booking_conflict","gd_booking_duplicate","gd_booking_edit_conflict"],true)){$this->audit_change($e->getMessage()==="gd_booking_edit_conflict"?"booking_edit_conflict":"booking_conflict_rejected","booking",$id?:0,$existing?(array)$existing:null,null,["booking_number"=>$number,"reason"=>$e->getMessage()]);}throw $e;}finally{if(!$locks_already_held){$locks->release();}}
    }

    public function checkAvailability(array $input,int $exclude_booking_id=0):array
    {
        [$start,$end,$resources]=$this->prepareSchedule($input);$this->assertResourcesCurrent($resources);$physical=$this->physicalResults($resources);$conflicts=$this->conflicts->findConflicts($this->unit_id,$resources,$exclude_booking_id?:null);$available=!array_filter($physical,static fn($v)=>empty($v["available"]))&&!$conflicts["has_conflict"];return ["available"=>$available,"starts_at_utc"=>$start,"ends_at_utc"=>$end,"resources"=>$physical,"conflicts"=>$conflicts["conflicts"]];
    }

    public function revalidateStored(object $booking):void
    {
        $rows=$this->booking_resources->for_booking((int)$booking->id,$this->unit_id);if(!$rows){throw new \DomainException("gd_invalid_booking_resources");}$windows=array_map(static fn($r)=>["resource_id"=>(int)$r->resource_id,"buffer_before_minutes"=>(int)$r->buffer_before_minutes,"buffer_after_minutes"=>(int)$r->buffer_after_minutes,"occupancy_starts_at_utc"=>(string)$r->occupancy_starts_at_utc,"occupancy_ends_at_utc"=>(string)$r->occupancy_ends_at_utc],$rows);$this->assertResourcesCurrent($windows);$this->assertAvailable($windows);$conflict=$this->conflicts->findConflicts($this->unit_id,$windows,(int)$booking->id);if($conflict["has_conflict"]){throw new \DomainException("gd_booking_conflict");}
    }

    public function delete(int $id):void
    {
        $row=$this->bookings->get_scoped($id,$this->unit_id);if(!$row){throw new \DomainException("gd_booking_not_found");}if(!in_array((string)$row->status,["hold","pending_confirmation","cancelled","expired"],true)){throw new \DomainException("gd_booking_delete_not_allowed");}$this->db->table($this->db->prefixTable("gd_bookings"))->where("id",$id)->where("unit_id",$this->unit_id)->where("deleted",0)->update(["deleted"=>1,"updated_at"=>gmdate("Y-m-d H:i:s"),"updated_by"=>$this->actor_id?:null,"lock_version"=>(int)$row->lock_version+1]);$this->audit_change("booking_deleted","booking",$id,(array)$row,null,["booking_number"=>$row->booking_number]);
    }

    private function prepare(array $input,?object $existing,bool $allow_confirmed):array
    {
        $type=trim((string)($input["booking_type"]??""));if(!in_array($type,Constants::BOOKING_TYPES,true)){throw new \DomainException("gd_invalid_booking_type");}$title=DataNormalizationService::text(strip_tags((string)($input["title"]??"")));if($title===""||mb_strlen($title)>180){throw new \DomainException("gd_booking_title_required");}
        $status=$existing?(string)$existing->status:trim((string)($input["status"]??""));if(!$existing&&!in_array($status,Constants::BOOKING_INITIAL_STATUSES,true)){throw new \DomainException("gd_invalid_booking_status");}if(!$existing&&$status==="confirmed"&&!$allow_confirmed){throw new \DomainException("gd_booking_status_permission_required");}
        $customer=(int)($input["customer_account_id"]??0);$contact=(int)($input["contact_person_id"]??0);$this->assertCustomerAndContact($type,$customer,$contact);
        [$start,$end,$resources]=$this->prepareSchedule($input);$hold=null;if($status==="hold"){$raw=trim((string)($input["hold_expires_at_local"]??""));if($raw===""){throw new \DomainException("gd_hold_expiry_required");}$hold=$this->time->localStringToUtc($raw);$now=time();$expires=$this->time->parseUtc($hold)->getTimestamp();$max=$this->configuredInt("booking_hold_max_minutes",Constants::BOOKING_DEFAULT_HOLD_MINUTES,1,Constants::BOOKING_MAX_HOLD_MINUTES);if($expires<=$now||$expires-$now>$max*60){throw new \DomainException("gd_invalid_hold_expiry");}}
        $notes=trim(strip_tags((string)($input["notes"]??"")));if(mb_strlen($notes)>5000){throw new \DomainException("gd_booking_notes_too_large");}$metadata=$this->bookingMetadata($input["metadata"]??null);
        return ["booking"=>["customer_account_id"=>$customer?:null,"contact_person_id"=>$contact?:null,"booking_type"=>$type,"title"=>$title,"status"=>$status,"starts_at_utc"=>$start,"ends_at_utc"=>$end,"timezone"=>$this->time->timezoneName(),"hold_expires_at_utc"=>$hold,"source_type"=>null,"source_id"=>null,"notes"=>$notes?:null,"metadata"=>$metadata],"resources"=>$resources,"lock_version"=>(int)($input["lock_version"]??0)];
    }

    private function prepareSchedule(array $input):array
    {
        $start=$this->time->localStringToUtc((string)($input["starts_at_local"]??""));$end=$this->time->localStringToUtc((string)($input["ends_at_local"]??""));[$start,$end]=$this->time->validateRange($start,$end);$duration=$this->time->parseUtc($end)->getTimestamp()-$this->time->parseUtc($start)->getTimestamp();$max=$this->configuredInt("booking_max_duration_minutes",1440,1,Constants::BOOKING_MAX_DURATION_MINUTES);if($duration>$max*60){throw new \DomainException("gd_booking_duration_too_large");}
        $raw=$input["resources"]??[];if(!is_array($raw)||!$raw){throw new \DomainException("gd_invalid_booking_resources");}$resources=[];$seen=[];$max_buffer=$this->configuredInt("booking_max_buffer_minutes",240,0,Constants::BOOKING_MAX_BUFFER_MINUTES);
        foreach($raw as $entry){if(!is_array($entry)){continue;}$rid=(int)($entry["resource_id"]??0);if($rid<=0||isset($seen[$rid])){throw new \DomainException($rid>0?"gd_duplicate_booking_resource":"gd_invalid_booking_resources");}$seen[$rid]=true;$before=$this->strictMinutes($entry["buffer_before_minutes"]??0,$max_buffer);$after=$this->strictMinutes($entry["buffer_after_minutes"]??0,$max_buffer);$s=$this->time->parseUtc($start)->modify("-$before minutes")->format("Y-m-d H:i:s");$e=$this->time->parseUtc($end)->modify("+$after minutes")->format("Y-m-d H:i:s");$resources[]=["resource_id"=>$rid,"buffer_before_minutes"=>$before,"buffer_after_minutes"=>$after,"occupancy_starts_at_utc"=>$s,"occupancy_ends_at_utc"=>$e];}
        if(!$resources){throw new \DomainException("gd_invalid_booking_resources");}usort($resources,static fn($a,$b)=>$a["resource_id"]<=>$b["resource_id"]);return [$start,$end,$resources];
    }

    private function strictMinutes($value,int $max):int{$raw=(string)$value;if(!preg_match('/^\d+$/',$raw)){throw new \DomainException("gd_invalid_booking_buffer");}$n=(int)$raw;if($n>$max){throw new \DomainException("gd_invalid_booking_buffer");}return $n;}
    private function assertCustomerAndContact(string $type,int $customer,int $contact):void
    {
        if(in_array($type,Constants::BOOKING_COMMERCIAL_TYPES,true)&&$customer<=0){throw new \DomainException("gd_booking_customer_required");}if($contact>0&&$customer<=0){throw new \DomainException("gd_booking_contact_requires_customer");}
        if($customer>0){$a=$this->db->table($this->db->prefixTable("gd_customer_accounts"))->where("id",$customer)->where("unit_id",$this->unit_id)->where("deleted",0)->where("status","active")->get(1)->getRow();if(!$a){throw new \DomainException("gd_invalid_booking_customer");}}
        if($contact>0){$p=$this->db->table($this->db->prefixTable("gd_people"))->where("id",$contact)->where("unit_id",$this->unit_id)->where("deleted",0)->get(1)->getRow();$linked=$this->db->table($this->db->prefixTable("gd_account_people"))->where("unit_id",$this->unit_id)->where("account_id",$customer)->where("person_id",$contact)->where("status","active")->where("deleted",0)->countAllResults();if(!$p||$linked<1){throw new \DomainException("gd_invalid_booking_contact");}}
    }
    private function assertResourcesCurrent(array $resources):void{$ids=array_column($resources,"resource_id");$rows=$this->db->table($this->db->prefixTable("gd_resources"))->select("id")->where("unit_id",$this->unit_id)->whereIn("id",$ids)->where("deleted",0)->where("is_active",1)->where("is_bookable",1)->get()->getResultArray();if(count($rows)!==count(array_unique($ids))){throw new \DomainException("gd_invalid_booking_resource");}}
    private function physicalResults(array $resources):array{$groups=[];foreach($resources as $r){$key=$r["occupancy_starts_at_utc"]."|".$r["occupancy_ends_at_utc"];$groups[$key][]=(int)$r["resource_id"];$windows[$key]=[$r["occupancy_starts_at_utc"],$r["occupancy_ends_at_utc"]];}$service=new AvailabilityService($this->unit_id);$out=[];foreach($groups as $key=>$ids){[$s,$e]=$windows[$key];foreach($service->checkMany($ids,$s,$e) as $rid=>$result){$out[$rid]=$result;}}return $out;}
    private function assertAvailable(array $resources):void{$results=$this->physicalResults($resources);foreach($results as $result){if(empty($result["available"])){throw new \DomainException("gd_booking_resource_unavailable");}}}
    private function assertNoDuplicate(array $prepared,int $exclude):void
    {
        $b=$this->db->prefixTable("gd_bookings");$q=$this->db->table($b)->select("id,title,customer_account_id,status,hold_expires_at_utc")->where("unit_id",$this->unit_id)->where("deleted",0)->where("starts_at_utc",$prepared["booking"]["starts_at_utc"])->where("ends_at_utc",$prepared["booking"]["ends_at_utc"])->whereIn("status",Constants::BOOKING_BLOCKING_STATUSES);if($prepared["booking"]["customer_account_id"]===null){$q->where("customer_account_id IS NULL",null,false);}else{$q->where("customer_account_id",$prepared["booking"]["customer_account_id"]);}if($exclude){$q->where("id !=",$exclude);}$candidates=$q->get()->getResult();if(!$candidates){return;}$ids=[];foreach($candidates as $c){if($c->status==="hold"&&(string)$c->hold_expires_at_utc<=gmdate("Y-m-d H:i:s")){continue;}if(DataNormalizationService::name($c->title)===DataNormalizationService::name($prepared["booking"]["title"])){$ids[]=(int)$c->id;}}if(!$ids){return;}$br=$this->db->prefixTable("gd_booking_resources");$rows=$this->db->table($br)->select("booking_id,resource_id")->where("unit_id",$this->unit_id)->whereIn("booking_id",$ids)->where("deleted",0)->orderBy("resource_id")->get()->getResult();$by=[];foreach($rows as $r){$by[(int)$r->booking_id][]=(int)$r->resource_id;}$wanted=array_column($prepared["resources"],"resource_id");sort($wanted);foreach($by as $set){sort($set);if($set===$wanted){throw new \DomainException("gd_booking_duplicate");}}}
    private function bookingMetadata($value):?string{$json=DataNormalizationService::json($value,16000);if($json===null){return null;}$data=json_decode($json,true);$walk=function($v,$key="")use(&$walk){$lower=mb_strtolower((string)$key);foreach(["password","token","secret","authorization","cookie","price","amount","payment","charge","billing"] as $bad){if(str_contains($lower,$bad)){throw new \DomainException("gd_booking_metadata_forbidden");}}if(is_array($v)){foreach($v as $k=>$item){$walk($item,(string)$k);}}elseif(is_string($v)&&preg_match('/[<>]/',$v)){throw new \DomainException("gd_booking_metadata_forbidden");}};$walk($data);return $json;}
    private function configuredInt(string $key,int $default,int $min,int $max):int{$t=$this->db->prefixTable("gd_settings");$row=$this->db->table($t)->select("value")->where("key",$key)->where("deleted",0)->groupStart()->where("unit_id",$this->unit_id)->orWhere("unit_id IS NULL",null,false)->groupEnd()->orderBy("unit_id","DESC")->get(1)->getRow();$v=$row&&preg_match('/^\d+$/',(string)$row->value)?(int)$row->value:$default;return max($min,min($max,$v));}
    private function appendChangeEvents(int $id,object $before,array $old_resources,array $prepared):void{$after=$prepared["booking"];$old_ids=array_map(static fn($r)=>(int)$r->resource_id,$old_resources);$new_ids=array_column($prepared["resources"],"resource_id");if($before->starts_at_utc!==$after["starts_at_utc"]||$before->ends_at_utc!==$after["ends_at_utc"]){$this->events->append($id,"schedule_changed",$before->status,$before->status,null,["before"=>[$before->starts_at_utc,$before->ends_at_utc],"after"=>[$after["starts_at_utc"],$after["ends_at_utc"]]]);}if($old_ids!==$new_ids||json_encode(array_map(static fn($r)=>[(int)$r->buffer_before_minutes,(int)$r->buffer_after_minutes],$old_resources))!==json_encode(array_map(static fn($r)=>[$r["buffer_before_minutes"],$r["buffer_after_minutes"]],$prepared["resources"]))){$this->events->append($id,"resources_changed",$before->status,$before->status,null,["before"=>$old_ids,"after"=>$new_ids]);}if((int)$before->customer_account_id!==(int)$after["customer_account_id"]){$this->events->append($id,"customer_changed",$before->status,$before->status);}if((int)$before->contact_person_id!==(int)$after["contact_person_id"]){$this->events->append($id,"contact_changed",$before->status,$before->status);}}
}
