<?php

declare(strict_types=1);

namespace grupo_donato_gestao\Services;

/** Projeção read-only de regras, exceções e bloqueios para FullCalendar. */
class CalendarService extends CustomerDataService
{
    private TemporalService $time;private bool $can_view_bookings;
    public function __construct(int $unit_id,bool $can_view_bookings=false){parent::__construct($unit_id);$this->time=new TemporalService($unit_id);$this->can_view_bookings=$can_view_bookings;}
    public function timezoneName():string{return $this->time->timezoneName();}

    public function events(string $range_start,string $range_end,array $resource_ids=[],array $types=[],array $booking_statuses=[]):array
    {
        $start=$this->time->parseIsoInstant($range_start);$end=$this->time->parseIsoInstant($range_end);if($end<=$start){throw new \DomainException("gd_invalid_datetime_range");}
        if(($end->getTimestamp()-$start->getTimestamp())>$this->time->calendarMaxDays()*86400){throw new \DomainException("gd_calendar_range_too_large");}
        $start_utc=$start->format("Y-m-d H:i:s");$end_utc=$end->format("Y-m-d H:i:s");$types=array_values(array_intersect($types,["weekly_rule","open_exception","closed_exception","block","booking"]));if(!$types){$types=["weekly_rule","open_exception","closed_exception","block","booking"];}
        $p=$this->db->getPrefix();$rb=$this->db->table($p."gd_resources")->select("id,code,name,is_active,is_bookable")->where("unit_id",$this->unit_id)->where("deleted",0)->where("is_active",1)->where("is_bookable",1);
        $resource_ids=array_values(array_unique(array_filter(array_map("intval",$resource_ids),static fn($id)=>$id>0)));if($resource_ids){$rb->whereIn("id",$resource_ids);}$resources=$rb->orderBy("sort_order")->orderBy("name")->get()->getResult();$ids=array_map(static fn($r)=>(int)$r->id,$resources);if(!$ids){return [];}$names=[];foreach($resources as $r){$names[(int)$r->id]=(string)$r->code." — ".(string)$r->name;}$events=[];
        if(in_array("weekly_rule",$types,true)){$rules=$this->db->table($p."gd_resource_availability_rules")->where("unit_id",$this->unit_id)->whereIn("resource_id",$ids)->where("status","active")->where("deleted",0)->get()->getResult();$local_start=$start->setTimezone(new \DateTimeZone($this->time->timezoneName()))->modify("-1 day")->setTime(0,0);$local_end=$end->setTimezone(new \DateTimeZone($this->time->timezoneName()))->modify("+1 day")->setTime(0,0);
            for($day=$local_start;$day<=$local_end;$day=$day->modify("+1 day")){foreach($rules as $r){$date=$day->format("Y-m-d");if((int)$r->weekday!==(int)$day->format("w")||($r->valid_from&&$date<$r->valid_from)||($r->valid_until&&$date>$r->valid_until)){continue;}$end_date=(int)$r->spans_next_day?$day->modify("+1 day")->format("Y-m-d"):$date;try{$s=$this->time->localToUtc($date,$r->start_time);$e=$this->time->localToUtc($end_date,$r->end_time);}catch(\DomainException $x){continue;}if(!TemporalService::overlaps($s,$e,$start_utc,$end_utc)){continue;}$events[]=$this->event("rule-{$r->id}-$date",$names[(int)$r->resource_id],$s,$e,"weekly_rule",(int)$r->resource_id,"#198754",true);}}
        }
        if(array_intersect(["open_exception","closed_exception"],$types)){$rows=$this->db->table($p."gd_resource_availability_exceptions")->where("unit_id",$this->unit_id)->whereIn("resource_id",$ids)->where("status","active")->where("deleted",0)->where("starts_at_utc <",$end_utc)->where("ends_at_utc >",$start_utc)->get()->getResult();foreach($rows as $r){$kind=$r->exception_type==="open"?"open_exception":"closed_exception";if(!in_array($kind,$types,true)){continue;}$events[]=$this->event("exception-{$r->id}",$names[(int)$r->resource_id]." — ".$r->title,$r->starts_at_utc,$r->ends_at_utc,$kind,(int)$r->resource_id,$r->exception_type==="open"?"#20c997":"#dc3545",true);}}
        if(in_array("block",$types,true)){$rows=$this->db->table($p."gd_resource_blocks")->where("unit_id",$this->unit_id)->whereIn("resource_id",$ids)->where("status","active")->where("deleted",0)->where("starts_at_utc <",$end_utc)->where("ends_at_utc >",$start_utc)->get()->getResult();foreach($rows as $r){$events[]=$this->event("block-{$r->id}",$names[(int)$r->resource_id]." — ".$r->title,$r->starts_at_utc,$r->ends_at_utc,"block",(int)$r->resource_id,"#fd7e14",false);}}
        if(in_array("booking",$types,true)&&$this->db->tableExists($p."gd_bookings")){$allowed=\grupo_donato_gestao\Config\Constants::BOOKING_STATUSES;$booking_statuses=array_values(array_intersect($booking_statuses,$allowed));$b=$p."gd_bookings";$br=$p."gd_booking_resources";$q=$this->db->table($br)->select("$b.id,$b.booking_number,$b.title,$b.status,$b.starts_at_utc,$b.ends_at_utc,$b.hold_expires_at_utc,$b.series_id,$b.detached_from_series,$br.resource_id,$br.occupancy_starts_at_utc,$br.occupancy_ends_at_utc,$br.buffer_before_minutes,$br.buffer_after_minutes")->join($b,"$b.id=$br.booking_id AND $b.unit_id=$br.unit_id","inner",false)->where("$br.unit_id",$this->unit_id)->whereIn("$br.resource_id",$ids)->where("$br.deleted",0)->where("$b.deleted",0)->where("$b.starts_at_utc <",$end_utc)->where("$b.ends_at_utc >",$start_utc)->groupStart()->where("$b.status !=","hold")->orWhere("$b.hold_expires_at_utc >",gmdate("Y-m-d H:i:s"))->groupEnd();if($booking_statuses){$q->whereIn("$b.status",$booking_statuses);} $colors=["hold"=>"#ffc107","pending_confirmation"=>"#6f42c1","confirmed"=>"#0d6efd","in_progress"=>"#20c997","completed"=>"#198754","cancelled"=>"#6c757d","expired"=>"#adb5bd","no_show"=>"#dc3545"];
            foreach($q->orderBy("$b.starts_at_utc","ASC")->get()->getResult() as $r){$is_series=(int)$r->series_id>0&&!(int)$r->detached_from_series;$title=$this->can_view_bookings?($is_series?"↻ ":"").$r->booking_number." — ".$r->title:(function_exists("app_lang")?app_lang("gd_calendar_busy"):"Ocupado");$events[]=["id"=>"booking-{$r->id}-{$r->resource_id}","title"=>$title,"start"=>$this->time->utcToIsoLocal($r->starts_at_utc),"end"=>$this->time->utcToIsoLocal($r->ends_at_utc),"backgroundColor"=>$colors[$r->status]??"#0d6efd","borderColor"=>$colors[$r->status]??"#0d6efd","classNames"=>$is_series?["gd-series-occurrence"]:[],"extendedProps"=>["event_type"=>"booking","booking_id"=>(int)$r->id,"booking_number"=>$this->can_view_bookings?$r->booking_number:null,"resource_id"=>(int)$r->resource_id,"status"=>$r->status,"is_series"=>$is_series,"series_id"=>$this->can_view_bookings&&$is_series?(int)$r->series_id:null,"occupancy_start"=>$this->time->utcToIsoLocal($r->occupancy_starts_at_utc),"occupancy_end"=>$this->time->utcToIsoLocal($r->occupancy_ends_at_utc),"buffer_before_minutes"=>(int)$r->buffer_before_minutes,"buffer_after_minutes"=>(int)$r->buffer_after_minutes]];}}
        // School/personal uses the canonical booking projection. Enrich it with
        // its source instead of creating duplicate calendar events.
        if($this->db->tableExists($p."gd_classes")){foreach($events as &$event){if(($event["extendedProps"]["event_type"]??"")!=="booking")continue;$booking_id=(int)($event["extendedProps"]["booking_id"]??0);$series_id=(int)($event["extendedProps"]["series_id"]??0);$q=$this->db->table($p."gd_classes")->select("id,name")->where("unit_id",$this->unit_id)->where("deleted",0)->groupStart()->where("booking_id",$booking_id);if($series_id)$q->orWhere("booking_series_id",$series_id);$school=$q->groupEnd()->get(1)->getRow();if($school){$event["extendedProps"]["source_type"]="school_class";$event["extendedProps"]["school_class_id"]=(int)$school->id;if($this->can_view_bookings)$event["title"]=(string)$school->name;}}unset($event);}
        return $events;
    }
    public function resources():array{$t=$this->db->prefixTable("gd_resources");return $this->db->table($t)->select("id,code,name")->where("unit_id",$this->unit_id)->where("deleted",0)->where("is_active",1)->where("is_bookable",1)->orderBy("sort_order")->orderBy("name")->get()->getResultArray();}
    private function event(string $id,string $title,string $start,string $end,string $type,int $resource_id,string $color,bool $background):array{return ["id"=>$id,"title"=>$title,"start"=>$this->time->utcToIsoLocal($start),"end"=>$this->time->utcToIsoLocal($end),"display"=>$background?"background":"auto","backgroundColor"=>$color,"borderColor"=>$color,"extendedProps"=>["event_type"=>$type,"resource_id"=>$resource_id]];}
}
