<?php

declare(strict_types=1);

namespace grupo_donato_gestao\Services;

use grupo_donato_gestao\Config\Constants;

class ContactMethodService extends CustomerDataService
{
    private $model;private $people;
    public function __construct(int $unit_id,int $actor_id=0,?object $login_user=null){parent::__construct($unit_id,$actor_id,$login_user);$this->model=model('grupo_donato_gestao\\Models\\Gd_contact_methods_model');$this->people=model('grupo_donato_gestao\\Models\\Gd_people_model');}
    public function save(array $input,int $id=0):int{$old=$id?$this->model->get_scoped($id,$this->unit_id):null;if($id&&!$old)throw new \DomainException('gd_record_not_found');$person=(int)($input['person_id']??0);if(!$this->people->get_scoped($person,$this->unit_id))throw new \DomainException('gd_invalid_person');$type=(string)($input['contact_type']??'');$status=(string)($input['status']??'active');if(!in_array($type,Constants::CONTACT_TYPES,true)||!in_array($status,Constants::CONTACT_STATUSES,true))throw new \DomainException('gd_invalid_value');$value=DataNormalizationService::text($input['value']??'');if($value==='')throw new \DomainException('gd_contact_required');if($type==='email'&&!filter_var($value,FILTER_VALIDATE_EMAIL))throw new \DomainException('gd_invalid_email');$primary=!empty($input['is_primary'])?1:0;$data=$this->stamp(['unit_id'=>$this->unit_id,'person_id'=>$person,'contact_type'=>$type,'label'=>DataNormalizationService::text($input['label']??'')?:null,'value'=>$value,'normalized_value'=>DataNormalizationService::contact($value,$type),'is_primary'=>$primary,'receives_notifications'=>!empty($input['receives_notifications'])?1:0,'is_verified'=>0,'status'=>$status],$id===0);$table=$this->db->prefixTable('gd_contact_methods');$previousPrimary=$primary&&$status==='active'?$this->db->table($table)->where('person_id',$person)->where('contact_type',$type)->where('unit_id',$this->unit_id)->where('deleted',0)->where('status','active')->where('is_primary',1)->where('id !=',$id?:0)->get(1)->getRow():null;$now=function_exists('get_current_utc_time')?get_current_utc_time():gmdate('Y-m-d H:i:s');$this->db->transStart();if($primary&&$status==='active'){$this->db->table($table)->where('person_id',$person)->where('contact_type',$type)->where('unit_id',$this->unit_id)->where('deleted',0)->where('id !=',$id?:0)->update(['is_primary'=>0,'updated_at'=>$now,'updated_by'=>$this->actor_id?:null]);}$save=(int)$this->model->ci_save($data,$id);$this->db->transComplete();if(!$save||$this->db->transStatus()===false)throw new \RuntimeException('save_failed');$this->audit_change($id?'update':'create','contact_method',$save,$old?(array)$old:null,(array)$this->model->get_scoped($save,$this->unit_id));if($previousPrimary){$this->audit_change('primary_change','contact_method',$save,null,null,['previous_contact_id'=>(int)$previousPrimary->id]);}return $save;}
    public function delete(int $id,string $reason):void{$row=$this->model->get_scoped($id,$this->unit_id);if(!$row)throw new \DomainException('gd_record_not_found');if(DataNormalizationService::text($reason)==='')throw new \DomainException('gd_delete_reason_required');$this->model->delete($id);$this->audit_change('delete','contact_method',$id,(array)$row,null,['reason'=>$reason]);}
}
