<?php
declare(strict_types=1);
namespace grupo_donato_gestao\Services;
use grupo_donato_gestao\Config\Constants;

/** Basic finance ledger: receivables, allocations, reversals, expenses and cash. */
class FinanceService extends CatalogDataService
{
    private $receivables;private $items;private $payments;private $allocations;private $expenses;private $cash;private ?object $login_user;
    public function __construct(int $unit_id,int $actor_id=0,?object $login_user=null){parent::__construct($unit_id,$actor_id,$login_user);$this->receivables=model('grupo_donato_gestao\\Models\\Gd_receivables_model');$this->items=model('grupo_donato_gestao\\Models\\Gd_receivable_items_model');$this->payments=model('grupo_donato_gestao\\Models\\Gd_payments_model');$this->allocations=model('grupo_donato_gestao\\Models\\Gd_payment_allocations_model');$this->expenses=model('grupo_donato_gestao\\Models\\Gd_expenses_model');$this->cash=model('grupo_donato_gestao\\Models\\Gd_cash_movements_model');$this->login_user=$login_user;}

    public function accounts():array{return $this->db->table($this->db->prefixTable('gd_financial_accounts'))->select('id,name,account_type')->where('unit_id',$this->unit_id)->where('status','active')->where('deleted',0)->orderBy('name')->get()->getResultArray();}
    public function saveAccount(array $in,int $id=0):array{$model=model('grupo_donato_gestao\\Models\\Gd_financial_accounts_model');$old=$id?$model->get_scoped($id,$this->unit_id):null;if($id&&!$old)throw new \DomainException('gd_record_not_found');$name=DataNormalizationService::text($in['name']??'');$code=strtoupper(preg_replace('/[^A-Z0-9_-]/','',DataNormalizationService::text($in['code']??'')));$type=(string)($in['account_type']??'');$status=(string)($in['status']??'active');if($name===''||$code===''||!in_array($type,Constants::FINANCIAL_ACCOUNT_TYPES,true)||!in_array($status,Constants::FINANCIAL_ACCOUNT_STATUSES,true))throw new \DomainException('gd_finance_invalid_account');$data=$this->stamp(['unit_id'=>$this->unit_id,'code'=>$code,'name'=>$name,'account_type'=>$type,'status'=>$status,'notes'=>DataNormalizationService::text($in['notes']??'')?:null],!$old);$saved=(int)$model->ci_save($data,$id);$this->audit_change($id?'update':'create','financial_account',$saved,$old?(array)$old:null,(array)$model->get_scoped($saved,$this->unit_id));return ['id'=>$saved];}
    public function createReceivable(array $in):array
    {
        $source=(string)($in['source_type']??'manual');if(!in_array($source,Constants::RECEIVABLE_SOURCE_TYPES,true))throw new \DomainException('gd_finance_invalid_source');$sourceId=(int)($in['source_id']??0);$reference=$this->reference($in['reference_month']??'');$account=(int)($in['customer_account_id']??0);$description=DataNormalizationService::text($in['description']??'');$issue=$this->valid_date($in['issue_date']??gmdate('Y-m-d'));$due=$this->valid_date($in['due_date']??'');$amount=DataNormalizationService::decimal($in['original_amount']??'',2);if(DataNormalizationService::decimalCompare($amount,'0.00')<=0||!$due||$due<$issue||$description==='')throw new \DomainException('gd_finance_invalid_receivable');
        [$account,$sourceId]=$this->resolveSource($source,$sourceId,$account);$this->scoped('gd_customer_accounts',$account);$area=$this->assert_area((int)($in['business_area_id']??0));$center=$this->assert_cost_center((int)($in['cost_center_id']??0),$area);
        if($source!=='manual'&&$sourceId>0){$dup=$this->db->table($this->db->prefixTable('gd_receivables'))->where('unit_id',$this->unit_id)->where('source_type',$source)->where('source_id',$sourceId)->where('reference_month',$reference)->where('deleted',0)->get(1)->getRow();if($dup)return ['created'=>false,'duplicate'=>true,'id'=>(int)$dup->id];}
        $product=(int)($in['product_id']??0);if($product)$this->scoped('gd_products',$product);$qty=DataNormalizationService::decimal($in['quantity']??'1',3);$unitAmount=DataNormalizationService::decimal($in['unit_amount']??$amount,2);$total=$this->multiply($qty,$unitAmount);if(DataNormalizationService::decimalCompare($total,$amount)!==0)throw new \DomainException('gd_finance_item_total_mismatch');
        $seq=new SequenceService();$seq->ensure($this->unit_id,'receivable','REC-'.gmdate('Y').'-',6,true);$number=$seq->next($this->unit_id,'receivable');$this->db->transBegin();try{$data=$this->stamp(['unit_id'=>$this->unit_id,'receivable_number'=>$number,'customer_account_id'=>$account,'source_type'=>$source,'source_id'=>$sourceId?:null,'reference_month'=>$reference,'description'=>$description,'issue_date'=>$issue,'due_date'=>$due,'original_amount'=>$amount,'paid_amount'=>'0.00','balance_amount'=>$amount,'status'=>$due<gmdate('Y-m-d')?'overdue':'open','business_area_id'=>$area,'cost_center_id'=>$center,'notes'=>DataNormalizationService::text($in['notes']??'')?:null,'lock_version'=>1],true);$id=(int)$this->receivables->ci_save($data,0);$item=$this->stamp(['unit_id'=>$this->unit_id,'receivable_id'=>$id,'description'=>DataNormalizationService::text($in['item_description']??$description),'product_id'=>$product?:null,'quantity'=>$qty,'unit_amount'=>$unitAmount,'total_amount'=>$total],true);$this->items->ci_save($item,0);$this->audit_change('create','receivable',$id,null,$data,['source_type'=>$source,'source_id'=>$sourceId]);if($this->db->transCommit()===false)throw new \RuntimeException('save_failed');return ['created'=>true,'id'=>$id,'receivable_number'=>$number];}catch(\Throwable $e){$this->db->transRollback();if(str_contains($e->getMessage(),'uniq_receivable_source'))return ['created'=>false,'duplicate'=>true];throw $e;}
    }
    public function cancelReceivable(int $id,string $reason):void{$r=$this->receivables->get_scoped($id,$this->unit_id);if(!$r)throw new \DomainException('gd_record_not_found');if((string)$r->status==='paid'||DataNormalizationService::decimalCompare((string)$r->paid_amount,'0.00')>0)throw new \DomainException('gd_finance_paid_cannot_cancel');$reason=DataNormalizationService::text($reason);if($reason==='')throw new \DomainException('gd_reason_required');$before=(array)$r;$data=$this->stamp(['status'=>'cancelled','notes'=>trim((string)$r->notes."\nCancelamento: ".$reason),'lock_version'=>(int)$r->lock_version+1],false);$this->receivables->ci_save($data,$id);$this->audit_change('cancel','receivable',$id,$before,(array)$this->receivables->get_scoped($id,$this->unit_id),['reason'=>$reason]);}
    public function getReceivable(int $id):?object{$r=$this->receivables->get_scoped($id,$this->unit_id);if(!$r)return null;$r->items=$this->items->for_receivable($id,$this->unit_id);$r->allocations=$this->db->query("SELECT a.*,p.payment_number,p.payment_date,p.payment_method,p.status payment_status FROM `{$this->db->prefixTable('gd_payment_allocations')}` a JOIN `{$this->db->prefixTable('gd_payments')}` p ON p.id=a.payment_id AND p.unit_id=a.unit_id AND p.deleted=0 WHERE a.unit_id=? AND a.receivable_id=? ORDER BY a.id",[$this->unit_id,$id])->getResult();return $r;}
    public function receivablesPage(array $o):array
    {
        $t=$this->db->prefixTable('gd_receivables');$a=$this->db->prefixTable('gd_customer_accounts');$base=function()use($o,$t,$a){$q=$this->db->table($t)->join($a,"$a.id=$t.customer_account_id AND $a.unit_id=$t.unit_id AND $a.deleted=0",'inner',false)->where("$t.unit_id",$this->unit_id)->where("$t.deleted",0);foreach(['status','source_type','source_id','customer_account_id','business_area_id','cost_center_id'] as $f)if(($v=$o[$f]??'')!=='')$q->where("$t.$f",$v);if($v=$o['date_from']??'')$q->where("$t.due_date >=",$v);if($v=$o['date_to']??'')$q->where("$t.due_date <=",$v);if($v=trim((string)($o['search_by']??'')))$q->groupStart()->like("$t.receivable_number",$v)->orLike("$t.description",$v)->orLike("$a.display_name",$v)->groupEnd();return $q;};$total=$this->db->table($t)->where('unit_id',$this->unit_id)->where('deleted',0)->countAllResults();$filtered=$base()->countAllResults(false);$rows=$base()->select("$t.*,$a.display_name customer_name,CASE WHEN $t.status IN ('open','partial') AND $t.due_date<CURDATE() THEN 'overdue' ELSE $t.status END display_status",false)->orderBy("$t.due_date",'DESC')->limit(max(1,min(100,(int)($o['limit']??25))),max(0,(int)($o['skip']??0)))->get()->getResult();return ['data'=>$rows,'recordsTotal'=>$total,'recordsFiltered'=>$filtered];
    }
    public function registerPayment(array $in):array
    {
        $allocInput=(array)($in['allocations']??[]);$alloc=[];foreach($allocInput as $rid=>$amount){$rid=(int)$rid;if(is_array($amount))$amount=$amount['amount']??'';$value=DataNormalizationService::decimal($amount,2);if($rid>0&&DataNormalizationService::decimalCompare($value,'0.00')>0)$alloc[$rid]=$value;}if(!$alloc)throw new \DomainException('gd_finance_allocation_required');ksort($alloc);$amount=DataNormalizationService::decimal($in['amount']??'',2);$sum='0.00';foreach($alloc as $v)$sum=$this->add($sum,$v);if(DataNormalizationService::decimalCompare($amount,'0.00')<=0||DataNormalizationService::decimalCompare($sum,$amount)!==0)throw new \DomainException('gd_finance_allocation_total');$method=(string)($in['payment_method']??'');if(!in_array($method,Constants::PAYMENT_METHODS,true))throw new \DomainException('gd_invalid_value');$account=(int)($in['financial_account_id']??0);$this->activeAccount($account);$date=$this->valid_date($in['payment_date']??gmdate('Y-m-d'));
        $locks=[];$this->db->transBegin();try{foreach(array_keys($alloc) as $rid){$lock="gd:receivable:{$this->unit_id}:$rid";if((int)$this->db->query('SELECT GET_LOCK(?,10) acquired',[$lock])->getRow()->acquired!==1)throw new \RuntimeException('gd_lock_timeout');$locks[]=$lock;$r=$this->db->query("SELECT * FROM `{$this->db->prefixTable('gd_receivables')}` WHERE id=? AND unit_id=? AND deleted=0 FOR UPDATE",[$rid,$this->unit_id])->getRow();if(!$r||in_array($r->status,['paid','cancelled'],true))throw new \DomainException('gd_finance_receivable_unavailable');if(DataNormalizationService::decimalCompare($alloc[$rid],(string)$r->balance_amount)>0)throw new \DomainException('gd_finance_overallocation');}
            $seq=new SequenceService();$seq->ensure($this->unit_id,'payment','PAG-'.gmdate('Y').'-',6,true);$number=$seq->next($this->unit_id,'payment');$data=$this->stamp(['unit_id'=>$this->unit_id,'payment_number'=>$number,'financial_account_id'=>$account,'payment_date'=>$date,'amount'=>$amount,'payment_method'=>$method,'external_reference'=>DataNormalizationService::text($in['external_reference']??'')?:null,'notes'=>DataNormalizationService::text($in['notes']??'')?:null,'status'=>'confirmed'],true);$pid=(int)$this->payments->ci_save($data,0);foreach($alloc as $rid=>$value){$ad=$this->stamp(['unit_id'=>$this->unit_id,'payment_id'=>$pid,'receivable_id'=>$rid,'allocated_amount'=>$value,'status'=>'active'],true);$this->allocations->ci_save($ad,0);$this->recalculate($rid);} $this->movement($account,$date,'in','payment',$pid,'Pagamento '.$number,$amount,null);$this->audit_change('confirm','payment',$pid,null,$data,['allocations'=>$alloc]);if($this->db->transCommit()===false)throw new \RuntimeException('save_failed');return ['id'=>$pid,'payment_number'=>$number];}catch(\Throwable $e){$this->db->transRollback();throw $e;}finally{foreach(array_reverse($locks) as $lock)$this->db->query('SELECT RELEASE_LOCK(?)',[$lock]);}
    }
    public function reversePayment(int $id,string $reason):void
    {
        $p=$this->payments->get_scoped($id,$this->unit_id);if(!$p)throw new \DomainException('gd_record_not_found');if($p->status!=='confirmed')throw new \DomainException('gd_finance_payment_reversed');$reason=DataNormalizationService::text($reason);if($reason==='')throw new \DomainException('gd_reason_required');$rows=$this->allocations->for_payment($id,$this->unit_id);$this->db->transBegin();try{$paymentData=$this->stamp(['status'=>'reversed','reversed_at'=>gmdate('Y-m-d H:i:s'),'reversed_by'=>$this->actor_id?:null,'reversal_reason'=>$reason],false);$this->payments->ci_save($paymentData,$id);foreach($rows as $a){if($a->status!=='active')continue;$d=$this->stamp(['status'=>'reversed'],false);$this->allocations->ci_save($d,(int)$a->id);$this->recalculate((int)$a->receivable_id);}$original=$this->db->table($this->db->prefixTable('gd_cash_movements'))->where('unit_id',$this->unit_id)->where('source_type','payment')->where('source_id',$id)->get(1)->getRow();$this->movement((int)$p->financial_account_id,gmdate('Y-m-d'),'out','payment_reversal',$id,'Estorno '.$p->payment_number,(string)$p->amount,(int)($original->id??0));$this->audit_change('reverse','payment',$id,(array)$p,(array)$this->payments->get_scoped($id,$this->unit_id),['reason'=>$reason]);if($this->db->transCommit()===false)throw new \RuntimeException('save_failed');}catch(\Throwable $e){$this->db->transRollback();throw $e;}
    }
    public function paymentsPage(array $o):array{$p=$this->db->prefixTable('gd_payments');$a=$this->db->prefixTable('gd_financial_accounts');$q=$this->db->table($p)->select("$p.*,$a.name account_name",false)->join($a,"$a.id=$p.financial_account_id AND $a.unit_id=$p.unit_id",'inner',false)->where("$p.unit_id",$this->unit_id)->where("$p.deleted",0);if($v=$o['date_from']??'')$q->where("$p.payment_date >=",$v);if($v=$o['date_to']??'')$q->where("$p.payment_date <=",$v);$total=$this->db->table($p)->where('unit_id',$this->unit_id)->where('deleted',0)->countAllResults();$rows=$q->orderBy("$p.payment_date",'DESC')->limit(max(1,min(100,(int)($o['limit']??25))),max(0,(int)($o['skip']??0)))->get()->getResult();return ['data'=>$rows,'recordsTotal'=>$total,'recordsFiltered'=>$total];}
    public function getPayment(int $id):?object{$p=$this->payments->get_scoped($id,$this->unit_id);if(!$p)return null;$p->allocations=$this->db->query("SELECT a.*,r.receivable_number,r.description FROM `{$this->db->prefixTable('gd_payment_allocations')}` a JOIN `{$this->db->prefixTable('gd_receivables')}` r ON r.id=a.receivable_id AND r.unit_id=a.unit_id WHERE a.unit_id=? AND a.payment_id=?",[$this->unit_id,$id])->getResult();return $p;}
    public function saveExpense(array $in,int $id=0):array
    {
        $old=$id?$this->expenses->get_scoped($id,$this->unit_id):null;if($id&&!$old)throw new \DomainException('gd_record_not_found');$description=DataNormalizationService::text($in['description']??'');$amount=DataNormalizationService::decimal($in['amount']??'',2);$status=(string)($in['status']??'pending');if($description===''||DataNormalizationService::decimalCompare($amount,'0.00')<=0||!in_array($status,Constants::EXPENSE_STATUSES,true))throw new \DomainException('gd_finance_invalid_expense');$date=$this->valid_date($in['expense_date']??gmdate('Y-m-d'));$due=$this->valid_date($in['due_date']??'');$paid=$this->valid_date($in['paid_date']??'');$account=(int)($in['financial_account_id']??0);$method=trim((string)($in['payment_method']??''));if($status==='paid'){if(!$paid)$paid=$date;$this->activeAccount($account);if(!in_array($method,Constants::PAYMENT_METHODS,true))throw new \DomainException('gd_invalid_value');}elseif($old&&$old->status==='paid')throw new \DomainException('gd_finance_paid_expense_immutable');$area=$this->assert_area((int)($in['business_area_id']??0));$center=$this->assert_cost_center((int)($in['cost_center_id']??0),$area);$number=$old->expense_number??'';if(!$number){$seq=new SequenceService();$seq->ensure($this->unit_id,'expense','DES-'.gmdate('Y').'-',6,true);$number=$seq->next($this->unit_id,'expense');}$this->db->transBegin();try{$data=$this->stamp(['unit_id'=>$this->unit_id,'expense_number'=>$number,'description'=>$description,'payee'=>DataNormalizationService::text($in['payee']??'')?:null,'expense_date'=>$date,'due_date'=>$due,'paid_date'=>$paid,'amount'=>$amount,'status'=>$status,'financial_account_id'=>$account?:null,'business_area_id'=>$area,'cost_center_id'=>$center,'payment_method'=>$method?:null,'notes'=>DataNormalizationService::text($in['notes']??'')?:null,'lock_version'=>(int)($old->lock_version??0)+1],!$old);$eid=(int)$this->expenses->ci_save($data,$id);if($status==='paid'&&(!$old||$old->status!=='paid'))$this->movement($account,$paid,'out','expense',$eid,'Despesa '.$number,$amount,null);$this->audit_change($id?'update':'create','expense',$eid,$old?(array)$old:null,(array)$this->expenses->get_scoped($eid,$this->unit_id));if($this->db->transCommit()===false)throw new \RuntimeException('save_failed');return ['id'=>$eid,'expense_number'=>$number];}catch(\Throwable $e){$this->db->transRollback();throw $e;}
    }
    /** Movimento de caixa manual (ex.: importação assistida sem vínculo seguro a cobrança). Aditivo à Fase 5. */
    public function createCashMovement(array $in):array
    {
        $account=(int)($in['financial_account_id']??0);$this->activeAccount($account);$type=(string)($in['movement_type']??'');if(!in_array($type,['in','out'],true))throw new \DomainException('gd_invalid_value');$date=$this->valid_date($in['movement_date']??gmdate('Y-m-d'));$amount=DataNormalizationService::decimal($in['amount']??'',2);$description=DataNormalizationService::text($in['description']??'');if(DataNormalizationService::decimalCompare($amount,'0.00')<=0||$description==='')throw new \DomainException('gd_finance_invalid_cash_movement');$source=(string)($in['source_type']??'import');$sourceId=(int)($in['source_id']??0);if($sourceId<=0)throw new \DomainException('gd_finance_invalid_cash_movement');$this->db->transBegin();try{$id=$this->movement($account,$date,$type,$source,$sourceId,$description,$amount,null);$this->audit_change('create','cash_movement',$id,null,['movement_type'=>$type,'amount'=>$amount,'source_type'=>$source,'source_id'=>$sourceId]);if($this->db->transCommit()===false)throw new \RuntimeException('save_failed');return ['id'=>$id];}catch(\Throwable $e){$this->db->transRollback();if(str_contains($e->getMessage(),'uniq_cash_source'))throw new \DomainException('gd_import_duplicate_movement');throw $e;}
    }
    public function expensesPage(array $o):array{$t=$this->db->prefixTable('gd_expenses');$a=$this->db->prefixTable('gd_financial_accounts');$q=$this->db->table($t)->select("$t.*,$a.name account_name",false)->join($a,"$a.id=$t.financial_account_id AND $a.unit_id=$t.unit_id",'left',false)->where("$t.unit_id",$this->unit_id)->where("$t.deleted",0);if($v=$o['status']??'')$q->where("$t.status",$v);$total=$this->db->table($t)->where('unit_id',$this->unit_id)->where('deleted',0)->countAllResults();$rows=$q->orderBy("$t.expense_date",'DESC')->limit(max(1,min(100,(int)($o['limit']??25))),max(0,(int)($o['skip']??0)))->get()->getResult();return ['data'=>$rows,'recordsTotal'=>$total,'recordsFiltered'=>$total];}
    public function cashPage(array $o):array{$t=$this->db->prefixTable('gd_cash_movements');$a=$this->db->prefixTable('gd_financial_accounts');$q=$this->db->table($t)->select("$t.*,$a.name account_name",false)->join($a,"$a.id=$t.financial_account_id AND $a.unit_id=$t.unit_id",'inner',false)->where("$t.unit_id",$this->unit_id);if($v=$o['financial_account_id']??'')$q->where("$t.financial_account_id",$v);if($v=$o['date_from']??'')$q->where("$t.movement_date >=",$v);if($v=$o['date_to']??'')$q->where("$t.movement_date <=",$v);$rows=$q->orderBy("$t.movement_date",'ASC')->orderBy("$t.id",'ASC')->get()->getResult();$balance='0.00';foreach($rows as $r){$balance=$r->movement_type==='in'?$this->add($balance,(string)$r->amount):$this->sub($balance,(string)$r->amount);$r->running_balance=$balance;}return $rows;}
    public function dashboard(string $from='',string $to=''):array{$from=$from?:gmdate('Y-m-01');$to=$to?:gmdate('Y-m-t');$r=$this->db->prefixTable('gd_receivables');$p=$this->db->prefixTable('gd_payments');$e=$this->db->prefixTable('gd_expenses');$sum=fn($sql,$params)=>DataNormalizationService::decimal((string)($this->db->query($sql,$params)->getRow()->total??'0'),2);$open=$sum("SELECT COALESCE(SUM(balance_amount),0) total FROM `$r` WHERE unit_id=? AND deleted=0 AND status IN ('open','partial','overdue')",[$this->unit_id]);$overdue=$sum("SELECT COALESCE(SUM(balance_amount),0) total FROM `$r` WHERE unit_id=? AND deleted=0 AND status IN ('open','partial','overdue') AND due_date<CURDATE()",[$this->unit_id]);$received=$sum("SELECT COALESCE(SUM(amount),0) total FROM `$p` WHERE unit_id=? AND deleted=0 AND status='confirmed' AND payment_date BETWEEN ? AND ?",[$this->unit_id,$from,$to]);$expenses=$sum("SELECT COALESCE(SUM(amount),0) total FROM `$e` WHERE unit_id=? AND deleted=0 AND status='paid' AND paid_date BETWEEN ? AND ?",[$this->unit_id,$from,$to]);$debtors=(int)$this->db->query("SELECT COUNT(DISTINCT customer_account_id) c FROM `$r` WHERE unit_id=? AND deleted=0 AND status IN ('open','partial','overdue') AND due_date<CURDATE()",[$this->unit_id])->getRow()->c;return ['open'=>$open,'overdue'=>$overdue,'received'=>$received,'expenses'=>$expenses,'balance'=>$this->sub($received,$expenses),'debtors'=>$debtors,'upcoming'=>$this->db->table($r)->where('unit_id',$this->unit_id)->whereIn('status',['open','partial'])->where('deleted',0)->where('due_date >=',gmdate('Y-m-d'))->orderBy('due_date')->limit(5)->get()->getResult(),'movements'=>array_slice(array_reverse($this->cashPage(['date_from'=>$from,'date_to'=>$to])),0,8)];}
    public function summary(array $filter):array{$r=$this->db->prefixTable('gd_receivables');$q=$this->db->table($r)->where('unit_id',$this->unit_id)->where('deleted',0);foreach($filter as $k=>$v)$q->where($k,$v);$rows=$q->orderBy('due_date','DESC')->get()->getResult();$open='0.00';$overdue='0.00';foreach($rows as $x)if(!in_array($x->status,['paid','cancelled'],true)){$open=$this->add($open,(string)$x->balance_amount);if($x->due_date<gmdate('Y-m-d'))$overdue=$this->add($overdue,(string)$x->balance_amount);}$ids=array_map(fn($x)=>(int)$x->id,$rows);$last=null;if($ids)$last=$this->db->table($this->db->prefixTable('gd_payment_allocations').' a')->select('p.payment_date,p.amount,p.payment_number')->join($this->db->prefixTable('gd_payments').' p','p.id=a.payment_id AND p.status=\'confirmed\'','inner',false)->whereIn('a.receivable_id',$ids)->where('a.unit_id',$this->unit_id)->orderBy('p.payment_date','DESC')->get(1)->getRow();return ['open'=>$open,'overdue'=>$overdue,'last_payment'=>$last,'receivables'=>$rows];}

    /**
     * Saldos agregados por origem em UMA consulta (elimina N+1 na lista de
     * mensalistas). Usa o prefixo (unit_id, source_type, source_id) do índice
     * uniq_receivable_source. Retorna mapa source_id => ['balance','overdue',
     * 'partial'(bool),'open_ids'(int[])] apenas para cobranças abertas/vencidas.
     * @param array<int> $ids
     * @return array<int,array<string,mixed>>
     */
    public function balancesBySource(string $source_type,array $ids):array
    {
        $ids=array_values(array_unique(array_filter(array_map('intval',$ids),static fn($i)=>$i>0)));if(!$ids)return [];
        $t=$this->db->prefixTable('gd_receivables');$ph=implode(',',array_fill(0,count($ids),'?'));
        $rows=$this->db->query("SELECT source_id, COALESCE(SUM(balance_amount),0) bal, COALESCE(SUM(CASE WHEN due_date<CURDATE() THEN balance_amount ELSE 0 END),0) overdue, SUM(CASE WHEN paid_amount>0 THEN 1 ELSE 0 END) partial_count, GROUP_CONCAT(id ORDER BY due_date ASC) open_ids FROM `$t` WHERE unit_id=? AND source_type=? AND source_id IN ($ph) AND deleted=0 AND status IN ('open','partial','overdue') GROUP BY source_id",array_merge([$this->unit_id,$source_type],$ids))->getResult();
        $map=[];foreach($rows as $r){$open_ids=array_values(array_filter(array_map('intval',explode(',',(string)$r->open_ids))));$map[(int)$r->source_id]=['balance'=>DataNormalizationService::decimal((string)$r->bal,2),'overdue'=>DataNormalizationService::decimal((string)$r->overdue,2),'partial'=>((int)$r->partial_count)>0,'open_ids'=>$open_ids];}
        return $map;
    }

    private function resolveSource(string $source,int $id,int $account):array{if($source==='enrollment'){$e=$this->scoped('gd_enrollments',$id);$sp=$this->scoped('gd_school_profiles',(int)$e->school_profile_id);return [(int)$sp->family_account_id,$id];}if($source==='court_rental'){$r=$this->scoped('gd_court_rentals',$id);return [(int)$r->customer_account_id,$id];}if($account<=0)throw new \DomainException('gd_finance_customer_required');return [$account,$id?:0];}
    private function recalculate(int $id):void{$r=$this->receivables->get_scoped($id,$this->unit_id);if(!$r)throw new \DomainException('gd_record_not_found');$paid=DataNormalizationService::decimal((string)($this->db->query("SELECT COALESCE(SUM(allocated_amount),0) total FROM `{$this->db->prefixTable('gd_payment_allocations')}` WHERE unit_id=? AND receivable_id=? AND status='active'",[$this->unit_id,$id])->getRow()->total??'0'),2);$balance=$this->sub((string)$r->original_amount,$paid);$status=DataNormalizationService::decimalCompare($balance,'0.00')===0?'paid':(DataNormalizationService::decimalCompare($paid,'0.00')>0?'partial':($r->due_date<gmdate('Y-m-d')?'overdue':'open'));$d=$this->stamp(['paid_amount'=>$paid,'balance_amount'=>$balance,'status'=>$status,'lock_version'=>(int)$r->lock_version+1],false);$this->receivables->ci_save($d,$id);}
    private function movement(int $account,string $date,string $type,string $source,int $sourceId,string $description,string $amount,?int $reversal):int{$d=['unit_id'=>$this->unit_id,'financial_account_id'=>$account,'movement_date'=>$date,'movement_type'=>$type,'source_type'=>$source,'source_id'=>$sourceId,'description'=>$description,'amount'=>$amount,'reversal_of_movement_id'=>$reversal,'created_by'=>$this->actor_id?:null];return (int)$this->cash->ci_save($d,0);}
    private function activeAccount(int $id):object{$r=$this->scoped('gd_financial_accounts',$id);if($r->status!=='active')throw new \DomainException('gd_finance_account_inactive');return $r;}
    private function scoped(string $table,int $id):object{$r=$this->db->table($this->db->prefixTable($table))->where('id',$id)->where('unit_id',$this->unit_id)->where('deleted',0)->get(1)->getRow();if(!$r)throw new \DomainException('gd_record_not_found');return $r;}
    private function reference($v):string{$v=trim((string)$v);if($v==='' )return '';if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$v))throw new \DomainException('gd_finance_invalid_reference');return $v;}
    private function cents(string $v):int{$negative=str_starts_with(trim($v),'-');$v=DataNormalizationService::decimal($negative?substr(trim($v),1):$v,2);[$i,$f]=explode('.',$v);$c=(int)$i*100+(int)$f;return $negative?-$c:$c;}private function money(int $c):string{$sign=$c<0?'-':'';$c=abs($c);return $sign.intdiv($c,100).'.'.str_pad((string)($c%100),2,'0',STR_PAD_LEFT);}private function add(string $a,string $b):string{return $this->money($this->cents($a)+$this->cents($b));}private function sub(string $a,string $b):string{return $this->money($this->cents($a)-$this->cents($b));}private function multiply(string $q,string $u):string{[$qi,$qf]=explode('.',DataNormalizationService::decimal($q,3));$m=(int)$qi*1000+(int)$qf;$c=$this->cents($u);$raw=$m*$c;if($raw%1000!==0)throw new \DomainException('gd_finance_fractional_cent');return $this->money(intdiv($raw,1000));}
}
