<?php
declare(strict_types=1);namespace grupo_donato_gestao\Services;
class ReceivableGenerationService extends CustomerDataService
{
    private ?object $login_user;public function __construct(int $unit_id,int $actor_id=0,?object $login_user=null){parent::__construct($unit_id,$actor_id,$login_user);$this->login_user=$login_user;}
    public function preview(string $month):array{$this->month($month);$first=$month.'-01';$last=(new \DateTimeImmutable($first))->format('Y-m-t');$out=[];$e=$this->db->query("SELECT e.id,e.product_id,e.preferred_due_day,c.name class_name,p.full_name,sp.family_account_id,a.display_name customer_name FROM `{$this->db->prefixTable('gd_enrollments')}` e JOIN `{$this->db->prefixTable('gd_school_profiles')}` sp ON sp.id=e.school_profile_id AND sp.unit_id=e.unit_id AND sp.deleted=0 JOIN `{$this->db->prefixTable('gd_people')}` p ON p.id=sp.person_id AND p.deleted=0 JOIN `{$this->db->prefixTable('gd_customer_accounts')}` a ON a.id=sp.family_account_id AND a.deleted=0 JOIN `{$this->db->prefixTable('gd_classes')}` c ON c.id=e.class_id AND c.deleted=0 WHERE e.unit_id=? AND e.status='active' AND e.deleted=0 AND e.starts_on<=? AND (e.ends_on IS NULL OR e.ends_on>=?)",[$this->unit_id,$last,$first])->getResult();foreach($e as $row){$amount=null;if($row->product_id){$price=(new PricingService($this->unit_id,$this->actor_id,$this->login_user))->resolve(['product_id'=>(int)$row->product_id,'reference_date'=>$first,'quantity'=>'1']);if(!empty($price['found']))$amount=$price['amount'];}$out[]=['key'=>'enrollment:'.$row->id,'source_type'=>'enrollment','source_id'=>(int)$row->id,'customer_account_id'=>(int)$row->family_account_id,'customer_name'=>$row->customer_name,'description'=>'Mensalidade '.$row->class_name.' — '.$row->full_name,'product_id'=>(int)$row->product_id,'amount'=>$amount,'due_date'=>$this->due($month,(int)($row->preferred_due_day?:10)),'ready'=>$amount!==null];}
        $rentals=$this->db->table($this->db->prefixTable('gd_court_rentals').' r')->select('r.id,r.customer_account_id,r.title,r.preferred_due_day,r.negotiated_amount,r.product_id,a.display_name customer_name')->join($this->db->prefixTable('gd_customer_accounts').' a','a.id=r.customer_account_id AND a.unit_id=r.unit_id AND a.deleted=0','inner',false)->where('r.unit_id',$this->unit_id)->where('r.rental_type','recurring')->where('r.status','active')->where('r.deleted',0)->groupStart()->where('r.effective_from IS NULL',null,false)->orWhere('r.effective_from <=',$last)->groupEnd()->groupStart()->where('r.effective_until IS NULL',null,false)->orWhere('r.effective_until >=',$first)->groupEnd()->get()->getResult();foreach($rentals as $row)$out[]=['key'=>'court_rental:'.$row->id,'source_type'=>'court_rental','source_id'=>(int)$row->id,'customer_account_id'=>(int)$row->customer_account_id,'customer_name'=>$row->customer_name,'description'=>'Mensalista — '.$row->title,'product_id'=>(int)$row->product_id,'amount'=>$row->negotiated_amount,'due_date'=>$this->due($month,(int)($row->preferred_due_day?:10)),'ready'=>$row->negotiated_amount!==null];return $out;}
    public function generateMonth(string $month,array $adjustments=[]):array{$rows=$this->preview($month);$result=['generated'=>[],'ignored'=>[],'errors'=>[]];$finance=new FinanceService($this->unit_id,$this->actor_id,$this->login_user);foreach($rows as $row){$adj=(array)($adjustments[$row['key']]??[]);$amount=$adj['amount']??$row['amount'];$due=$adj['due_date']??$row['due_date'];if($amount===null||$amount===''){$result['errors'][]=['key'=>$row['key'],'error'=>'gd_finance_amount_required'];continue;}try{$saved=$finance->createReceivable($row+['reference_month'=>$month,'issue_date'=>gmdate('Y-m-d'),'due_date'=>$due,'original_amount'=>$amount,'unit_amount'=>$amount,'quantity'=>'1']);if(!empty($saved['created']))$result['generated'][]=$saved;else$result['ignored'][]=$row['key'];}catch(\Throwable $e){$result['errors'][]=['key'=>$row['key'],'error'=>$e->getMessage()];}}return $result;}
    public function generateCourtRental(int $id,array $override=[]):array{$r=$this->db->table($this->db->prefixTable('gd_court_rentals'))->where('id',$id)->where('unit_id',$this->unit_id)->where('deleted',0)->get(1)->getRow();if(!$r||$r->rental_type!=='single')throw new \DomainException('gd_record_not_found');$amount=$override['amount']??$r->negotiated_amount;if($amount===null)throw new \DomainException('gd_finance_amount_required');return (new FinanceService($this->unit_id,$this->actor_id,$this->login_user))->createReceivable(['source_type'=>'court_rental','source_id'=>$id,'reference_month'=>'','description'=>'Locação avulsa — '.$r->title,'issue_date'=>gmdate('Y-m-d'),'due_date'=>$override['due_date']??gmdate('Y-m-d'),'original_amount'=>$amount,'unit_amount'=>$amount,'quantity'=>'1','product_id'=>(int)$r->product_id]);}
    private function month(string $m):void{if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$m))throw new \DomainException('gd_finance_invalid_reference');}private function due(string $m,int $day):string{$this->month($m);$max=(int)(new \DateTimeImmutable($m.'-01'))->format('t');return sprintf('%s-%02d',$m,min(max($day,1),$max));}
}
