<?php
declare(strict_types=1);
namespace grupo_donato_gestao\Services;
use grupo_donato_gestao\Config\Constants;
class SchoolEnrollmentService extends CustomerDataService
{
    private $model;
    public function __construct(int $unit_id,int $actor_id=0,?object $login_user=null){parent::__construct($unit_id,$actor_id,$login_user);$this->model=model('grupo_donato_gestao\\Models\\Gd_enrollments_model');}
    public function save(array $input,int $id=0):array
    {
        $old=$id?$this->model->get_scoped($id,$this->unit_id):null;if($id&&!$old)throw new \DomainException('gd_record_not_found');$class_id=(int)($input['class_id']??($old->class_id??0));$profile_id=(int)($input['school_profile_id']??($old->school_profile_id??0));$status=(string)($input['status']??'active');if(!in_array($status,Constants::SCHOOL_ENROLLMENT_STATUSES,true))throw new \DomainException('gd_invalid_value');$class=$this->scoped('gd_classes',$class_id);$profile=$this->scoped('gd_school_profiles',$profile_id);if(in_array($status,Constants::SCHOOL_ENROLLMENT_OPEN_STATUSES,true)&&((string)$class->status!=='active'||(string)$profile->status!=='active'))throw new \DomainException('gd_school_inactive_target');$starts=$this->valid_date($input['starts_on']??gmdate('Y-m-d'));$ends=$this->valid_date($input['ends_on']??'');if(!$starts||($ends&&$ends<$starts))throw new \DomainException('gd_invalid_date_range');$due=trim((string)($input['preferred_due_day']??''));$due=$due===''?null:(int)$due;if($due!==null&&($due<1||$due>31))throw new \DomainException('gd_invalid_due_day');$product=(int)($input['product_id']??0);if($product){$p=$this->scoped('gd_products',$product);if((string)$p->status!=='active')throw new \DomainException('gd_invalid_product');}
        $lock='gd:school-class:'.$this->unit_id.':'.$class_id;if((int)$this->db->query('SELECT GET_LOCK(?,10) acquired',[$lock])->getRow()->acquired!==1)throw new \RuntimeException('gd_lock_timeout');$this->db->transBegin();try{if(in_array($status,Constants::SCHOOL_ENROLLMENT_OPEN_STATUSES,true)){$dup=$this->db->table($this->db->prefixTable('gd_enrollments'))->where('unit_id',$this->unit_id)->where('class_id',$class_id)->where('school_profile_id',$profile_id)->whereIn('status',Constants::SCHOOL_ENROLLMENT_OPEN_STATUSES)->where('deleted',0);if($id)$dup->where('id !=',$id);if($dup->countAllResults()>0)throw new \DomainException('gd_school_duplicate_enrollment');$count=$this->db->table($this->db->prefixTable('gd_enrollments'))->where('unit_id',$this->unit_id)->where('class_id',$class_id)->whereIn('status',Constants::SCHOOL_ENROLLMENT_OPEN_STATUSES)->where('deleted',0);if($id)$count->where('id !=',$id);if($count->countAllResults()>=(int)$class->capacity)throw new \DomainException('gd_school_capacity_reached');}
            $notes=DataNormalizationService::text($input['notes']??'');$data=$this->stamp(['unit_id'=>$this->unit_id,'class_id'=>$class_id,'school_profile_id'=>$profile_id,'product_id'=>$product?:null,'starts_on'=>$starts,'ends_on'=>$ends,'preferred_due_day'=>$due,'status'=>$status,'notes'=>$notes?:null],$id===0);if($id){if(!$this->model->optimistic_update($id,$this->unit_id,(int)($input['lock_version']??0),$data))throw new \DomainException('gd_concurrency_conflict');$saved=$id;}else{$saved=(int)$this->model->ci_save($data,0);}if(!$saved)throw new \RuntimeException('save_failed');$after=$this->model->get_scoped($saved,$this->unit_id);$beforeData=$old?(array)$old:null;$afterData=$after?(array)$after:null;$this->audit_change($id?'update':'create','school_enrollment',$saved,$beforeData,$afterData);if($this->db->transCommit()===false)throw new \RuntimeException('save_failed');return ['id'=>$saved];}catch(\Throwable $e){$this->db->transRollback();throw $e;}finally{$this->db->query('SELECT RELEASE_LOCK(?)',[$lock]);}
    }
    private function scoped(string $table,int $id):object{$r=$this->db->table($this->db->prefixTable($table))->where('id',$id)->where('unit_id',$this->unit_id)->where('deleted',0)->get(1)->getRow();if(!$r)throw new \DomainException('gd_record_not_found');return $r;}
}
