<?php
declare(strict_types=1);
namespace grupo_donato_gestao\Services;
use grupo_donato_gestao\Config\Constants;
class SchoolAttendanceService extends CustomerDataService
{
    private $sessions;private $records;
    public function __construct(int $unit_id,int $actor_id=0,?object $login_user=null){parent::__construct($unit_id,$actor_id,$login_user);$this->sessions=model('grupo_donato_gestao\\Models\\Gd_attendance_sessions_model');$this->records=model('grupo_donato_gestao\\Models\\Gd_attendance_records_model');}
    public function roster(int $class_id,string $date):array
    {
        $date=$this->valid_date($date)??throw new \DomainException('gd_invalid_date');$class=$this->db->table($this->db->prefixTable('gd_classes'))->where('id',$class_id)->where('unit_id',$this->unit_id)->where('deleted',0)->get(1)->getRow();if(!$class)throw new \DomainException('gd_record_not_found');$session=$this->sessions->for_date($class_id,$date,$this->unit_id);$sid=(int)($session->id??0);
        $rows=$this->db->query("SELECT sp.id school_profile_id,p.full_name,COALESCE(r.attendance_status,'unmarked') attendance_status,r.notes FROM `{$this->db->prefixTable('gd_enrollments')}` e JOIN `{$this->db->prefixTable('gd_school_profiles')}` sp ON sp.id=e.school_profile_id AND sp.unit_id=e.unit_id AND sp.deleted=0 JOIN `{$this->db->prefixTable('gd_people')}` p ON p.id=sp.person_id AND p.unit_id=sp.unit_id AND p.deleted=0 LEFT JOIN `{$this->db->prefixTable('gd_attendance_records')}` r ON r.attendance_session_id=? AND r.school_profile_id=sp.id AND r.unit_id=sp.unit_id WHERE e.unit_id=? AND e.class_id=? AND e.deleted=0 AND e.status IN ('active','paused') AND e.starts_on<=? AND (e.ends_on IS NULL OR e.ends_on>=?) ORDER BY p.full_name",[$sid,$this->unit_id,$class_id,$date,$date])->getResult();return ['class'=>$class,'date'=>$date,'session'=>$session,'students'=>$rows,'totals'=>$this->totals($rows)];
    }
    public function saveBatch(int $class_id,string $date,array $marks,string $session_status='completed'):array
    {
        if(!in_array($session_status,Constants::SCHOOL_ATTENDANCE_SESSION_STATUSES,true))throw new \DomainException('gd_invalid_value');$roster=$this->roster($class_id,$date);$allowed=array_map(fn($r)=>(int)$r->school_profile_id,$roster['students']);$this->db->transBegin();try{$session=$roster['session'];if(!$session){$sessionData=$this->stamp(['unit_id'=>$this->unit_id,'class_id'=>$class_id,'attendance_date'=>$date,'status'=>$session_status,'notes'=>null],true);$sid=(int)$this->sessions->ci_save($sessionData,0);}else{$sid=(int)$session->id;$sessionData=$this->stamp(['status'=>$session_status],false);$this->sessions->ci_save($sessionData,$sid);}foreach($marks as $profile=>$mark){$profile=(int)$profile;if(!in_array($profile,$allowed,true))throw new \DomainException('gd_school_attendance_roster');$status=is_array($mark)?(string)($mark['status']??'unmarked'):(string)$mark;if(!in_array($status,Constants::SCHOOL_ATTENDANCE_STATUSES,true))throw new \DomainException('gd_invalid_value');$notes=is_array($mark)?DataNormalizationService::text($mark['notes']??''):'';$old=$this->db->table($this->db->prefixTable('gd_attendance_records'))->where('attendance_session_id',$sid)->where('school_profile_id',$profile)->get(1)->getRow();$data=$this->stamp(['unit_id'=>$this->unit_id,'attendance_session_id'=>$sid,'class_id'=>$class_id,'school_profile_id'=>$profile,'attendance_status'=>$status,'notes'=>$notes?:null],!$old);$this->records->ci_save($data,(int)($old->id??0));}$this->audit_change('batch_save','school_attendance_session',$sid,null,['class_id'=>$class_id,'attendance_date'=>$date,'marks'=>count($marks)]);if($this->db->transCommit()===false)throw new \RuntimeException('save_failed');return $this->roster($class_id,$date);}catch(\Throwable $e){$this->db->transRollback();throw $e;}
    }
    private function totals(array $rows):array{$out=array_fill_keys(Constants::SCHOOL_ATTENDANCE_STATUSES,0);foreach($rows as $r)$out[$r->attendance_status]++;return $out;}
}
