<?php
declare(strict_types=1);
namespace grupo_donato_gestao\Services;
use grupo_donato_gestao\Config\Constants;
class SchoolClassService extends CustomerDataService
{
    private $classes; private ?object $login_user;
    public function __construct(int $unit_id,int $actor_id=0,?object $login_user=null){parent::__construct($unit_id,$actor_id,$login_user);$this->classes=model('grupo_donato_gestao\\Models\\Gd_classes_model');$this->login_user=$login_user;}
    public function save(array $input,int $id=0):array
    {
        $old=$id?$this->classes->get_scoped($id,$this->unit_id):null;if($id&&!$old)throw new \DomainException('gd_record_not_found');$name=DataNormalizationService::text($input['name']??'');$modality=DataNormalizationService::text($input['modality']??'');if($name===''||$modality==='')throw new \DomainException('gd_school_class_required');$type=(string)($input['class_type']??'group');$status=(string)($input['status']??'active');if(!in_array($type,Constants::SCHOOL_CLASS_TYPES,true)||!in_array($status,Constants::SCHOOL_CLASS_STATUSES,true))throw new \DomainException('gd_invalid_value');
        $user=(int)($input['instructor_user_id']??0);$person=(int)($input['instructor_person_id']??0);if($user&&$person)throw new \DomainException('gd_school_one_instructor');if($user)$this->assertRise($this->db->prefixTable('users'),$user);if($person)$this->assertScoped('gd_people',$person);$resource=(int)($input['resource_id']??0);if($resource)$this->assertScoped('gd_resources',$resource);
        $series=(int)($input['booking_series_id']??0);$booking=(int)($input['booking_id']??0);if($series&&$booking)throw new \DomainException('gd_school_one_schedule');if($series)$this->assertScoped('gd_booking_series',$series);if($booking)$this->assertScoped('gd_bookings',$booking);
        $days=array_values(array_unique(array_filter(array_map('intval',(array)($input['weekdays']??[])),fn($d)=>$d>=1&&$d<=7)));sort($days);$start=trim((string)($input['local_start_time']??''))?:null;$end=trim((string)($input['local_end_time']??''))?:null;if(($start&&!$end)||($end&&!$start)||($start&&$end&&$end<=$start))throw new \DomainException('gd_invalid_time_range');$capacity=max(1,(int)($input['capacity']??($type==='personal'?1:20)));$min=trim((string)($input['min_age']??''))!==''?(int)$input['min_age']:null;$max=trim((string)($input['max_age']??''))!==''?(int)$input['max_age']:null;if($min!==null&&$max!==null&&$max<$min)throw new \DomainException('gd_invalid_age_range');$starts=$this->valid_date($input['starts_on']??'');$ends=$this->valid_date($input['ends_on']??'');if($starts&&$ends&&$ends<$starts)throw new \DomainException('gd_invalid_date_range');
        $this->db->transBegin();try{if(!$series&&!$booking&&!empty($input['create_series'])){if(!$resource||!$days||!$start||!$end||!$starts)throw new \DomainException('gd_school_schedule_required');$seriesResult=(new BookingSeriesService($this->unit_id,$this->actor_id,$this->login_user))->create(['booking_type'=>'school','title'=>$name,'frequency'=>'weekly','interval_value'=>1,'weekdays'=>$days,'local_start_time'=>$start,'local_end_time'=>$end,'starts_on'=>$starts,'ends_mode'=>$ends?'on_date':'never','ends_on'=>$ends,'default_booking_status'=>'confirmed','conflict_policy'=>'skip','horizon_days'=>180,'resources'=>[['resource_id'=>$resource]]],true);$series=(int)$seriesResult['id'];}
            $number=$old->class_number??'';if(!$number){$seq=new SequenceService();$seq->ensure($this->unit_id,'school_class','TUR-'.gmdate('Y').'-',5,true);$number=$seq->next($this->unit_id,'school_class');}
            $data=$this->stamp(['unit_id'=>$this->unit_id,'class_number'=>$number,'name'=>$name,'modality'=>$modality,'class_type'=>$type,'instructor_user_id'=>$user?:null,'instructor_person_id'=>$person?:null,'resource_id'=>$resource?:null,'booking_series_id'=>$series?:null,'booking_id'=>$booking?:null,'weekdays'=>$days?implode(',',$days):null,'local_start_time'=>$start,'local_end_time'=>$end,'timezone'=>(new TemporalService($this->unit_id))->timezoneName(),'capacity'=>$capacity,'min_age'=>$min,'max_age'=>$max,'starts_on'=>$starts,'ends_on'=>$ends,'status'=>$status,'notes'=>DataNormalizationService::text($input['notes']??'')?:null,'metadata'=>json_encode(['source'=>'school'],JSON_UNESCAPED_SLASHES)],$id===0);
            if($id){$version=(int)($input['lock_version']??0);if(!$this->classes->optimistic_update($id,$this->unit_id,$version,$data))throw new \DomainException('gd_concurrency_conflict');$saved=$id;}else{$saved=(int)$this->classes->ci_save($data,0);}if(!$saved)throw new \RuntimeException('save_failed');$after=$this->classes->get_scoped($saved,$this->unit_id);$beforeData=$old?(array)$old:null;$afterData=$after?(array)$after:null;$this->audit_change($id?'update':'create','school_class',$saved,$beforeData,$afterData);if($this->db->transCommit()===false)throw new \RuntimeException('save_failed');return ['id'=>$saved,'class_number'=>$number,'booking_series_id'=>($series?:null)];}catch(\Throwable $e){$this->db->transRollback();throw $e;}
    }
    public function get(int $id):?object{$c=$this->classes->get_scoped($id,$this->unit_id);if(!$c)return null;$c->enrollments=$this->db->query("SELECT e.*,p.full_name FROM `{$this->db->prefixTable('gd_enrollments')}` e JOIN `{$this->db->prefixTable('gd_school_profiles')}` sp ON sp.id=e.school_profile_id AND sp.unit_id=e.unit_id AND sp.deleted=0 JOIN `{$this->db->prefixTable('gd_people')}` p ON p.id=sp.person_id AND p.deleted=0 WHERE e.unit_id=? AND e.class_id=? AND e.deleted=0 ORDER BY p.full_name",[$this->unit_id,$id])->getResult();return $c;}
    public function listPage(array $o):array{$t=$this->db->prefixTable('gd_classes');$base=function()use($o,$t){$q=$this->db->table($t)->where('unit_id',$this->unit_id)->where('deleted',0);if($v=trim((string)($o['status']??'')))$q->where('status',$v);if($v=trim((string)($o['class_type']??'')))$q->where('class_type',$v);if($v=trim((string)($o['search_by']??'')))$q->groupStart()->like('name',$v)->orLike('modality',$v)->orLike('class_number',$v)->groupEnd();return $q;};$total=$this->db->table($t)->where('unit_id',$this->unit_id)->where('deleted',0)->countAllResults();$filtered=$base()->countAllResults(false);$e=$this->db->prefixTable('gd_enrollments');$r=$this->db->prefixTable('gd_resources');$p=$this->db->prefixTable('gd_people');$u=$this->db->prefixTable('users');$rows=$base()->select("$t.*,(SELECT COUNT(*) FROM `$e` ee WHERE ee.class_id=$t.id AND ee.unit_id=$t.unit_id AND ee.deleted=0 AND ee.status IN ('active','paused')) enrolled,(SELECT name FROM `$r` rr WHERE rr.id=$t.resource_id AND rr.unit_id=$t.unit_id AND rr.deleted=0) resource_name,COALESCE((SELECT full_name FROM `$p` ip WHERE ip.id=$t.instructor_person_id AND ip.unit_id=$t.unit_id AND ip.deleted=0),(SELECT TRIM(CONCAT(first_name,' ',last_name)) FROM `$u` iu WHERE iu.id=$t.instructor_user_id)) instructor_name",false)->orderBy('name')->limit(max(1,min(100,(int)($o['limit']??25))),max(0,(int)($o['skip']??0)))->get()->getResult();return ['data'=>$rows,'recordsTotal'=>$total,'recordsFiltered'=>$filtered];}
    private function assertScoped(string $table,int $id):object{$r=$this->db->table($this->db->prefixTable($table))->where('id',$id)->where('unit_id',$this->unit_id)->where('deleted',0)->get(1)->getRow();if(!$r)throw new \DomainException('gd_record_not_found');return $r;}private function assertRise(string $table,int $id):void{if($this->db->table($table)->where('id',$id)->countAllResults()!==1)throw new \DomainException('gd_invalid_rise_link');}
}
