<?php $e = static fn($value) => htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8"); $id = (int) ($model_info->id ?? 0); ?>
<?php echo form_open(get_uri("grupo_donato/addresses/save"), ["id" => "gd-address-form", "class" => "general-form", "role" => "form"]); ?>
<div class="modal-body clearfix"><div class="container-fluid">
    <input type="hidden" name="id" value="<?php echo $id; ?>"><input type="hidden" name="account_id" value="<?php echo (int) $account_id; ?>"><input type="hidden" name="duplicate_override" value="0">
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_address_type"); ?></label><div class="col-md-9"><select name="address_type" class="form-control"><?php foreach ($types as $option) { ?><option value="<?php echo $e($option["id"]); ?>"<?php echo ($model_info->address_type ?? "main") === $option["id"] ? " selected" : ""; ?>><?php echo $e($option["text"]); ?></option><?php } ?></select></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_postal_code"); ?></label><div class="col-md-3"><?php echo form_input(["name" => "postal_code", "value" => $model_info->postal_code ?? "", "class" => "form-control", "maxlength" => 20]); ?></div><label class="col-md-2"><?php echo app_lang("gd_street"); ?></label><div class="col-md-4"><?php echo form_input(["name" => "street", "value" => $model_info->street ?? "", "class" => "form-control", "maxlength" => 190]); ?></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_number"); ?></label><div class="col-md-3"><?php echo form_input(["name" => "number", "value" => $model_info->number ?? "", "class" => "form-control", "maxlength" => 30]); ?></div><label class="col-md-2"><?php echo app_lang("gd_complement"); ?></label><div class="col-md-4"><?php echo form_input(["name" => "complement", "value" => $model_info->complement ?? "", "class" => "form-control", "maxlength" => 120]); ?></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_district"); ?></label><div class="col-md-3"><?php echo form_input(["name" => "district", "value" => $model_info->district ?? "", "class" => "form-control", "maxlength" => 120]); ?></div><label class="col-md-2"><?php echo app_lang("gd_city"); ?></label><div class="col-md-4"><?php echo form_input(["name" => "city", "value" => $model_info->city ?? "", "class" => "form-control", "maxlength" => 120]); ?></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_state"); ?></label><div class="col-md-3"><?php echo form_input(["name" => "state", "value" => $model_info->state ?? "", "class" => "form-control", "maxlength" => 80]); ?></div><label class="col-md-2"><?php echo app_lang("gd_country"); ?></label><div class="col-md-4"><?php echo form_input(["name" => "country", "value" => $model_info->country ?? "", "class" => "form-control", "maxlength" => 80]); ?></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_flags"); ?></label><div class="col-md-9"><?php echo form_checkbox("is_primary", "1", !empty($model_info->is_primary)); ?> <?php echo app_lang("gd_primary"); ?></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_status"); ?></label><div class="col-md-9"><select name="status" class="form-control"><option value="active"<?php echo ($model_info->status ?? "active") === "active" ? " selected" : ""; ?>><?php echo app_lang("gd_status_active"); ?></option><option value="inactive"<?php echo ($model_info->status ?? "") === "inactive" ? " selected" : ""; ?>><?php echo app_lang("gd_status_inactive"); ?></option></select></div></div></div>
    <?php if ($id) { ?><div class="form-group"><div class="row"><label class="col-md-3 text-danger"><?php echo app_lang("gd_delete_reason"); ?></label><div class="col-md-9"><?php echo form_input(["name" => "reason", "class" => "form-control", "maxlength" => 500]); ?></div></div></div><?php } ?>
</div></div>
<div class="modal-footer"><?php if ($id) { ?><button type="button" id="gd-delete-address" class="btn btn-danger me-auto"><?php echo app_lang("delete"); ?></button><?php } ?><button type="button" class="btn btn-default" data-bs-dismiss="modal"><?php echo app_lang("close"); ?></button><button type="submit" class="btn btn-primary"><?php echo app_lang("save"); ?></button></div><?php echo form_close(); ?>
<script type="text/javascript">
$(document).ready(function () { var form = $("#gd-address-form"); form.appForm({onSuccess: function () { location.reload(); }, onError: function (result) { if (result.duplicate_confirmation_required && window.confirm('<?php echo addslashes(app_lang("gd_confirm_duplicate_override")); ?>')) { form.find("[name=duplicate_override]").val("1"); setTimeout(function () { form.trigger("submit"); }, 100); } return true; }}); $("#gd-delete-address").click(function () { if (!form.find("[name=reason]").val()) { appAlert.error('<?php echo addslashes(app_lang("gd_delete_reason_required")); ?>', {container: ".modal-body", animate: false}); return; } $.post('<?php echo_uri("grupo_donato/addresses/delete"); ?>', form.serialize(), function (result) { if (result.success) location.reload(); else appAlert.error(result.message, {container: ".modal-body", animate: false}); }, "json"); }); });
</script>
