<?php
$money = static function ($value): string { $raw = trim((string) $value); $negative = str_starts_with($raw, "-"); $raw = ltrim($raw, "+-"); if (strpos($raw, ",") !== false && strpos($raw, ".") === false) $raw = str_replace(",", ".", $raw); [$i, $f] = array_pad(explode(".", $raw, 2), 2, "00"); $i = ltrim($i, "0") ?: "0"; return ($negative ? "-" : "") . "R$ " . (preg_replace('/\B(?=(\d{3})+(?!\d))/', ".", $i) ?: $i) . "," . str_pad(substr($f, 0, 2), 2, "0"); };
?>
<div class="modal-body">
    <div class="d-flex justify-content-between align-items-start"><div><h4 class="mb5"><?php echo esc($cost->description); ?></h4><span class="text-muted"><?php echo esc($cost->expense_number); ?> · <?php echo esc($cost->payee ?: "-"); ?></span></div><span class="badge bg-secondary"><?php echo esc(app_lang("gd_cost_status_" . ($cost->display_status ?: "pending"))); ?></span></div>
    <hr>
    <div class="row"><div class="col-md-3"><small class="text-muted"><?php echo app_lang("gd_costs_competence"); ?></small><br><?php echo esc($cost->reference_month); ?></div><div class="col-md-3"><small class="text-muted"><?php echo app_lang("gd_costs_issue_date"); ?></small><br><?php echo format_to_date($cost->issue_date, false); ?></div><div class="col-md-3"><small class="text-muted"><?php echo app_lang("gd_finance_due"); ?></small><br><?php echo $cost->due_date ? format_to_date($cost->due_date, false) : "-"; ?></div><div class="col-md-3"><small class="text-muted"><?php echo app_lang("gd_costs_nature"); ?></small><br><?php echo esc(app_lang("gd_cost_nature_" . $cost->nature)); ?></div></div>
    <div class="row mt15"><div class="col-md-3"><small class="text-muted"><?php echo app_lang("gd_costs_gross"); ?></small><br><?php echo $money($cost->gross_amount); ?></div><div class="col-md-3"><small class="text-muted"><?php echo app_lang("gd_costs_discount"); ?></small><br><?php echo $money($cost->discount_amount); ?></div><div class="col-md-3"><small class="text-muted"><?php echo app_lang("gd_costs_interest"); ?> / <?php echo app_lang("gd_costs_penalty"); ?></small><br><?php echo $money($cost->interest_amount); ?> / <?php echo $money($cost->penalty_amount); ?></div><div class="col-md-3"><small class="text-muted"><?php echo app_lang("gd_costs_final"); ?> / <?php echo app_lang("gd_costs_balance"); ?></small><br><strong><?php echo $money($cost->final_amount); ?></strong> / <?php echo $money($cost->balance_amount); ?></div></div>
    <div class="row mt15"><div class="col-md-3"><small class="text-muted"><?php echo app_lang("gd_costs_category"); ?></small><br><?php echo esc($cost->subcategory_name ?: ($cost->category_name ?: "-")); ?></div><div class="col-md-3"><small class="text-muted"><?php echo app_lang("gd_costs_center"); ?></small><br><?php echo esc($cost->cost_center_name ?: "-"); ?></div><div class="col-md-3"><small class="text-muted"><?php echo app_lang("gd_costs_business_area"); ?></small><br><?php echo esc($cost->business_area_name ?: "-"); ?></div><div class="col-md-3"><small class="text-muted"><?php echo app_lang("gd_costs_behavior"); ?></small><br><?php echo esc(app_lang("gd_cost_behavior_" . $cost->cost_behavior)); ?></div></div>
    <?php if ($cost->notes): ?><div class="alert alert-light mt15"><?php echo nl2br(esc($cost->notes)); ?></div><?php endif; ?>
    <hr><h5><?php echo app_lang("gd_costs_paid"); ?></h5>
    <div class="table-responsive"><table class="table table-sm"><thead><tr><th><?php echo app_lang("gd_finance_number"); ?></th><th><?php echo app_lang("gd_finance_payment_date"); ?></th><th><?php echo app_lang("gd_finance_method"); ?></th><th><?php echo app_lang("gd_finance_amount"); ?></th><th><?php echo app_lang("gd_status"); ?></th><th></th></tr></thead><tbody><?php foreach ($cost->payments as $payment): ?><tr><td><?php echo esc($payment->payment_number); ?></td><td><?php echo format_to_date($payment->payment_date, false); ?></td><td><?php echo esc(app_lang("gd_finance_method_" . $payment->payment_method)); ?></td><td><?php echo $money($payment->amount); ?></td><td><?php echo esc($payment->status); ?></td><td><?php if ($can_pay && in_array((string) $payment->status, ["confirmed", "legacy_migrated"], true)) echo ajax_anchor(get_uri("grupo_donato/finance/costs/payment/reverse"), '<i data-feather="rotate-ccw" class="icon-14"></i>', ["data-post-id" => (int) $payment->id, "data-post-reason" => app_lang("gd_cost_payment_reversed"), "data-reload-on-success" => 1, "title" => app_lang("gd_cost_payment_reversed")]); ?></td></tr><?php endforeach; ?><?php if (!$cost->payments): ?><tr><td colspan="6" class="text-muted text-center">-</td></tr><?php endif; ?></tbody></table></div>
    <?php if ($can_manage): ?><hr><h5><?php echo app_lang("gd_attachment_uploaded"); ?></h5><form id="gd-cost-attachment-form" enctype="multipart/form-data"><input type="hidden" name="expense_id" value="<?php echo (int) $cost->id; ?>"><div class="row"><div class="col-md-5"><input type="file" name="file[]" class="form-control" accept=".pdf,.jpg,.jpeg,.png,.webp" multiple required></div><div class="col-md-3"><select name="document_type" class="form-control"><option value="invoice">Nota fiscal</option><option value="boleto">Boleto</option><option value="receipt">Recibo</option><option value="pix_proof">Comprovante PIX</option><option value="contract">Contrato</option><option value="photo">Foto</option><option value="other">Outro</option></select></div><div class="col-md-4"><button class="btn btn-default" type="submit"><i data-feather="paperclip" class="icon-14"></i> <?php echo app_lang("gd_attachment_uploaded"); ?></button></div></div></form><ul class="mt10"><?php foreach ($cost->attachments as $attachment): ?><li><a href="<?php echo get_uri("grupo_donato/finance/costs/attachments/" . (int) $attachment->id); ?>"><?php echo esc($attachment->original_name); ?></a> <small class="text-muted">(<?php echo number_format((int) $attachment->file_size); ?> bytes)</small></li><?php endforeach; ?></ul><?php endif; ?>
</div>
<div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal"><?php echo app_lang("close"); ?></button><?php if ($can_pay && (string) $cost->balance_amount !== "0.00" && $cost->status !== "cancelled"): ?><?php echo modal_anchor(get_uri("grupo_donato/finance/costs/payment-modal"), app_lang("gd_cost_register_payment"), ["class" => "btn btn-primary", "data-post-id" => (int) $cost->id]); ?><?php endif; ?></div>
<script>
$(document).ready(function () { var form = $("#gd-cost-attachment-form"); form.on("submit", function (event) { event.preventDefault(); var data = new FormData(this); $.ajax({url: "<?php echo get_uri("grupo_donato/finance/costs/attachments/upload"); ?>", type: "POST", data: data, processData: false, contentType: false, dataType: "json"}).done(function (result) { if (result.success) location.reload(); else appAlert.error(result.message); }).fail(function () { appAlert.error("<?php echo addslashes(app_lang("error_occurred")); ?>"); }); }); });
</script>
