<?php
$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,"UTF-8");$id=(int)($model_info->id??0);$selected=[];foreach(($model_info->resources??[]) as $r){$selected[(int)$r->resource_id]=$r;}
?>
<?php $series_scope=$series_scope??"";$booking_save_uri=$series_scope==="single"?"grupo_donato/booking-series/update-occurrence":"grupo_donato/bookings/save";$customer_options_uri=$customer_options_uri??"grupo_donato/bookings/customer-options";$contact_options_uri=$contact_options_uri??"grupo_donato/bookings/contact-options";$booking_check_uri=$booking_check_uri??"grupo_donato/bookings/check-availability"; ?>
<?php echo form_open(get_uri($booking_save_uri),["id"=>"gd-booking-form","class"=>"general-form","role"=>"form"]); ?>
<div class="modal-body clearfix"><div class="container-fluid"><input type="hidden" name="id" value="<?php echo $id; ?>"><input type="hidden" name="lock_version" value="<?php echo (int)($model_info->lock_version??0); ?>">
<div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_type"); ?></label><div class="col-md-3"><select name="booking_type" class="form-control"><?php foreach($types as $v){ ?><option value="<?php echo $e($v); ?>"<?php echo ($model_info->booking_type??"internal")===$v?" selected":""; ?>><?php echo app_lang("gd_booking_type_".$v); ?></option><?php } ?></select></div><label class="col-md-3"><?php echo app_lang("gd_status"); ?></label><div class="col-md-3"><?php if($id){ ?><input class="form-control" value="<?php echo app_lang("gd_booking_status_".$model_info->status); ?>" disabled><?php }else{ ?><select name="status" id="gd-booking-status" class="form-control"><?php foreach($initial_statuses as $v){ ?><option value="<?php echo $v; ?>"><?php echo app_lang("gd_booking_status_".$v); ?></option><?php } ?></select><?php } ?></div></div></div>
<div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_title"); ?></label><div class="col-md-9"><input name="title" class="form-control" maxlength="180" required value="<?php echo $e($model_info->title??""); ?>"></div></div></div>
<div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_customer"); ?></label><div class="col-md-3"><select name="customer_account_id" id="gd-booking-customer" class="form-control"><option value=""></option><?php foreach($accounts as $a){ ?><option value="<?php echo (int)$a["id"]; ?>"<?php echo (int)($model_info->customer_account_id??0)===(int)$a["id"]?" selected":""; ?>><?php echo $e($a["display_name"]); ?></option><?php } ?></select></div><label class="col-md-3"><?php echo app_lang("gd_contact"); ?></label><div class="col-md-3"><select name="contact_person_id" id="gd-booking-contact" class="form-control"><option value=""></option><?php foreach($contacts as $p){ ?><option value="<?php echo (int)$p["id"]; ?>"<?php echo (int)($model_info->contact_person_id??0)===(int)$p["id"]?" selected":""; ?>><?php echo $e($p["full_name"]); ?></option><?php } ?></select></div></div></div>
<div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_starts_at"); ?></label><div class="col-md-3"><input type="datetime-local" name="starts_at_local" class="form-control" required value="<?php echo $e($starts_local); ?>"></div><label class="col-md-3"><?php echo app_lang("gd_ends_at"); ?></label><div class="col-md-3"><input type="datetime-local" name="ends_at_local" class="form-control" required value="<?php echo $e($ends_local); ?>"></div></div><small class="text-muted"><?php echo app_lang("gd_unit_timezone").": ".$e($timezone); ?></small></div>
<div class="form-group gd-hold-row"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_hold_until"); ?></label><div class="col-md-3"><input type="datetime-local" name="hold_expires_at_local" class="form-control" value="<?php echo $e($hold_local); ?>"></div></div></div>
<div class="form-group"><label><?php echo app_lang("gd_resources_and_buffers"); ?></label><div class="table-responsive"><table class="table table-sm"><thead><tr><th></th><th><?php echo app_lang("gd_resource"); ?></th><th><?php echo app_lang("gd_buffer_before"); ?></th><th><?php echo app_lang("gd_buffer_after"); ?></th></tr></thead><tbody><?php foreach($resources as $r){$current=$selected[(int)$r["id"]]??null; ?><tr><td><input type="checkbox" name="resources[<?php echo (int)$r["id"]; ?>][selected]" value="1"<?php echo $current?" checked":""; ?>></td><td><?php echo $e($r["code"]." — ".$r["name"]); ?></td><td><input type="number" min="0" name="resources[<?php echo (int)$r["id"]; ?>][buffer_before_minutes]" class="form-control" value="<?php echo (int)($current->buffer_before_minutes??0); ?>"></td><td><input type="number" min="0" name="resources[<?php echo (int)$r["id"]; ?>][buffer_after_minutes]" class="form-control" value="<?php echo (int)($current->buffer_after_minutes??0); ?>"></td></tr><?php } ?></tbody></table></div></div>
<div class="form-group"><label><?php echo app_lang("gd_notes"); ?></label><textarea name="notes" class="form-control" rows="2"><?php echo $e($model_info->notes??""); ?></textarea></div><div class="form-group"><label><?php echo app_lang("gd_metadata_json"); ?></label><textarea name="metadata" class="form-control" rows="2"><?php echo $e($model_info->metadata??""); ?></textarea></div><div id="gd-booking-check-result" class="mb10"></div>
</div></div><div class="modal-footer"><button type="button" id="gd-booking-check" class="btn btn-info"><?php echo app_lang("gd_check_availability"); ?></button><button type="button" class="btn btn-default" data-bs-dismiss="modal"><?php echo app_lang("close"); ?></button><button type="submit" class="btn btn-primary"><?php echo app_lang("save"); ?></button></div><?php echo form_close(); ?>
<script>$(document).ready(function(){var f=$("#gd-booking-form"),customer=$("#gd-booking-customer"),contact=$("#gd-booking-contact");f.appForm({onSuccess:function(r){location.href='<?php echo_uri("grupo_donato/bookings/view/"); ?>'+r.id;}});customer.select2({placeholder:'-',allowClear:true,ajax:{url:'<?php echo_uri($customer_options_uri); ?>',type:'POST',dataType:'json',delay:250,data:function(p){return {q:p.term||''};},processResults:function(d){return d;}}}).on('change',function(){contact.val(null).trigger('change');});contact.select2({placeholder:'-',allowClear:true,ajax:{url:'<?php echo_uri($contact_options_uri); ?>',type:'POST',dataType:'json',delay:250,data:function(p){return {q:p.term||'',customer_account_id:customer.val()};},processResults:function(d){return d;}}});function hold(){$('.gd-hold-row').toggle(!<?php echo $id?"true":"false"; ?>&&$('#gd-booking-status').val()==='hold');}$('#gd-booking-status').on('change',hold);hold();$('#gd-booking-check').on('click',function(){$.post('<?php echo_uri($booking_check_uri); ?>',f.serialize()).done(function(r){$('#gd-booking-check-result').html(r.success&&r.data.available?'<span class="text-success"><?php echo addslashes(app_lang("gd_available")); ?></span>':'<span class="text-danger">'+(r.message||'<?php echo addslashes(app_lang("gd_unavailable")); ?>')+'</span>');});});});</script>
