<?php load_css(["assets/js/fullcalendar/fullcalendar.min.css"]);load_js(["assets/js/fullcalendar/fullcalendar.min.js","assets/js/fullcalendar/locales-all.min.js"]);$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,"UTF-8"); ?>
<div id="page-content" class="page-wrapper clearfix"><div class="card"><div class="page-title clearfix"><h4><?php echo app_lang("gd_menu_agenda"); ?></h4><div class="title-button-group">
<?php if(!empty($can_bookings_manage)) echo modal_anchor(get_uri("grupo_donato/bookings/modal"),'<i data-feather="plus-circle" class="icon-16"></i> '.app_lang("gd_add_booking"),["class"=>"btn btn-primary","title"=>app_lang("gd_add_booking")]); ?>
<?php if(!empty($can_series_manage)) echo " ".modal_anchor(get_uri("grupo_donato/booking-series/modal"),'<i data-feather="repeat" class="icon-16"></i> '.app_lang("gd_new_booking_series"),["class"=>"btn btn-default","title"=>app_lang("gd_new_booking_series")]); ?>
<?php if(!empty($can_bookings_view)) echo " ".anchor(get_uri("grupo_donato/bookings"),'<i data-feather="book-open" class="icon-16"></i> '.app_lang("gd_view_bookings"),["class"=>"btn btn-default"]); ?>
<?php if(!empty($can_series_view)) echo " ".anchor(get_uri("grupo_donato/booking-series"),'<i data-feather="layers" class="icon-16"></i> '.app_lang("gd_view_series"),["class"=>"btn btn-default"]); ?>
<span class="text-muted ml10"><?php echo app_lang("gd_unit_timezone").": ".$e($timezone); ?></span></div></div>
<div class="card-body"><div class="row mb15"><div class="col-md-7"><label><?php echo app_lang("gd_resources"); ?></label><select id="gd-calendar-resources" class="select2 form-control" multiple><?php foreach($resources as $r){ ?><option value="<?php echo (int)$r['id']; ?>"><?php echo $e($r['code']." — ".$r['name']); ?></option><?php } ?></select></div><div class="col-md-5"><label><?php echo app_lang("gd_calendar_layers"); ?></label><select id="gd-calendar-types" class="select2 form-control" multiple><option value="weekly_rule" selected><?php echo app_lang("gd_weekly_availability"); ?></option><option value="open_exception" selected><?php echo app_lang("gd_exception_type_open"); ?></option><option value="closed_exception" selected><?php echo app_lang("gd_exception_type_closed"); ?></option><option value="block" selected><?php echo app_lang("gd_resource_blocks"); ?></option><option value="booking" selected><?php echo app_lang("gd_menu_bookings"); ?></option></select></div></div><div class="mb15"><span class="badge bg-success"><?php echo app_lang("gd_available"); ?></span> <span class="badge bg-danger"><?php echo app_lang("gd_closed"); ?></span> <span class="badge bg-warning"><?php echo app_lang("gd_blocked"); ?></span> <span class="badge bg-primary"><?php echo app_lang("gd_menu_bookings"); ?></span> <small class="text-muted ml10"><?php echo app_lang("gd_calendar_buffers_hint"); ?></small></div><div id="gd-calendar"></div></div></div></div>
<script>$(document).ready(function(){var el=document.getElementById('gd-calendar');var calendar=new FullCalendar.Calendar(el,{locale:AppLanugage.locale,timeZone:'<?php echo addslashes($timezone); ?>',height:$(window).height()-250,firstDay:AppHelper.settings.firstDayOfWeek,headerToolbar:{left:'prev,next today',center:'title',right:'dayGridMonth,timeGridWeek,timeGridDay,listMonth'},events:function(info,success,failure){$.ajax({url:'<?php echo_uri("grupo_donato/calendar/events"); ?>',data:{start:info.startStr,end:info.endStr,resources:($("#gd-calendar-resources").val()||[]).join(','),types:($("#gd-calendar-types").val()||[]).join(',')},dataType:'json'}).done(success).fail(failure);},loading:function(v){if(v){appLoader.show();}else{appLoader.hide();feather.replace();}}});calendar.render();$("#gd-calendar-resources,#gd-calendar-types").select2().on('change',function(){calendar.refetchEvents();});});</script>
