<?php $e = static fn($value) => htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8"); ?>
<div id="page-content" class="page-wrapper clearfix">
    <div class="page-title clearfix"><h4><?php echo $e($person->full_name); ?></h4><div class="title-button-group"><?php if ($can_manage) echo modal_anchor(get_uri("grupo_donato/people/modal_form"), "<i data-feather='edit' class='icon-16'></i> " . app_lang("edit"), ["class" => "btn btn-default", "title" => app_lang("edit"), "data-post-id" => $person->id]); ?> <?php echo anchor(get_uri("grupo_donato/people"), app_lang("back"), ["class" => "btn btn-default"]); ?></div></div>
    <div class="row"><div class="col-md-7"><div class="card"><div class="card-header"><h4><?php echo app_lang("gd_main_data"); ?></h4></div><div class="card-body">
        <div class="row"><div class="col-md-6"><strong><?php echo app_lang("gd_preferred_name"); ?></strong><br><?php echo $e($person->preferred_name); ?></div><div class="col-md-6"><strong><?php echo app_lang("gd_status"); ?></strong><br><?php echo app_lang("gd_status_" . $person->status); ?></div></div><hr>
        <div class="row"><div class="col-md-6"><strong><?php echo app_lang("gd_birth_date"); ?></strong><br><?php echo $person->birth_date ? format_to_date($person->birth_date) : ""; ?></div><div class="col-md-6"><strong><?php echo app_lang("gd_rise_links"); ?></strong><br><?php echo $person->rise_user_id ? "User #" . (int) $person->rise_user_id : ""; ?> <?php echo $person->rise_contact_id ? "Contact #" . (int) $person->rise_contact_id : app_lang("gd_not_linked"); ?></div></div><hr>
        <strong><?php echo app_lang("note"); ?></strong><br><?php echo nl2br($e($person->notes)); ?>
    </div></div></div><div class="col-md-5">
        <div class="card"><div class="card-header"><h4><?php echo app_lang("gd_possible_duplicates"); ?></h4></div><div class="card-body"><?php if (!$duplicates) { ?><span class="text-muted"><?php echo app_lang("gd_no_possible_duplicates"); ?></span><?php } else { foreach ($duplicates as $duplicate) { ?><div class="mb10"><strong><?php echo $e($duplicate["display_summary"]); ?></strong> — <?php echo app_lang("gd_confidence_" . $duplicate["confidence"]); ?><br><small><?php echo $e(implode(", ", $duplicate["matched_fields"])); ?></small></div><?php }} ?></div></div>
        <?php if ($can_audit) { ?><div class="card"><div class="card-header"><h4><?php echo app_lang("gd_recent_audit"); ?></h4></div><div class="card-body"><?php if (!$audits) echo '<span class="text-muted">' . app_lang("gd_no_audit_events") . '</span>'; foreach ($audits as $event) { ?><div class="mb10"><strong><?php echo $e($event->action); ?></strong><br><small><?php echo $event->created_at ? format_to_datetime($event->created_at) : ""; ?></small></div><?php } ?></div></div><?php } ?>
    </div></div>
    <div class="card"><div class="page-title clearfix"><h4><?php echo app_lang("gd_contact_methods"); ?></h4><?php if ($can_contacts) { ?><div class="title-button-group"><?php echo modal_anchor(get_uri("grupo_donato/contacts/modal_form"), "<i data-feather='plus-circle' class='icon-16'></i> " . app_lang("gd_add_contact"), ["class" => "btn btn-default", "title" => app_lang("gd_add_contact"), "data-post-person_id" => $person->id]); ?></div><?php } ?></div><div class="table-responsive"><table id="gd-contact-methods-table" class="display" width="100%"></table></div></div>
    <div class="card"><div class="page-title clearfix"><h4><?php echo app_lang("gd_linked_accounts"); ?></h4><?php if ($can_relations) { ?><div class="title-button-group"><?php echo modal_anchor(get_uri("grupo_donato/account-people/modal_form"), "<i data-feather='plus-circle' class='icon-16'></i> " . app_lang("gd_add_relation"), ["class" => "btn btn-default", "title" => app_lang("gd_add_relation"), "data-post-person_id" => $person->id]); ?></div><?php } ?></div><div class="table-responsive"><table id="gd-person-accounts-table" class="display" width="100%"></table></div></div>
</div>
<script type="text/javascript">
$(document).ready(function () {
    $("#gd-contact-methods-table").appTable({source: '<?php echo_uri("grupo_donato/contacts/list_data"); ?>', serverSide: true, filterParams: {person_id: "<?php echo (int) $person->id; ?>"}, columns: [
        {title: '<?php echo app_lang("gd_contact_type"); ?>'}, {title: '<?php echo app_lang("gd_label"); ?>'}, {title: '<?php echo app_lang("gd_contact_value"); ?>'}, {title: '<?php echo app_lang("gd_primary"); ?>'}, {title: '<?php echo app_lang("gd_status"); ?>'}, {title: '<i data-feather="menu" class="icon-16"></i>', "class": "text-center option w80"}
    ]});
    $("#gd-person-accounts-table").appTable({source: '<?php echo_uri("grupo_donato/account-people/list_data"); ?>', serverSide: true, filterParams: {person_id: "<?php echo (int) $person->id; ?>"}, columns: [
        {title: '<?php echo app_lang("gd_customer_account"); ?>'}, {title: '<?php echo app_lang("gd_role"); ?>'}, {title: '<?php echo app_lang("gd_primary"); ?>'}, {title: '<?php echo app_lang("gd_financial_responsible"); ?>'}, {title: '<?php echo app_lang("gd_status"); ?>'}, {title: '<i data-feather="menu" class="icon-16"></i>', "class": "text-center option w80"}
    ]});
});
</script>
