<?php $e = static fn($v) => htmlspecialchars((string) $v, ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8"); ?>
<?php echo form_open(get_uri("grupo_donato/court-rentals/save-monthly"), ["id" => "gd-court-monthly-form", "class" => "general-form", "role" => "form"]); ?>
<input type="hidden" name="rental_type" value="recurring">
<div class="modal-body clearfix"><div class="container-fluid">
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_title"); ?></label><div class="col-md-9"><input name="title" class="form-control" maxlength="180" required></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_customer"); ?></label><div class="col-md-3"><select name="customer_account_id" id="gd-crm-customer" class="form-control" required><option value=""></option><?php foreach ($accounts as $a) { ?><option value="<?php echo (int) $a["id"]; ?>"><?php echo $e($a["display_name"]); ?></option><?php } ?></select></div><label class="col-md-3"><?php echo app_lang("gd_contact"); ?></label><div class="col-md-3"><select name="contact_person_id" id="gd-crm-contact" class="form-control"><option value=""></option></select></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_frequency"); ?></label><div class="col-md-3"><select name="frequency" id="gd-crm-frequency" class="form-control"><?php foreach ($frequencies as $fq) { ?><option value="<?php echo $e($fq); ?>"><?php echo app_lang("gd_booking_series_frequency_" . $fq); ?></option><?php } ?></select></div><label class="col-md-3"><?php echo app_lang("gd_interval"); ?></label><div class="col-md-3"><input type="number" min="1" name="interval_value" class="form-control" value="1"></div></div></div>
    <div class="form-group gd-crm-weekly"><label><?php echo app_lang("gd_weekdays"); ?></label><div><?php for ($d = 1; $d <= 7; $d++) { ?><label class="mr10"><input type="checkbox" name="weekdays[]" value="<?php echo $d; ?>"> <?php echo app_lang("gd_weekday_short_" . $d); ?></label><?php } ?></div></div>
    <div class="form-group gd-crm-monthly" style="display:none"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_monthly_day"); ?></label><div class="col-md-3"><input type="number" min="1" max="31" name="monthly_day" class="form-control"></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_starts_at"); ?> (<?php echo app_lang("gd_local_time"); ?>)</label><div class="col-md-3"><input type="time" name="local_start_time" class="form-control" required></div><div class="col-md-3"><input type="time" name="local_end_time" class="form-control" required></div></div><small class="text-muted"><?php echo app_lang("gd_unit_timezone") . ": " . $e($timezone); ?></small></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_starts_on"); ?></label><div class="col-md-3"><input type="date" name="starts_on" class="form-control" required></div><label class="col-md-3"><?php echo app_lang("gd_ends_mode"); ?></label><div class="col-md-3"><select name="ends_mode" id="gd-crm-ends" class="form-control"><?php foreach ($ends_modes as $m) { ?><option value="<?php echo $e($m); ?>"><?php echo app_lang("gd_booking_series_ends_mode_" . $m); ?></option><?php } ?></select></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_ends_on"); ?></label><div class="col-md-3"><input type="date" name="ends_on" class="form-control"></div><label class="col-md-3"><?php echo app_lang("gd_max_occurrences"); ?></label><div class="col-md-3"><input type="number" min="1" name="max_occurrences" class="form-control"></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_conflict_policy"); ?></label><div class="col-md-3"><select name="conflict_policy" class="form-control"><?php foreach ($conflict_policies as $p) { ?><option value="<?php echo $e($p); ?>"><?php echo app_lang("gd_booking_series_conflict_" . $p); ?></option><?php } ?></select></div><label class="col-md-3"><?php echo app_lang("gd_status"); ?></label><div class="col-md-3"><select name="default_booking_status" class="form-control"><?php foreach ($default_statuses as $s) { ?><option value="<?php echo $e($s); ?>"><?php echo app_lang("gd_booking_status_" . $s); ?></option><?php } ?></select></div></div></div>
    <input type="hidden" name="generation_horizon_days" value="90">
    <div class="form-group"><label><?php echo app_lang("gd_resources_and_buffers"); ?></label><div class="table-responsive"><table class="table table-sm"><thead><tr><th></th><th><?php echo app_lang("gd_resource"); ?></th><th><?php echo app_lang("gd_buffer_before"); ?></th><th><?php echo app_lang("gd_buffer_after"); ?></th></tr></thead><tbody><?php foreach ($resources as $r) { ?><tr><td><input type="checkbox" name="resources[<?php echo (int) $r["id"]; ?>][selected]" value="1"></td><td><?php echo $e($r["code"] . " — " . $r["name"]); ?></td><td><input type="number" min="0" name="resources[<?php echo (int) $r["id"]; ?>][buffer_before_minutes]" class="form-control" value="0"></td><td><input type="number" min="0" name="resources[<?php echo (int) $r["id"]; ?>][buffer_after_minutes]" class="form-control" value="0"></td></tr><?php } ?></tbody></table></div><button type="button" id="gd-crm-preview" class="btn btn-info btn-sm"><?php echo app_lang("gd_preview_occurrences"); ?></button><div id="gd-crm-preview-result" class="mt5"></div></div>
    <hr><h6><?php echo app_lang("gd_commercial_terms"); ?></h6>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_preferred_due_day"); ?></label><div class="col-md-3"><input type="number" min="1" max="31" name="preferred_due_day" class="form-control"></div><label class="col-md-3"><?php echo app_lang("gd_product"); ?> / <?php echo app_lang("gd_price_list"); ?></label><div class="col-md-3"><input type="number" name="product_id" id="gd-crm-product" class="form-control" placeholder="ID"> <input type="number" name="price_list_id" id="gd-crm-price-list" class="form-control mt5" placeholder="ID"></div></div></div>
    <div class="form-group"><div class="row"><div class="col-md-3"><button type="button" id="gd-crm-resolve" class="btn btn-info btn-block"><?php echo app_lang("gd_resolve_price"); ?></button></div><div class="col-md-9"><span id="gd-crm-price-info"></span></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_list_amount"); ?></label><div class="col-md-3"><input name="list_amount" id="gd-crm-list" class="form-control" placeholder="0.00"></div><label class="col-md-3"><?php echo app_lang("gd_negotiated_amount"); ?></label><div class="col-md-3"><input name="negotiated_amount" class="form-control" placeholder="0.00"></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_discount_amount"); ?></label><div class="col-md-3"><input name="discount_amount" class="form-control" placeholder="0.00"></div><label class="col-md-3"><?php echo app_lang("gd_discount_reason"); ?></label><div class="col-md-3"><input name="discount_reason" class="form-control" maxlength="255"></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_effective_from"); ?></label><div class="col-md-3"><input type="date" name="effective_from" class="form-control"></div><label class="col-md-3"><?php echo app_lang("gd_effective_until"); ?></label><div class="col-md-3"><input type="date" name="effective_until" class="form-control"></div></div></div>
    <div class="form-group"><label><?php echo app_lang("gd_commercial_notes"); ?></label><textarea name="commercial_notes" class="form-control" rows="2"></textarea></div>
    <div class="form-group"><div class="row"><div class="col-md-6"><label><input type="checkbox" name="activate" value="1"> <?php echo app_lang("gd_activate_on_create"); ?></label></div><div class="col-md-6"><input name="justification" class="form-control" placeholder="<?php echo app_lang("gd_justification"); ?>"></div></div></div>
</div></div>
<div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal"><?php echo app_lang("close"); ?></button><button type="submit" class="btn btn-primary"><?php echo app_lang("save"); ?></button></div>
<?php echo form_close(); ?>
<script>
$(document).ready(function(){
    var f=$("#gd-court-monthly-form"),customer=$("#gd-crm-customer"),contact=$("#gd-crm-contact");
    f.appForm({onSuccess:function(r){location.href='<?php echo_uri("grupo_donato/court-rentals/view/"); ?>'+r.id;}});
    customer.select2({placeholder:'-',allowClear:true,ajax:{url:'<?php echo_uri("grupo_donato/court-rentals/customer-options"); ?>',type:'POST',dataType:'json',delay:250,data:function(p){return {q:p.term||''};},processResults:function(d){return d;}}}).on('change',function(){contact.val(null).trigger('change');});
    contact.select2({placeholder:'-',allowClear:true,ajax:{url:'<?php echo_uri("grupo_donato/court-rentals/contact-options"); ?>',type:'POST',dataType:'json',delay:250,data:function(p){return {q:p.term||'',customer_account_id:customer.val()};},processResults:function(d){return d;}}});
    function freq(){var v=$('#gd-crm-frequency').val();$('.gd-crm-weekly').toggle(v==='weekly');$('.gd-crm-monthly').toggle(v==='monthly');}
    $('#gd-crm-frequency').on('change',freq);freq();
    $('#gd-crm-resolve').on('click',function(){var resource=$('input[name^="resources"][name$="[selected]"]:checked').first().attr('name');var rid=resource?resource.replace(/\D+/g,''):'';$.post('<?php echo_uri("grupo_donato/court-rentals/resolve-price"); ?>',{product_id:$('#gd-crm-product').val(),price_list_id:$('#gd-crm-price-list').val(),resource_id:rid,quantity:'1'}).done(function(r){if(r.success&&r.data&&r.data.found){$('#gd-crm-list').val(r.data.amount);$('#gd-crm-price-info').html('<span class="text-success"><?php echo addslashes(app_lang("gd_suggested_price")); ?>: '+r.data.currency+' '+r.data.amount+' ('+r.data.matched_scope+')</span>');}else{$('#gd-crm-price-info').html('<span class="text-warning"><?php echo addslashes(app_lang("gd_no_price_suggestion")); ?></span>');}});});
    $('#gd-crm-preview').on('click',function(){$.post('<?php echo_uri("grupo_donato/court-rentals/preview"); ?>',f.serialize()).done(function(r){if(r.success){$('#gd-crm-preview-result').html('<span class="text-info">'+(r.data?r.data.length:0)+' <?php echo addslashes(app_lang("gd_next_occurrence")); ?></span>');}else{$('#gd-crm-preview-result').html('<span class="text-danger">'+(r.message||'')+'</span>');}});});
});
</script>
