<?php $e = static fn($v) => htmlspecialchars((string) $v, ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8"); ?>
<?php echo form_open(get_uri("grupo_donato/court-rentals/save-single"), ["id" => "gd-court-single-form", "class" => "general-form", "role" => "form"]); ?>
<input type="hidden" name="rental_type" value="single">
<div class="modal-body clearfix"><div class="container-fluid">
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_title"); ?></label><div class="col-md-9"><input name="title" class="form-control" maxlength="180" required></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_customer"); ?></label><div class="col-md-3"><select name="customer_account_id" id="gd-cr-customer" class="form-control" required><option value=""></option><?php foreach ($accounts as $a) { ?><option value="<?php echo (int) $a["id"]; ?>"><?php echo $e($a["display_name"]); ?></option><?php } ?></select></div><label class="col-md-3"><?php echo app_lang("gd_contact"); ?></label><div class="col-md-3"><select name="contact_person_id" id="gd-cr-contact" class="form-control"><option value=""></option></select></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_starts_at"); ?></label><div class="col-md-3"><input type="datetime-local" name="starts_at_local" class="form-control" required></div><label class="col-md-3"><?php echo app_lang("gd_ends_at"); ?></label><div class="col-md-3"><input type="datetime-local" name="ends_at_local" class="form-control" required></div></div><small class="text-muted"><?php echo app_lang("gd_unit_timezone") . ": " . $e($timezone); ?></small></div>
    <div class="form-group"><label><?php echo app_lang("gd_resources_and_buffers"); ?></label><div class="table-responsive"><table class="table table-sm"><thead><tr><th></th><th><?php echo app_lang("gd_resource"); ?></th><th><?php echo app_lang("gd_buffer_before"); ?></th><th><?php echo app_lang("gd_buffer_after"); ?></th></tr></thead><tbody><?php foreach ($resources as $r) { ?><tr><td><input type="checkbox" name="resources[<?php echo (int) $r["id"]; ?>][selected]" value="1"></td><td><?php echo $e($r["code"] . " — " . $r["name"]); ?></td><td><input type="number" min="0" name="resources[<?php echo (int) $r["id"]; ?>][buffer_before_minutes]" class="form-control" value="0"></td><td><input type="number" min="0" name="resources[<?php echo (int) $r["id"]; ?>][buffer_after_minutes]" class="form-control" value="0"></td></tr><?php } ?></tbody></table></div></div>
    <hr><h6><?php echo app_lang("gd_commercial_terms"); ?></h6>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_product"); ?> / <?php echo app_lang("gd_price_list"); ?></label><div class="col-md-3"><input type="number" name="product_id" id="gd-cr-product" class="form-control" placeholder="ID"></div><div class="col-md-3"><input type="number" name="price_list_id" id="gd-cr-price-list" class="form-control" placeholder="ID"></div><div class="col-md-3"><button type="button" id="gd-cr-resolve" class="btn btn-info btn-block"><?php echo app_lang("gd_resolve_price"); ?></button></div></div><div id="gd-cr-price-info" class="mt5"></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_list_amount"); ?></label><div class="col-md-3"><input name="list_amount" id="gd-cr-list" class="form-control" placeholder="0.00"></div><label class="col-md-3"><?php echo app_lang("gd_negotiated_amount"); ?></label><div class="col-md-3"><input name="negotiated_amount" class="form-control" placeholder="0.00"></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_discount_amount"); ?></label><div class="col-md-3"><input name="discount_amount" class="form-control" placeholder="0.00"></div><label class="col-md-3"><?php echo app_lang("gd_discount_reason"); ?></label><div class="col-md-3"><input name="discount_reason" class="form-control" maxlength="255"></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_effective_from"); ?></label><div class="col-md-3"><input type="date" name="effective_from" class="form-control"></div><label class="col-md-3"><?php echo app_lang("gd_effective_until"); ?></label><div class="col-md-3"><input type="date" name="effective_until" class="form-control"></div></div></div>
    <div class="form-group"><label><?php echo app_lang("gd_commercial_notes"); ?></label><textarea name="commercial_notes" class="form-control" rows="2"></textarea></div>
    <div class="form-group"><div class="row"><div class="col-md-6"><label><input type="checkbox" name="activate" value="1"> <?php echo app_lang("gd_activate_on_create"); ?></label></div><div class="col-md-6"><input name="justification" class="form-control" placeholder="<?php echo app_lang("gd_justification"); ?>"></div></div></div>
    <div id="gd-cr-check-result" class="mb10"></div>
</div></div>
<div class="modal-footer"><button type="button" id="gd-cr-check" class="btn btn-info"><?php echo app_lang("gd_check_availability"); ?></button><button type="button" class="btn btn-default" data-bs-dismiss="modal"><?php echo app_lang("close"); ?></button><button type="submit" class="btn btn-primary"><?php echo app_lang("save"); ?></button></div>
<?php echo form_close(); ?>
<script>
$(document).ready(function(){
    var f=$("#gd-court-single-form"),customer=$("#gd-cr-customer"),contact=$("#gd-cr-contact");
    f.appForm({onSuccess:function(r){location.href='<?php echo_uri("grupo_donato/court-rentals/view/"); ?>'+r.id;}});
    customer.select2({placeholder:'-',allowClear:true,ajax:{url:'<?php echo_uri("grupo_donato/court-rentals/customer-options"); ?>',type:'POST',dataType:'json',delay:250,data:function(p){return {q:p.term||''};},processResults:function(d){return d;}}}).on('change',function(){contact.val(null).trigger('change');});
    contact.select2({placeholder:'-',allowClear:true,ajax:{url:'<?php echo_uri("grupo_donato/court-rentals/contact-options"); ?>',type:'POST',dataType:'json',delay:250,data:function(p){return {q:p.term||'',customer_account_id:customer.val()};},processResults:function(d){return d;}}});
    $('#gd-cr-resolve').on('click',function(){var resource=$('input[name^="resources"][name$="[selected]"]:checked').first().attr('name');var rid=resource?resource.replace(/\D+/g,''):'';$.post('<?php echo_uri("grupo_donato/court-rentals/resolve-price"); ?>',{product_id:$('#gd-cr-product').val(),price_list_id:$('#gd-cr-price-list').val(),resource_id:rid,quantity:'1'}).done(function(r){if(r.success&&r.data&&r.data.found){$('#gd-cr-list').val(r.data.amount);$('#gd-cr-price-info').html('<span class="text-success"><?php echo addslashes(app_lang("gd_suggested_price")); ?>: '+r.data.currency+' '+r.data.amount+' ('+r.data.matched_scope+')</span>');}else{$('#gd-cr-price-info').html('<span class="text-warning"><?php echo addslashes(app_lang("gd_no_price_suggestion")); ?></span>');}});});
    $('#gd-cr-check').on('click',function(){$.post('<?php echo_uri("grupo_donato/court-rentals/check-availability"); ?>',f.serialize()).done(function(r){$('#gd-cr-check-result').html(r.success&&r.data.available?'<span class="text-success"><?php echo addslashes(app_lang("gd_available")); ?></span>':'<span class="text-danger">'+(r.message||'<?php echo addslashes(app_lang("gd_unavailable")); ?>')+'</span>');});});
});
</script>
