<?php
$e = static fn($value) => htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8");
$id = (int) ($model_info->id ?? 0);
$selected_resources = [];
foreach (($model_info->resources ?? []) as $resource) { $selected_resources[(int) $resource->resource_id] = $resource; }
$selected_days = json_decode((string) ($model_info->weekdays ?? "[]"), true) ?: [];
$scope = $scope ?? "";
$action = $scope === "this_and_future" ? "grupo_donato/booking-series/update-this-and-future" : ($id ? "grupo_donato/booking-series/update-entire" : "grupo_donato/booking-series/save");
$days = [1 => "Seg", 2 => "Ter", 3 => "Qua", 4 => "Qui", 5 => "Sex", 6 => "Sáb", 7 => "Dom"];
?>
<?php echo form_open(get_uri($action), ["id" => "gd-series-form", "class" => "general-form", "role" => "form"]); ?>
<div class="modal-body clearfix"><div class="container-fluid">
    <input type="hidden" name="id" value="<?php echo $id; ?>">
    <input type="hidden" name="lock_version" value="<?php echo (int) ($model_info->lock_version ?? 0); ?>">
    <input type="hidden" name="from_local_date" value="<?php echo $e($from_local_date ?? ""); ?>">
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_type"); ?></label><div class="col-md-3"><select name="booking_type" class="form-control"><?php foreach ($types as $value) { ?><option value="<?php echo $e($value); ?>"<?php echo ($model_info->booking_type ?? "internal") === $value ? " selected" : ""; ?>><?php echo app_lang("gd_booking_type_" . $value); ?></option><?php } ?></select></div><label class="col-md-3"><?php echo app_lang("gd_title"); ?></label><div class="col-md-3"><input name="title" class="form-control" maxlength="180" required value="<?php echo $e($model_info->title ?? ""); ?>"></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_customer"); ?></label><div class="col-md-3"><select name="customer_account_id" class="form-control"><option value=""></option><?php foreach ($accounts as $account) { ?><option value="<?php echo (int) $account["id"]; ?>"<?php echo (int) ($model_info->customer_account_id ?? 0) === (int) $account["id"] ? " selected" : ""; ?>><?php echo $e($account["display_name"]); ?></option><?php } ?></select></div><label class="col-md-3"><?php echo app_lang("gd_contact"); ?></label><div class="col-md-3"><select name="contact_person_id" class="form-control"><option value=""></option><?php foreach ($contacts as $contact) { ?><option value="<?php echo (int) $contact["id"]; ?>"<?php echo (int) ($model_info->contact_person_id ?? 0) === (int) $contact["id"] ? " selected" : ""; ?>><?php echo $e($contact["full_name"]); ?></option><?php } ?></select></div></div></div>
    <hr><div class="form-group"><div class="row"><label class="col-md-2"><?php echo app_lang("gd_frequency"); ?></label><div class="col-md-2"><select name="frequency" id="gd-series-frequency" class="form-control"><?php foreach ($frequencies as $value) { ?><option value="<?php echo $value; ?>"<?php echo ($model_info->frequency ?? "weekly") === $value ? " selected" : ""; ?>><?php echo app_lang("gd_booking_series_frequency_" . $value); ?></option><?php } ?></select></div><label class="col-md-2"><?php echo app_lang("gd_interval"); ?></label><div class="col-md-2"><input type="number" min="1" max="365" name="interval_value" class="form-control" value="<?php echo (int) ($model_info->interval_value ?? 1); ?>"></div><label class="col-md-2 gd-monthly-row"><?php echo app_lang("gd_monthly_day"); ?></label><div class="col-md-2 gd-monthly-row"><input type="number" min="1" max="31" name="monthly_day" class="form-control" value="<?php echo $e($model_info->monthly_day ?? date("j")); ?>"></div></div></div>
    <div class="form-group gd-weekly-row"><label><?php echo app_lang("gd_weekdays"); ?></label><div><?php foreach ($days as $value => $label) { ?><label class="checkbox-inline mr15"><input type="checkbox" name="weekdays[]" value="<?php echo $value; ?>"<?php echo in_array($value, $selected_days, true) ? " checked" : ""; ?>> <?php echo $label; ?></label><?php } ?></div></div>
    <div class="form-group"><div class="row"><label class="col-md-2"><?php echo app_lang("gd_local_start_time"); ?></label><div class="col-md-2"><input type="time" name="local_start_time" class="form-control" required value="<?php echo $e(substr((string) ($model_info->local_start_time ?? "09:00"), 0, 5)); ?>"></div><label class="col-md-2"><?php echo app_lang("gd_local_end_time"); ?></label><div class="col-md-2"><input type="time" name="local_end_time" class="form-control" required value="<?php echo $e(substr((string) ($model_info->local_end_time ?? "10:00"), 0, 5)); ?>"></div><label class="col-md-2"><?php echo app_lang("gd_starts_on"); ?></label><div class="col-md-2"><input type="date" name="starts_on" class="form-control" required value="<?php echo $e($scope === "this_and_future" ? ($from_local_date ?? "") : ($model_info->starts_on ?? date("Y-m-d"))); ?>"></div></div><small class="text-muted"><?php echo app_lang("gd_unit_timezone") . ": " . $e($timezone) . ". " . app_lang("gd_booking_series_overnight_hint"); ?></small></div>
    <div class="form-group"><div class="row"><label class="col-md-2"><?php echo app_lang("gd_ends_mode"); ?></label><div class="col-md-2"><select name="ends_mode" id="gd-series-ends-mode" class="form-control"><?php foreach ($ends_modes as $value) { ?><option value="<?php echo $value; ?>"<?php echo ($model_info->ends_mode ?? "count") === $value ? " selected" : ""; ?>><?php echo app_lang("gd_booking_series_ends_" . $value); ?></option><?php } ?></select></div><label class="col-md-2 gd-until-row"><?php echo app_lang("gd_ends_on"); ?></label><div class="col-md-2 gd-until-row"><input type="date" name="ends_on" class="form-control" value="<?php echo $e($model_info->ends_on ?? ""); ?>"></div><label class="col-md-2 gd-count-row"><?php echo app_lang("gd_max_occurrences"); ?></label><div class="col-md-2 gd-count-row"><input type="number" min="1" max="366" name="max_occurrences" class="form-control" value="<?php echo $e($model_info->max_occurrences ?? 10); ?>"></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_default_booking_status"); ?></label><div class="col-md-3"><select name="default_booking_status" class="form-control"><?php foreach ($default_statuses as $value) { ?><option value="<?php echo $value; ?>"<?php echo ($model_info->default_booking_status ?? "pending_confirmation") === $value ? " selected" : ""; ?>><?php echo app_lang("gd_booking_status_" . $value); ?></option><?php } ?></select></div><label class="col-md-3"><?php echo app_lang("gd_conflict_policy"); ?></label><div class="col-md-3"><select name="conflict_policy" class="form-control"><?php foreach ($conflict_policies as $value) { ?><option value="<?php echo $value; ?>"<?php echo ($model_info->conflict_policy ?? "reject_series") === $value ? " selected" : ""; ?>><?php echo app_lang("gd_booking_series_conflict_" . $value); ?></option><?php } ?></select></div></div></div>
    <div class="form-group"><div class="row"><label class="col-md-3"><?php echo app_lang("gd_generation_horizon_days"); ?></label><div class="col-md-3"><input type="number" min="1" max="730" name="generation_horizon_days" class="form-control" value="<?php echo (int) ($model_info->generation_horizon_days ?? 90); ?>"></div></div></div>
    <div class="form-group"><label><?php echo app_lang("gd_resources_and_buffers"); ?></label><div class="table-responsive"><table class="table table-sm"><thead><tr><th></th><th><?php echo app_lang("gd_resource"); ?></th><th><?php echo app_lang("gd_buffer_before"); ?></th><th><?php echo app_lang("gd_buffer_after"); ?></th></tr></thead><tbody><?php foreach ($resources as $resource) { $current = $selected_resources[(int) $resource["id"]] ?? null; ?><tr><td><input type="checkbox" name="resources[<?php echo (int) $resource["id"]; ?>][selected]" value="1"<?php echo $current ? " checked" : ""; ?>></td><td><?php echo $e($resource["code"] . " — " . $resource["name"]); ?></td><td><input type="number" min="0" name="resources[<?php echo (int) $resource["id"]; ?>][buffer_before_minutes]" class="form-control" value="<?php echo (int) ($current->buffer_before_minutes ?? 0); ?>"></td><td><input type="number" min="0" name="resources[<?php echo (int) $resource["id"]; ?>][buffer_after_minutes]" class="form-control" value="<?php echo (int) ($current->buffer_after_minutes ?? 0); ?>"></td></tr><?php } ?></tbody></table></div></div>
    <div class="form-group"><label><?php echo app_lang("gd_notes"); ?></label><textarea name="notes" class="form-control" rows="2"><?php echo $e($model_info->notes ?? ""); ?></textarea></div>
    <div class="form-group"><label><?php echo app_lang("gd_metadata_json"); ?></label><textarea name="metadata" class="form-control" rows="2"><?php echo $e($model_info->metadata ?? ""); ?></textarea></div>
    <div id="gd-series-preview-result"></div>
</div></div>
<div class="modal-footer"><button type="button" id="gd-series-preview" class="btn btn-info"><?php echo app_lang("gd_preview_occurrences"); ?></button><button type="button" class="btn btn-default" data-bs-dismiss="modal"><?php echo app_lang("close"); ?></button><button type="submit" class="btn btn-primary"><?php echo app_lang("save"); ?></button></div>
<?php echo form_close(); ?>
<script>
$(document).ready(function(){
    var form=$("#gd-series-form");
    form.appForm({onSuccess:function(response){location.href='<?php echo_uri("grupo_donato/booking-series/view/"); ?>'+(response.new_series_id||response.id);}});
    function toggle(){var f=$("#gd-series-frequency").val(),e=$("#gd-series-ends-mode").val();$(".gd-weekly-row").toggle(f==="weekly");$(".gd-monthly-row").toggle(f==="monthly");$(".gd-until-row").toggle(e==="until_date");$(".gd-count-row").toggle(e==="count");}
    $("#gd-series-frequency,#gd-series-ends-mode").on("change",toggle);toggle();
    $("#gd-series-preview").on("click",function(){$.post('<?php echo_uri("grupo_donato/booking-series/preview"); ?>',form.serialize()).done(function(response){if(!response.success){appAlert.error(response.message);return;}var rows=response.data||[],html='<div class="table-responsive"><table class="table table-sm"><tr><th>Data</th><th>UTC</th><th>Status</th></tr>';$.each(rows.slice(0,100),function(_,row){html+='<tr><td>'+row.local_date+'</td><td>'+row.starts_at_utc+' — '+row.ends_at_utc+'</td><td>'+(row.available?'✓':'⚠')+'</td></tr>';});html+='</table></div>';$("#gd-series-preview-result").html(html);});});
});
</script>
