<?php $e = static fn($value) => htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8"); ?>
<div id="page-content" class="page-wrapper clearfix">
    <div class="page-title clearfix"><h4><?php echo $e($series->series_number . " — " . $series->title); ?></h4><div class="title-button-group"><?php if ($can_manage && in_array($series->status, ["active", "paused"], true)) { echo modal_anchor(get_uri("grupo_donato/booking-series/modal"), "<i data-feather='edit' class='icon-16'></i> " . app_lang("gd_update_entire_series"), ["class" => "btn btn-default", "data-post-id" => $series->id, "title" => app_lang("gd_update_entire_series")]); } echo anchor(get_uri("grupo_donato/booking-series"), app_lang("back"), ["class" => "btn btn-default"]); ?></div></div>
    <div class="row"><div class="col-md-7">
        <div class="card"><div class="card-header"><h4><?php echo app_lang("gd_booking_series"); ?></h4></div><div class="card-body">
            <div class="row"><div class="col-md-4"><strong><?php echo app_lang("gd_status"); ?></strong><br><?php echo app_lang("gd_booking_series_status_" . $series->status); ?></div><div class="col-md-4"><strong><?php echo app_lang("gd_frequency"); ?></strong><br><?php echo app_lang("gd_booking_series_frequency_" . $series->frequency); ?></div><div class="col-md-4"><strong><?php echo app_lang("gd_lock_version"); ?></strong><br><?php echo (int) $series->lock_version; ?></div></div><hr>
            <div class="row"><div class="col-md-4"><strong><?php echo app_lang("gd_starts_on"); ?></strong><br><?php echo $e($series->starts_on); ?></div><div class="col-md-4"><strong><?php echo app_lang("gd_ends_mode"); ?></strong><br><?php echo app_lang("gd_booking_series_ends_" . $series->ends_mode); ?></div><div class="col-md-4"><strong><?php echo app_lang("gd_customer"); ?></strong><br><?php echo $e($series->customer_name ?? "-"); ?></div></div><hr>
            <strong><?php echo app_lang("gd_resources_and_buffers"); ?></strong><table class="table table-sm"><tbody><?php foreach ($series->resources as $resource) { ?><tr><td><?php echo $e($resource->resource_code . " — " . $resource->resource_name); ?></td><td><?php echo (int) $resource->buffer_before_minutes . " / " . (int) $resource->buffer_after_minutes . " min"; ?></td></tr><?php } ?></tbody></table>
        </div></div>
        <div class="card"><div class="card-header"><h4><?php echo app_lang("gd_generated_occurrences"); ?></h4></div><div class="card-body table-responsive"><table class="table table-sm"><thead><tr><th><?php echo app_lang("gd_booking_number"); ?></th><th><?php echo app_lang("gd_starts_on"); ?></th><th><?php echo app_lang("gd_status"); ?></th><th></th></tr></thead><tbody><?php foreach ($series->occurrences as $occurrence) { ?><tr><td><?php echo anchor(get_uri("grupo_donato/bookings/view/" . $occurrence->id), $e($occurrence->booking_number)); ?><?php echo $occurrence->is_series_exception ? " <span class='badge bg-warning'>*</span>" : ""; ?></td><td><?php echo $e($occurrence->series_local_date); ?></td><td><?php echo app_lang("gd_booking_status_" . $occurrence->status); ?></td><td><?php if ($can_manage && in_array($occurrence->status, ["pending_confirmation", "confirmed"], true) && $occurrence->starts_at_utc > gmdate("Y-m-d H:i:s")) { echo modal_anchor(get_uri("grupo_donato/booking-series/occurrence-modal"), "<i data-feather='edit' class='icon-16'></i>", ["data-post-id" => $occurrence->id, "title" => app_lang("gd_update_single_occurrence")]); echo modal_anchor(get_uri("grupo_donato/booking-series/modal"), "<i data-feather='git-branch' class='icon-16'></i>", ["data-post-id" => $series->id, "data-post-scope" => "this_and_future", "data-post-from_local_date" => $occurrence->series_local_date, "title" => app_lang("gd_update_this_and_future")]); } if ($can_status && in_array($occurrence->status, ["pending_confirmation", "confirmed"], true)) { ?><button class="btn btn-link gd-cancel-occurrence" data-id="<?php echo (int) $occurrence->id; ?>"><i data-feather="x" class="icon-16"></i></button><?php } ?></td></tr><?php } ?></tbody></table></div></div>
    </div><div class="col-md-5">
        <?php if ($can_status || $can_manage) { ?><div class="card"><div class="card-header"><h4><?php echo app_lang("gd_actions"); ?></h4></div><div class="card-body" id="gd-series-actions"><?php if ($can_manage && $series->status === "active") { ?><button data-action="generate" class="btn btn-default mr5"><?php echo app_lang("gd_generate_occurrences"); ?></button><?php } if ($can_status && $series->status === "active") { ?><button data-action="pause" class="btn btn-warning mr5"><?php echo app_lang("gd_pause_series"); ?></button><?php } if ($can_status && $series->status === "paused") { ?><button data-action="resume" class="btn btn-success mr5"><?php echo app_lang("gd_resume_series"); ?></button><?php } if ($can_status && in_array($series->status, ["active", "paused"], true)) { ?><button data-action="complete" data-reason="1" class="btn btn-secondary mr5"><?php echo app_lang("gd_complete_series"); ?></button><button data-action="cancel" data-reason="1" class="btn btn-danger"><?php echo app_lang("gd_cancel_series"); ?></button><?php } ?></div></div><?php } ?>
        <div class="card"><div class="card-header"><h4><?php echo app_lang("gd_series_exceptions"); ?></h4></div><div class="card-body"><?php foreach ($series->exceptions as $exception) { ?><div class="mb10"><strong><?php echo $e($exception->exception_type); ?></strong> — <?php echo $e($exception->local_date); ?><?php if ($exception->reason) { ?><br><small><?php echo $e($exception->reason); ?></small><?php } ?></div><?php } ?></div></div>
        <div class="card"><div class="card-header"><h4><?php echo app_lang("gd_series_history"); ?></h4></div><div class="card-body"><?php foreach ($series->events as $event) { ?><div class="mb10"><strong><?php echo $e($event->event_type); ?></strong> <small class="text-muted"><?php echo $e($event->created_at . " UTC"); ?></small></div><?php } ?></div></div>
    </div></div>
</div>
<script>
$(document).ready(function(){
    function post(url,data){$.post(url,data).done(function(response){if(response.success){location.reload();}else{appAlert.error(response.message);}});}
    $("#gd-series-actions button").on("click",function(){var button=$(this),reason="";if(button.data("reason")){reason=window.prompt('<?php echo addslashes(app_lang("gd_reason")); ?>','');if(!reason){return;}}post('<?php echo_uri("grupo_donato/booking-series/" . (int) $series->id . "/"); ?>'+button.data("action"),{lock_version:<?php echo (int) $series->lock_version; ?>,reason:reason});});
    $(".gd-cancel-occurrence").on("click",function(){var reason=window.prompt('<?php echo addslashes(app_lang("gd_reason")); ?>','');if(reason){post('<?php echo_uri("grupo_donato/booking-series/cancel-occurrence"); ?>',{booking_id:$(this).data("id"),reason:reason});}});
});
</script>
