<?php
$detail_buttons = anchor(get_uri('grupo_donato/school/students'), '<i data-feather="arrow-left" class="icon-16"></i> '.app_lang('back'), ['class'=>'btn btn-default']);
if(!empty($can_manage)) $detail_buttons .= ' '.modal_anchor(get_uri('grupo_donato/school/students/modal'), '<i data-feather="edit" class="icon-16"></i> '.app_lang('edit'), ['class'=>'btn btn-default','title'=>app_lang('gd_school_student'),'data-post-id'=>(int)$student->id]);
if(!empty($student->family_account_id)) $detail_buttons .= ' '.anchor(get_uri('grupo_donato/customers/view/'.(int)$student->family_account_id), '<i data-feather="briefcase" class="icon-16"></i> '.app_lang('gd_school_family'), ['class'=>'btn btn-default']);
$detail_buttons .= ' '.anchor(get_uri('grupo_donato/school/classes'), '<i data-feather="layers" class="icon-16"></i> '.app_lang('gd_school_enroll'), ['class'=>'btn btn-default']);
$detail_buttons .= ' '.anchor(get_uri('grupo_donato/school/attendance'), '<i data-feather="check-square" class="icon-16"></i> '.app_lang('gd_school_attendance'), ['class'=>'btn btn-default']);
if(!empty($financial)&&!empty($student->family_account_id)) $detail_buttons .= ' '.anchor(get_uri('grupo_donato/finance/receivables?customer_account_id='.(int)$student->family_account_id), '<i data-feather="dollar-sign" class="icon-16"></i> '.app_lang('gd_finance_overview'), ['class'=>'btn btn-default']);
?>
<?php echo view("grupo_donato_gestao\\Views\\components\\page_header", ["title" => esc($student->person->full_name), "buttons" => $detail_buttons]); ?>
<?php if(!empty($financial)) include dirname(__DIR__).'/finance/context_summary.php'; ?>
<div class="card"><div class="page-title clearfix"><h1><?php echo esc($student->person->full_name); ?></h1></div><div class="card-body"><p><strong><?php echo app_lang('gd_school_family'); ?>:</strong> <?php echo esc($student->family->display_name??'-'); ?></p><p><strong><?php echo app_lang('gd_school_guardians'); ?>:</strong> <?php echo esc(implode(', ',array_map(fn($x)=>$x->full_name,$student->guardians))); ?></p><h4><?php echo app_lang('gd_school_enrollments'); ?></h4><div class="table-responsive"><table class="table"><tr><th><?php echo app_lang('gd_school_class'); ?></th><th><?php echo app_lang('gd_status'); ?></th><th><?php echo app_lang('gd_school_start'); ?></th><th><?php echo app_lang('gd_finance_receivables'); ?></th></tr><?php foreach($student->enrollments as $e): ?><tr><td><?php echo esc($e->class_name); ?></td><td><?php echo app_lang('gd_school_status_'.$e->status); ?></td><td><?php echo format_to_date($e->starts_on,false); ?></td><td><a href="<?php echo get_uri('grupo_donato/finance/receivables?source_type=enrollment&source_id='.(int)$e->id); ?>"><?php echo app_lang('gd_view_details'); ?></a></td></tr><?php endforeach; ?></table></div><h4><?php echo app_lang('gd_school_frequency'); ?>: <?php echo $student->attendance['percentage']===null?'-':$student->attendance['percentage'].'%'; ?></h4><div class="table-responsive"><table class="table"><tr><th><?php echo app_lang('gd_date'); ?></th><th><?php echo app_lang('gd_school_class'); ?></th><th><?php echo app_lang('gd_status'); ?></th></tr><?php foreach($student->attendance['rows'] as $a): ?><tr><td><?php echo format_to_date($a->attendance_date,false); ?></td><td><?php echo esc($a->class_name); ?></td><td><?php echo app_lang('gd_school_attendance_'.$a->attendance_status); ?></td></tr><?php endforeach; ?></table></div></div></div>
