<?php $id=(int)($model_info->id??0);$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,"UTF-8"); ?>
<?php echo form_open(get_uri("grupo_donato/resources/availability/save"),["id"=>"gd-availability-form","class"=>"general-form"]); ?><div class="modal-body clearfix"><div class="container-fluid">
<input type="hidden" name="id" value="<?php echo $id; ?>"><input type="hidden" name="resource_id" value="<?php echo (int)$resource_id; ?>">
<div class="form-group row"><label class="col-md-3"><?php echo app_lang("gd_weekday"); ?></label><div class="col-md-9"><select name="weekday" class="form-control"><?php foreach($weekdays as $v=>$label){ ?><option value="<?php echo $v; ?>"<?php echo (int)($model_info->weekday??1)===$v?' selected':''; ?>><?php echo $e($label); ?></option><?php } ?></select></div></div>
<div class="form-group row"><label class="col-md-3"><?php echo app_lang("gd_start_time"); ?></label><div class="col-md-3"><input type="time" name="start_time" class="form-control" required value="<?php echo $e(substr((string)($model_info->start_time??""),0,5)); ?>"></div><label class="col-md-3"><?php echo app_lang("gd_end_time"); ?></label><div class="col-md-3"><input type="time" name="end_time" class="form-control" required value="<?php echo $e(substr((string)($model_info->end_time??""),0,5)); ?>"></div></div>
<div class="form-group row"><label class="col-md-3"><?php echo app_lang("gd_options"); ?></label><div class="col-md-9"><label><input type="checkbox" name="spans_next_day" value="1"<?php echo !empty($model_info->spans_next_day)?' checked':''; ?>> <?php echo app_lang("gd_spans_next_day"); ?></label></div></div>
<div class="form-group row"><label class="col-md-3"><?php echo app_lang("gd_valid_from"); ?></label><div class="col-md-3"><input type="date" name="valid_from" class="form-control" value="<?php echo $e($model_info->valid_from??""); ?>"></div><label class="col-md-3"><?php echo app_lang("gd_valid_until"); ?></label><div class="col-md-3"><input type="date" name="valid_until" class="form-control" value="<?php echo $e($model_info->valid_until??""); ?>"></div></div>
<div class="form-group row"><label class="col-md-3"><?php echo app_lang("gd_status"); ?></label><div class="col-md-3"><select name="status" class="form-control"><?php foreach($statuses as $s){ ?><option value="<?php echo $s; ?>"<?php echo ($model_info->status??'active')===$s?' selected':''; ?>><?php echo app_lang("gd_status_".$s); ?></option><?php } ?></select></div><label class="col-md-3"><?php echo app_lang("gd_sort_order"); ?></label><div class="col-md-3"><input type="number" min="0" name="sort_order" class="form-control" value="<?php echo (int)($model_info->sort_order??0); ?>"></div></div>
<div class="form-group row"><label class="col-md-3"><?php echo app_lang("gd_notes"); ?></label><div class="col-md-9"><textarea name="notes" class="form-control" rows="3"><?php echo $e($model_info->notes??""); ?></textarea></div></div>
</div></div><div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal"><?php echo app_lang("close"); ?></button><button type="submit" class="btn btn-primary"><?php echo app_lang("save"); ?></button></div><?php echo form_close(); ?>
<script>$(document).ready(function(){ $("#gd-availability-form").appForm({onSuccess:function(){ $("#gd-availability-table").appTable({reload:true}); }}); });</script>
