<?php

declare(strict_types=1);

namespace grupo_donato_gestao\Controllers;

use grupo_donato_gestao\Config\Constants;
use grupo_donato_gestao\Services\CustomerAccountService;
use grupo_donato_gestao\Services\DataPrivacyService;

class Customer_accounts extends Gd_Controller
{
    private $model; private CustomerAccountService $service; private int $unit_id;
    public function __construct(){parent::__construct();$this->access->require('gd_customer_accounts_view');$this->unit_id=(int)$this->active_unit_id();if(!$this->unit_id){throw new \RuntimeException('No active unit.');}$this->model=$this->gd_model('Gd_customer_accounts_model');$this->service=new CustomerAccountService($this->unit_id,$this->user_id(),$this->login_user);}
    public function index(){return $this->gd_render('customers/index',['can_manage'=>$this->access->can('gd_customer_accounts_manage')]);}
    public function view($id){$row=$this->service->get((int)$id);if(!$row)return show_404();$canAudit=$this->access->can('gd_audit_view');$audits=$canAudit?$this->gd_model('Gd_audit_logs_model')->get_details(['unit_id'=>$this->unit_id,'entity_type'=>'customer_account','entity_id'=>(int)$row->id,'limit'=>8])->getResult():[];$financial=$this->access->can('gd_finance_view')?(new \grupo_donato_gestao\Services\FinanceService($this->unit_id,$this->user_id(),$this->login_user))->summary(['customer_account_id'=>(int)$row->id]):null;return $this->gd_render('customers/view',['account'=>$row,'document_masked'=>DataPrivacyService::maskDocument($row->document_number),'duplicates'=>$this->service->duplicates((array)$row,(int)$row->id),'audits'=>$audits,'can_manage'=>$this->access->can('gd_customer_accounts_manage'),'can_relations'=>$this->access->can('gd_customer_relations_manage'),'can_addresses'=>$this->access->can('gd_addresses_manage'),'can_audit'=>$canAudit,'financial'=>$financial]);}
    public function list_data(){ $o=append_server_side_filtering_commmon_params(['unit_id'=>$this->unit_id,'account_type'=>$this->request->getPost('account_type'),'status'=>$this->request->getPost('status')]);$r=$this->model->get_details($o);$rows=[];foreach($r['data'] as $x){$rows[]=$this->row($x);} $r['data']=$rows;echo json_encode($r);}
    public function modal_form(){ $this->access->require('gd_customer_accounts_manage');$id=(int)$this->request->getPost('id');$row=$id?$this->service->get($id):null;if($id&&!$row)return show_404();return $this->gd_view('customers/modal_form',['model_info'=>$row?:new \stdClass(),'types'=>$this->dropdown(Constants::ACCOUNT_TYPES,'gd_account_type_'),'statuses'=>$this->dropdown(Constants::ACCOUNT_STATUSES,'gd_status_'),'document_types'=>$this->dropdown(Constants::DOCUMENT_TYPES_CUSTOMER,'gd_document_type_')]);}
    public function save(){ $this->access->require('gd_customer_accounts_manage');try{$result=$this->service->save($this->account_input(),(int)$this->request->getPost('id'),(bool)$this->request->getPost('duplicate_override'));if(!$result['saved'])return $this->json_error(app_lang('gd_duplicate_confirmation_required'),['duplicate_confirmation_required'=>true,'duplicates'=>$result['duplicates']]);$saved=$this->service->get($result['id']);$saved->people_count=$this->model->active_relation_count($result['id'],$this->unit_id);return $this->json_success(app_lang('record_saved'),['id'=>$result['id'],'data'=>$this->row($saved),'duplicates'=>$result['duplicates']]);}catch(\Throwable $e){return $this->service_error($e);}}
    public function delete(){ $this->access->require('gd_customer_accounts_manage');try{$this->service->delete((int)$this->request->getPost('id'),(string)$this->request->getPost('reason'));return $this->json_success(app_lang('record_deleted'));}catch(\Throwable $e){return $this->service_error($e);}}
    public function duplicates(){try{return $this->json_success('', ['duplicates'=>$this->service->duplicates($this->account_input(),(int)$this->request->getPost('id'))]);}catch(\Throwable $e){return $this->service_error($e);}}
    private function account_input():array{return ['account_type'=>$this->request->getPost('account_type'),'display_name'=>$this->request->getPost('display_name'),'legal_name'=>$this->request->getPost('legal_name'),'trade_name'=>$this->request->getPost('trade_name'),'document_type'=>$this->request->getPost('document_type'),'document_number'=>$this->request->getPost('document_number'),'email'=>$this->request->getPost('email'),'phone'=>$this->request->getPost('phone'),'whatsapp'=>$this->request->getPost('whatsapp'),'status'=>$this->request->getPost('status'),'rise_client_id'=>$this->request->getPost('rise_client_id'),'notes'=>$this->request->getPost('notes')];}
    private function row($x):array{if(!$x)return[];$actions=anchor(get_uri('grupo_donato/customers/view/'.$x->id),"<i data-feather='eye' class='icon-16'></i>",['title'=>app_lang('gd_view_details')]);if($this->access->can('gd_customer_accounts_manage')){$actions.=modal_anchor(get_uri('grupo_donato/customers/modal_form'),"<i data-feather='edit' class='icon-16'></i>",['title'=>app_lang('edit'),'data-post-id'=>$x->id]);}$contact=$x->phone?:($x->whatsapp?:$x->email);$masked=($x->phone||$x->whatsapp)?DataPrivacyService::maskPhone($contact):DataPrivacyService::maskEmail($contact);return[$this->escape($x->display_name),app_lang('gd_account_type_'.$x->account_type),$this->escape(DataPrivacyService::maskDocument($x->document_number)),$this->escape($masked),(int)$x->people_count,app_lang('gd_status_'.$x->status),$x->updated_at?format_to_datetime($x->updated_at):'',$actions];}
    private function dropdown(array $values,string $prefix):array{$out=[];foreach($values as $v)$out[]=['id'=>$v,'text'=>app_lang($prefix.$v)];return$out;}
    private function service_error(\Throwable $e):void{$key=$e->getMessage();$message=str_starts_with($key,'gd_')?app_lang($key):app_lang('error_occurred');$this->json_error($message);}
}
