<?php
declare(strict_types=1);namespace grupo_donato_gestao\Controllers;
use grupo_donato_gestao\Config\Constants;use grupo_donato_gestao\Services\FinanceService;use grupo_donato_gestao\Services\ReceivableGenerationService;
class Finance extends Gd_Controller
{
    private FinanceService $service;private int $unit;
    public function __construct(){parent::__construct();$this->access->require('gd_finance_view');$this->unit=(int)$this->active_unit_id();if(!$this->unit)throw new \RuntimeException('No active unit.');$this->service=new FinanceService($this->unit,$this->user_id(),$this->login_user);}
    public function index(){return $this->gd_render('finance/overview',['dashboard'=>$this->service->dashboard(),'can_receivables'=>$this->access->can('gd_receivables_manage'),'can_payments'=>$this->access->can('gd_payments_manage'),'can_expenses'=>$this->access->can('gd_expenses_manage')]);}
    public function account_modal(){try{$this->access->require('gd_receivables_manage');return $this->gd_view('finance/account_modal',['types'=>Constants::FINANCIAL_ACCOUNT_TYPES]);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function save_account(){try{$this->access->require('gd_receivables_manage');$r=$this->service->saveAccount(['code'=>$this->request->getPost('code'),'name'=>$this->request->getPost('name'),'account_type'=>$this->request->getPost('account_type'),'status'=>'active','notes'=>$this->request->getPost('notes')]);$this->json_success(app_lang('record_saved'),$r);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function receivables(){return $this->gd_render('finance/receivables',['can_manage'=>$this->access->can('gd_receivables_manage'),'can_payments'=>$this->access->can('gd_payments_manage'),'statuses'=>Constants::RECEIVABLE_STATUSES,'sources'=>Constants::RECEIVABLE_SOURCE_TYPES,'initial_source_type'=>(string)$this->request->getGet('source_type'),'initial_source_id'=>(int)$this->request->getGet('source_id'),'initial_customer_account_id'=>(int)$this->request->getGet('customer_account_id')]);}
    public function receivables_data(){try{$r=$this->service->receivablesPage(append_server_side_filtering_commmon_params($this->filters(['status','source_type','source_id','customer_account_id','business_area_id','cost_center_id','date_from','date_to'])));$r['data']=array_map(fn($x)=>['number'=>anchor(get_uri('grupo_donato/finance/receivables/view/'.$x->id),$this->escape($x->receivable_number)),'customer'=>$this->escape($x->customer_name),'source'=>app_lang('gd_finance_source_'.$x->source_type),'description'=>$this->escape($x->description),'reference'=>$x->reference_month?:'-','due'=>format_to_date($x->due_date,false),'amount'=>$x->original_amount,'paid'=>$x->paid_amount,'balance'=>$x->balance_amount,'status'=>app_lang('gd_finance_receivable_status_'.$x->display_status),'options'=>$this->access->can('gd_payments_manage')&&$x->balance_amount!=='0.00'?modal_anchor(get_uri('grupo_donato/finance/payment-modal'),'<i data-feather="dollar-sign" class="icon-16"></i>',['title'=>app_lang('gd_finance_register_payment'),'data-post-receivable_id'=>$x->id,'data-post-balance'=>$x->balance_amount]):''],$r['data']);return $this->response->setJSON($r);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function receivable_modal(){try{$this->access->require('gd_receivables_manage');return $this->gd_view('finance/receivable_modal',['accounts'=>$this->options('gd_customer_accounts','display_name'),'areas'=>$this->options('gd_business_areas','name',true),'centers'=>$this->options('gd_cost_centers','name',true)]);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function save_receivable(){try{$this->access->require('gd_receivables_manage');$keys=['customer_account_id','description','issue_date','due_date','original_amount','business_area_id','cost_center_id','notes'];$in=['source_type'=>'manual','reference_month'=>''];foreach($keys as $k)$in[$k]=$this->request->getPost($k);$in['unit_amount']=$in['original_amount'];$in['quantity']='1';$r=$this->service->createReceivable($in);$this->json_success(app_lang('record_saved'),$r);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function view_receivable($id){$r=$this->service->getReceivable((int)$id);if(!$r)return show_404();return $this->gd_render('finance/receivable_view',['receivable'=>$r,'can_payments'=>$this->access->can('gd_payments_manage'),'can_manage'=>$this->access->can('gd_receivables_manage')]);}
    public function cancel_receivable(){try{$this->access->require('gd_receivables_manage');$this->service->cancelReceivable((int)$this->request->getPost('id'),(string)$this->request->getPost('reason'));$this->json_success(app_lang('record_saved'));}catch(\Throwable $e){$this->gd_fail($e);}}
    public function generate(){return $this->gd_render('finance/generate',['can_manage'=>$this->access->can('gd_receivables_manage')]);}
    public function generation_preview(){try{$this->access->require('gd_receivables_manage');$r=(new ReceivableGenerationService($this->unit,$this->user_id(),$this->login_user))->preview((string)$this->request->getPost('reference_month'));return $this->response->setJSON(['success'=>true,'data'=>$r]);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function generation_confirm(){try{$this->access->require('gd_receivables_manage');$r=(new ReceivableGenerationService($this->unit,$this->user_id(),$this->login_user))->generateMonth((string)$this->request->getPost('reference_month'),(array)$this->request->getPost('adjustments'));$this->json_success(app_lang('gd_finance_generation_done'),['data'=>$r]);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function generate_rental(){try{$this->access->require('gd_receivables_manage');$r=(new ReceivableGenerationService($this->unit,$this->user_id(),$this->login_user))->generateCourtRental((int)$this->request->getPost('rental_id'),['amount'=>$this->request->getPost('amount'),'due_date'=>$this->request->getPost('due_date')]);$msg=empty($r['created'])&&!empty($r['duplicate'])?app_lang('gd_finance_receivable_exists'):app_lang('record_saved');$this->json_success($msg,$r);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function payments(){return $this->gd_render('finance/payments',['can_manage'=>$this->access->can('gd_payments_manage')]);}
    public function payments_data(){try{$r=$this->service->paymentsPage(append_server_side_filtering_commmon_params($this->filters(['date_from','date_to'])));$r['data']=array_map(fn($x)=>['number'=>anchor(get_uri('grupo_donato/finance/payments/receipt/'.$x->id),$this->escape($x->payment_number)),'date'=>format_to_date($x->payment_date,false),'account'=>$this->escape($x->account_name),'method'=>app_lang('gd_finance_method_'.$x->payment_method),'amount'=>$x->amount,'status'=>app_lang('gd_finance_payment_status_'.$x->status),'options'=>$this->access->can('gd_payments_manage')&&$x->status==='confirmed'?ajax_anchor(get_uri('grupo_donato/finance/payments/reverse'),'<i data-feather="rotate-ccw" class="icon-16"></i>',['data-post-id'=>$x->id,'data-post-reason'=>app_lang('gd_finance_operator_reversal'),'data-reload-on-success'=>1,'title'=>app_lang('gd_finance_reverse_payment')]):''],$r['data']);return $this->response->setJSON($r);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function payment_modal(){try{$this->access->require('gd_payments_manage');$rid=(int)$this->request->getPost('receivable_id');$balance=(string)$this->request->getPost('balance');$open=$this->service->receivablesPage(['status'=>'open','limit'=>100])['data'];$partial=$this->service->receivablesPage(['status'=>'partial','limit'=>100])['data'];$overdue=$this->service->receivablesPage(['status'=>'overdue','limit'=>100])['data'];return $this->gd_view('finance/payment_modal',['receivable_id'=>$rid,'balance'=>$balance,'receivables'=>array_merge($open,$partial,$overdue),'accounts'=>$this->service->accounts(),'methods'=>Constants::PAYMENT_METHODS]);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function save_payment(){try{$this->access->require('gd_payments_manage');$r=$this->service->registerPayment(['allocations'=>(array)$this->request->getPost('allocations'),'amount'=>$this->request->getPost('amount'),'payment_date'=>$this->request->getPost('payment_date'),'payment_method'=>$this->request->getPost('payment_method'),'financial_account_id'=>$this->request->getPost('financial_account_id'),'external_reference'=>$this->request->getPost('external_reference'),'notes'=>$this->request->getPost('notes')]);$this->json_success(app_lang('record_saved'),$r);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function reverse_payment(){try{$this->access->require('gd_payments_manage');$this->service->reversePayment((int)$this->request->getPost('id'),(string)$this->request->getPost('reason'));$this->json_success(app_lang('record_saved'));}catch(\Throwable $e){$this->gd_fail($e);}}
    public function receipt($id){$p=$this->service->getPayment((int)$id);if(!$p)return show_404();return $this->gd_render('finance/receipt',['payment'=>$p]);}
    public function expenses(){return $this->gd_render('finance/expenses',['can_manage'=>$this->access->can('gd_expenses_manage')]);}
    public function expenses_data(){try{$r=$this->service->expensesPage(append_server_side_filtering_commmon_params($this->filters(['status'])));$r['data']=array_map(fn($x)=>['number'=>$this->escape($x->expense_number),'description'=>$this->escape($x->description),'payee'=>$this->escape($x->payee?:'-'),'date'=>format_to_date($x->expense_date,false),'due'=>$x->due_date?format_to_date($x->due_date,false):'-','amount'=>$x->amount,'status'=>app_lang('gd_finance_expense_status_'.$x->status),'account'=>$this->escape($x->account_name?:'-'),'options'=>$this->access->can('gd_expenses_manage')&&$x->status!=='paid'?modal_anchor(get_uri('grupo_donato/finance/expense-modal'),'<i data-feather="edit" class="icon-16"></i>',['title'=>app_lang('gd_finance_expense'),'data-post-id'=>$x->id]):''],$r['data']);return $this->response->setJSON($r);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function expense_modal(){try{$this->access->require('gd_expenses_manage');$id=(int)$this->request->getPost('id');$expense=$id?model('grupo_donato_gestao\\Models\\Gd_expenses_model')->get_scoped($id,$this->unit):null;return $this->gd_view('finance/expense_modal',['expense'=>$expense,'accounts'=>$this->service->accounts(),'areas'=>$this->options('gd_business_areas','name',true),'centers'=>$this->options('gd_cost_centers','name',true),'methods'=>Constants::PAYMENT_METHODS,'statuses'=>Constants::EXPENSE_STATUSES]);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function save_expense(){try{$this->access->require('gd_expenses_manage');$keys=['description','payee','expense_date','due_date','paid_date','amount','status','financial_account_id','business_area_id','cost_center_id','payment_method','notes'];$in=[];foreach($keys as $k)$in[$k]=$this->request->getPost($k);$r=$this->service->saveExpense($in,(int)$this->request->getPost('id'));$this->json_success(app_lang('record_saved'),$r);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function cash(){ $this->access->require('gd_cash_view');return $this->gd_render('finance/cash',['accounts'=>$this->service->accounts()]);}
    public function cash_data(){try{$this->access->require('gd_cash_view');$rows=$this->service->cashPage($this->filters(['financial_account_id','date_from','date_to']));$data=array_map(fn($x)=>['date'=>format_to_date($x->movement_date,false),'account'=>$this->escape($x->account_name),'type'=>app_lang('gd_finance_movement_'.$x->movement_type),'source'=>app_lang('gd_finance_source_'.$x->source_type),'description'=>$this->escape($x->description),'in'=>$x->movement_type==='in'?$x->amount:'','out'=>$x->movement_type==='out'?$x->amount:'','balance'=>$x->running_balance],$rows);return $this->response->setJSON(['data'=>$data,'recordsTotal'=>count($data),'recordsFiltered'=>count($data)]);}catch(\Throwable $e){$this->gd_fail($e);}}
    private function filters(array $keys):array{$o=[];foreach($keys as $k)$o[$k]=$this->request->getPost($k)??$this->request->getGet($k);return $o;}
    private function options(string $table,string $label,bool $global=false):array{$db=db_connect();$q=$db->table($db->prefixTable($table))->select("id,$label text",false)->where('deleted',0);if(!$global)$q->where('unit_id',$this->unit);else$q->groupStart()->where('unit_id',$this->unit)->orWhere('unit_id IS NULL',null,false)->groupEnd();return $q->orderBy($label)->get()->getResultArray();}
}
