<?php
declare(strict_types=1);
namespace grupo_donato_gestao\Controllers;
use grupo_donato_gestao\Config\Constants;
use grupo_donato_gestao\Services\SchoolClassService;
use grupo_donato_gestao\Services\SchoolEnrollmentService;
class School_classes extends Gd_Controller
{
    private SchoolClassService $service;private int $unit;
    public function __construct(){parent::__construct();$this->access->require('gd_school_view');$this->unit=(int)$this->active_unit_id();if(!$this->unit)throw new \RuntimeException('No active unit.');$this->service=new SchoolClassService($this->unit,$this->user_id(),$this->login_user);}
    public function index(){return $this->gd_render('school_classes/index',['can_manage'=>$this->access->can('gd_classes_manage'),'types'=>Constants::SCHOOL_CLASS_TYPES,'statuses'=>Constants::SCHOOL_CLASS_STATUSES]);}
    public function list_data(){try{$r=$this->service->listPage(append_server_side_filtering_commmon_params(['status'=>$this->request->getPost('status'),'class_type'=>$this->request->getPost('class_type')]));$r['data']=array_map(fn($x)=>['number'=>$this->escape($x->class_number),'name'=>anchor(get_uri('grupo_donato/school/classes/view/'.$x->id),$this->escape($x->name)),'modality'=>$this->escape($x->modality),'type'=>app_lang('gd_school_class_type_'.$x->class_type),'instructor'=>$this->escape($x->instructor_name?:'-'),'resource'=>$this->escape($x->resource_name?:'-'),'schedule'=>$this->escape($x->weekdays?:'-').' '.$this->escape(substr((string)$x->local_start_time,0,5)),'capacity'=>(int)$x->enrolled.' / '.(int)$x->capacity,'status'=>app_lang('gd_school_status_'.$x->status),'options'=>$this->access->can('gd_classes_manage')?modal_anchor(get_uri('grupo_donato/school/classes/modal'),'<i data-feather="edit" class="icon-16"></i>',['class'=>'edit','title'=>app_lang('gd_school_class'),'data-post-id'=>$x->id]):''],$r['data']);return $this->response->setJSON($r);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function modal(){try{$this->access->require('gd_classes_manage');$id=(int)($this->request->getPost('id')?:$this->request->getGet('id'));$class=$id?$this->service->get($id):null;$db=db_connect();$scoped=fn($t,$label)=>$db->table($db->prefixTable($t))->select("id,$label text",false)->where('unit_id',$this->unit)->where('deleted',0)->where('status','active')->orderBy($label)->get()->getResultArray();$staff=$db->table($db->prefixTable('users'))->select("id,TRIM(CONCAT(first_name,' ',last_name)) text",false)->where('user_type','staff')->where('status','active')->orderBy('first_name')->get()->getResultArray();return $this->gd_view('school_classes/modal_form',['class'=>$class,'types'=>Constants::SCHOOL_CLASS_TYPES,'statuses'=>Constants::SCHOOL_CLASS_STATUSES,'resources'=>$scoped('gd_resources','name'),'people'=>$scoped('gd_people','full_name'),'staff'=>$staff]);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function save(){try{$this->access->require('gd_classes_manage');$keys=['name','modality','class_type','instructor_user_id','instructor_person_id','resource_id','booking_series_id','booking_id','local_start_time','local_end_time','capacity','min_age','max_age','starts_on','ends_on','status','notes','lock_version','create_series'];$in=[];foreach($keys as $k)$in[$k]=$this->request->getPost($k);$in['weekdays']=(array)$this->request->getPost('weekdays');$r=$this->service->save($in,(int)$this->request->getPost('id'));$this->json_success(app_lang('record_saved'),$r);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function view($id){$c=$this->service->get((int)$id);if(!$c)return show_404();$db=db_connect();$resource_name=$c->resource_id?(string)($db->table($db->prefixTable('gd_resources'))->select('name')->where('id',(int)$c->resource_id)->where('unit_id',$this->unit)->get(1)->getRow()->name??''):'';$instructor_name='';if($c->instructor_person_id){$instructor_name=(string)($db->table($db->prefixTable('gd_people'))->select('full_name')->where('id',(int)$c->instructor_person_id)->where('unit_id',$this->unit)->get(1)->getRow()->full_name??'');}elseif($c->instructor_user_id){$instructor_name=(string)($db->table($db->prefixTable('users'))->select("TRIM(CONCAT(first_name,' ',last_name)) n",false)->where('id',(int)$c->instructor_user_id)->get(1)->getRow()->n??'');}return $this->gd_render('school_classes/view',['class'=>$c,'resource_name'=>$resource_name,'instructor_name'=>$instructor_name,'can_manage'=>$this->access->can('gd_classes_manage'),'can_enroll'=>$this->access->can('gd_enrollments_manage')]);}
    public function enrollment_modal(){try{$this->access->require('gd_enrollments_manage');$db=db_connect();$profiles=$db->query("SELECT sp.id,p.full_name text FROM `{$db->prefixTable('gd_school_profiles')}` sp JOIN `{$db->prefixTable('gd_people')}` p ON p.id=sp.person_id AND p.deleted=0 WHERE sp.unit_id=? AND sp.status='active' AND sp.deleted=0 ORDER BY p.full_name",[$this->unit])->getResultArray();$products=$db->table($db->prefixTable('gd_products'))->select('id,name text')->where('unit_id',$this->unit)->where('status','active')->where('deleted',0)->orderBy('name')->get()->getResultArray();return $this->gd_view('school_classes/enrollment_modal',['class_id'=>(int)$this->request->getPost('class_id'),'profiles'=>$profiles,'products'=>$products,'statuses'=>Constants::SCHOOL_ENROLLMENT_STATUSES]);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function enroll(){try{$this->access->require('gd_enrollments_manage');$r=(new SchoolEnrollmentService($this->unit,$this->user_id(),$this->login_user))->save(['class_id'=>$this->request->getPost('class_id'),'school_profile_id'=>$this->request->getPost('school_profile_id'),'product_id'=>$this->request->getPost('product_id'),'starts_on'=>$this->request->getPost('starts_on'),'ends_on'=>$this->request->getPost('ends_on'),'preferred_due_day'=>$this->request->getPost('preferred_due_day'),'status'=>$this->request->getPost('status'),'notes'=>$this->request->getPost('notes')],(int)$this->request->getPost('id'));$this->json_success(app_lang('record_saved'),$r);}catch(\Throwable $e){$this->gd_fail($e);}}
}
