<?php
declare(strict_types=1);
namespace grupo_donato_gestao\Controllers;
use grupo_donato_gestao\Config\Constants;
use grupo_donato_gestao\Services\SchoolStudentService;
class School_students extends Gd_Controller
{
    private SchoolStudentService $service;
    public function __construct(){parent::__construct();$this->access->require('gd_school_view');$unit=(int)$this->active_unit_id();if(!$unit)throw new \RuntimeException('No active unit.');$this->service=new SchoolStudentService($unit,$this->user_id(),$this->login_user);}
    public function index(){return $this->gd_render('school_students/index',['can_manage'=>$this->access->can('gd_students_manage'),'statuses'=>Constants::SCHOOL_PROFILE_STATUSES]);}
    public function list_data(){try{$r=$this->service->listPage(append_server_side_filtering_commmon_params(['status'=>$this->request->getPost('status')]));$r['data']=array_map(fn($x)=>['name'=>anchor(get_uri('grupo_donato/school/students/view/'.$x->id),$this->escape($x->full_name)),'guardian'=>$this->escape($x->guardian_name?:'-'),'contact'=>$this->escape($x->primary_contact?:'-'),'classes'=>$this->escape($x->class_names?:'-'),'frequency'=>$x->frequency===null?'-':$x->frequency.'%','status'=>app_lang('gd_school_status_'.$x->status),'options'=>$this->access->can('gd_students_manage')?modal_anchor(get_uri('grupo_donato/school/students/modal'),' <i data-feather="edit" class="icon-16"></i>',['class'=>'edit','title'=>app_lang('gd_school_student'),'data-post-id'=>$x->id]):''],$r['data']);return $this->response->setJSON($r);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function modal(){try{$this->access->require('gd_students_manage');$id=(int)($this->request->getPost('id')?:$this->request->getGet('id'));$student=$id?$this->service->get($id):null;return $this->gd_view('school_students/modal_form',['student'=>$student,'families'=>$this->service->options('gd_customer_accounts','display_name','account_type = \'family\''),'people'=>$this->service->options('gd_people','full_name'),'statuses'=>Constants::SCHOOL_PROFILE_STATUSES]);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function save(){try{$this->access->require('gd_students_manage');$result=$this->service->save(['person_id'=>$this->request->getPost('person_id'),'full_name'=>$this->request->getPost('full_name'),'birth_date'=>$this->request->getPost('birth_date'),'family_account_id'=>$this->request->getPost('family_account_id'),'new_family_name'=>$this->request->getPost('new_family_name'),'guardian_ids'=>(array)$this->request->getPost('guardian_ids'),'primary_guardian_id'=>$this->request->getPost('primary_guardian_id'),'contact_type'=>$this->request->getPost('contact_type'),'contact_value'=>$this->request->getPost('contact_value'),'status'=>$this->request->getPost('status'),'notes'=>$this->request->getPost('notes'),'duplicate_override'=>$this->request->getPost('duplicate_override')],(int)$this->request->getPost('id'));if(empty($result['saved'])){$this->json_error(app_lang('gd_duplicate_confirmation_required'),$result);return;}$this->json_success(app_lang('record_saved'),['id'=>$result['id']]);}catch(\Throwable $e){$this->gd_fail($e);}}
    public function view($id){$s=$this->service->get((int)$id);if(!$s)return show_404();$financial=$this->access->can('gd_finance_view')?(new \grupo_donato_gestao\Services\FinanceService((int)$this->active_unit_id(),$this->user_id(),$this->login_user))->summary(['customer_account_id'=>(int)$s->family_account_id]):null;return $this->gd_render('school_students/view',['student'=>$s,'can_manage'=>$this->access->can('gd_students_manage'),'can_enroll'=>$this->access->can('gd_enrollments_manage'),'financial'=>$financial]);}
}
