<?php $c=$class??null; echo form_open(get_uri('grupo_donato/school/classes/save'),['id'=>'class-form','class'=>'general-form']); ?>
<div class="modal-body">
<input type="hidden" name="id" value="<?php echo $c->id??0; ?>"><input type="hidden" name="lock_version" value="<?php echo $c->lock_version??0; ?>">
<div class="form-group"><label><?php echo app_lang('gd_name'); ?></label><input required class="form-control" name="name" value="<?php echo esc($c->name??''); ?>"></div>
<div class="form-group"><label><?php echo app_lang('gd_school_modality'); ?></label><input required class="form-control" name="modality" value="<?php echo esc($c->modality??'Futebol'); ?>"></div>
<div class="row"><div class="col-md-6"><label><?php echo app_lang('gd_type'); ?></label><?php echo form_dropdown('class_type',array_combine($types,array_map(fn($x)=>app_lang('gd_school_class_type_'.$x),$types)),$c->class_type??'group','class="form-control"'); ?></div><div class="col-md-6"><label><?php echo app_lang('gd_school_capacity'); ?></label><input type="number" min="1" class="form-control" name="capacity" value="<?php echo $c->capacity??1; ?>"></div></div>
<div class="form-group mt-3"><label><?php echo app_lang('gd_school_instructor_staff'); ?></label><?php echo form_dropdown('instructor_user_id',[''=>'-']+array_column($staff,'text','id'),$c->instructor_user_id??'','class="form-control select2"'); ?></div>
<div class="form-group"><label><?php echo app_lang('gd_school_instructor_person'); ?></label><?php echo form_dropdown('instructor_person_id',[''=>'-']+array_column($people,'text','id'),$c->instructor_person_id??'','class="form-control select2"'); ?></div>
<div class="form-group"><label><?php echo app_lang('gd_resource'); ?></label><?php echo form_dropdown('resource_id',[''=>'-']+array_column($resources,'text','id'),$c->resource_id??'','class="form-control select2"'); ?></div>
<div class="form-group"><label><?php echo app_lang('gd_school_weekdays'); ?></label><?php echo form_multiselect('weekdays[]',[1=>app_lang('gd_weekday_1'),2=>app_lang('gd_weekday_2'),3=>app_lang('gd_weekday_3'),4=>app_lang('gd_weekday_4'),5=>app_lang('gd_weekday_5'),6=>app_lang('gd_weekday_6'),7=>app_lang('gd_weekday_7')],isset($c->weekdays)?explode(',',$c->weekdays):[],'class="form-control select2"'); ?></div>
<div class="row"><div class="col-md-6"><input type="time" class="form-control" name="local_start_time" value="<?php echo esc(substr((string)($c->local_start_time??''),0,5)); ?>"></div><div class="col-md-6"><input type="time" class="form-control" name="local_end_time" value="<?php echo esc(substr((string)($c->local_end_time??''),0,5)); ?>"></div></div>
<div class="row mt-3"><div class="col-md-6"><label><?php echo app_lang('gd_school_start'); ?></label><input type="date" class="form-control" name="starts_on" value="<?php echo esc($c->starts_on??''); ?>"></div><div class="col-md-6"><label><?php echo app_lang('gd_school_end'); ?></label><input type="date" class="form-control" name="ends_on" value="<?php echo esc($c->ends_on??''); ?>"></div></div>
<?php if(!$c): ?><div class="form-check mt-3"><input class="form-check-input" type="checkbox" name="create_series" value="1" id="create-series"><label for="create-series"><?php echo app_lang('gd_school_create_series'); ?></label></div><?php endif; ?>
<div class="form-group mt-3"><label><?php echo app_lang('gd_status'); ?></label><?php echo form_dropdown('status',array_combine($statuses,array_map(fn($x)=>app_lang('gd_school_status_'.$x),$statuses)),$c->status??'active','class="form-control"'); ?></div>
<div class="form-group"><label><?php echo app_lang('gd_notes'); ?></label><textarea class="form-control" name="notes"><?php echo esc($c->notes??''); ?></textarea></div></div>
<div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal"><?php echo app_lang('close'); ?></button><button type="submit" class="btn btn-primary"><?php echo app_lang('save'); ?></button></div><?php echo form_close(); ?>
<script>$(document).ready(function(){"use strict";$("#class-form").appForm({onSuccess:function(){location.reload();}});$("#class-form .select2").select2();});</script>
